#!/usr/bin/env ruby
# frozen_string_literal: true

require "json"
require "open3"
require "pathname"

def assert(condition, message)
  return if condition

  warn "FAIL: #{message}"
  exit 1
end

project_root = Pathname.new(__dir__).join("..").realpath
command = ["ruby", project_root.join("bin/xnix-compatd").to_s]

stdout, stderr, status = Open3.capture3(*command, "probe")
assert(status.success?, "runtime daemon probe must exit successfully: #{stderr}")
probe = JSON.parse(stdout)
assert(probe["version"] == "0.2.57", "runtime daemon probe must report the current version")
assert(probe["bus_name"] == "org.xnix.Compatibility1", "runtime daemon probe must keep the stable bus name")
assert(probe["capabilities"]["recipe_store"], "runtime daemon probe must expose recipe store capability")
assert(probe["capabilities"]["registry_backed_recipe_store"], "runtime daemon probe must expose registry-backed recipe loading")
assert(probe["capabilities"]["application_state_roots"], "runtime daemon probe must expose application state roots")
assert(probe["capabilities"]["compatibility_acquisition_preflight"], "runtime daemon probe must expose acquisition preflight capability")
assert(probe["capabilities"]["compatibility_action_queues"], "runtime daemon probe must expose action queue capability")
assert(probe["capabilities"]["compatibility_action_review_receipts"], "runtime daemon probe must expose action review receipt capability")
assert(probe["capabilities"]["compatibility_artifact_manifests"], "runtime daemon probe must expose artifact manifest capability")
assert(probe["capabilities"]["compatibility_engine_catalog"], "runtime daemon probe must expose engine catalog capability")
assert(probe["capabilities"]["compatibility_install_planning"], "runtime daemon probe must expose install planning capability")
assert(probe["capabilities"]["compatibility_package_sources"], "runtime daemon probe must expose package source capability")
assert(probe["capabilities"]["compatibility_backend_binding"], "runtime daemon probe must expose backend binding capability")
assert(probe["capabilities"]["compatibility_run_planning"], "runtime daemon probe must expose run planning capability")
assert(probe["capabilities"]["compatibility_repair_planning"], "runtime daemon probe must expose repair planning capability")
assert(probe["capabilities"]["compatibility_test_planning"], "runtime daemon probe must expose test planning capability")
assert(probe["capabilities"]["compatibility_test_results"], "runtime daemon probe must expose test result capability")
assert(probe["capabilities"]["ai_diagnostic_inputs"], "runtime daemon probe must expose AI diagnostic input capability")
assert(probe["capabilities"]["ai_diagnostic_recommendations"], "runtime daemon probe must expose AI diagnostic recommendation capability")
assert(probe["capabilities"]["ai_repair_approval_gates"], "runtime daemon probe must expose AI repair approval gate capability")
assert(probe["capabilities"]["runtime_live_owner_gates"], "runtime daemon probe must expose Runtime live owner gate capability")
assert(probe["capabilities"]["runtime_method_parity_manifests"], "runtime daemon probe must expose Runtime method parity manifest capability")
assert(probe["capabilities"]["runtime_owner_smoke_plans"], "runtime daemon probe must expose Runtime owner smoke plan capability")
assert(probe["capabilities"]["runtime_service_binding"], "runtime daemon probe must expose Runtime service binding capability")
assert(probe["capabilities"]["runtime_write_gates"], "runtime daemon probe must expose Runtime write gate capability")
assert(probe["capabilities"]["compatibility_settings"], "runtime daemon probe must expose compatibility settings capability")
assert(probe["capabilities"]["compatibility_settings_change_planning"], "runtime daemon probe must expose settings change planning capability")
assert(probe["capabilities"]["dbus_method_dispatch"], "runtime daemon probe must expose method dispatch capability")
assert(!probe["capabilities"]["dbus_binding"], "runtime daemon must not claim a D-Bus binding before it exists")
assert(probe["recipe_trust"]["registry_backed"], "runtime daemon probe must report registry-backed recipe loading")
assert(probe["recipe_trust"]["digest_verified"], "runtime daemon probe must report digest-verified recipes")
assert(!probe["recipe_trust"]["signed_recipe_validation"], "runtime daemon probe must not claim production recipe signatures yet")

stdout, stderr, status = Open3.capture3(*command, "list-applications")
assert(status.success?, "runtime daemon list must exit successfully: #{stderr}")
applications = JSON.parse(stdout)
assert(applications.length == 1, "runtime daemon must list the bundled sample application")
assert(applications.first["id"] == "org.xnix.sample.notepad", "runtime daemon must expose sample recipe id")
assert(applications.first["mime_types"].include?("application/x-xnix-txt"), "runtime daemon must expose MIME types")

stdout, stderr, status = Open3.capture3(*command, "diagnostics", "org.xnix.sample.notepad")
assert(status.success?, "runtime daemon diagnostics must exit successfully: #{stderr}")
diagnostics = JSON.parse(stdout)
assert(diagnostics["status"] == "known", "runtime daemon diagnostics must know bundled recipes")
assert(diagnostics["checks"].any? { |check| check["status"] == "pending" }, "runtime daemon must report backend work as pending")
assert(diagnostics["test_plan"]["plan_type"] == "compatibility-test", "runtime daemon diagnostics must include compatibility test planning")
assert(diagnostics["test_plan"]["pending_step_count"] == 3, "runtime daemon diagnostics must count pending test steps")
assert(diagnostics["test_result"]["result_type"] == "compatibility-test-result", "runtime daemon diagnostics must include compatibility test results")
assert(diagnostics["test_result"]["overall_status"] == "pending", "runtime daemon diagnostics must expose pending test status")
assert(diagnostics["test_result"]["counts"]["pending"] == 3, "runtime daemon diagnostics must count pending test results")
assert(diagnostics["action_queue"]["queue_type"] == "compatibility-center-action-queue", "runtime daemon diagnostics must include action queues")
assert(diagnostics["action_queue"]["action_count"] == 5, "runtime daemon diagnostics must count action queue items")
assert(diagnostics["action_queue"]["user_review_required_count"] == 3, "runtime daemon diagnostics must count review-required actions")
assert(!diagnostics["action_queue"]["execution_enabled"], "runtime daemon diagnostics must not enable queued action execution")
assert(diagnostics["action_review_receipt"]["receipt_type"] == "compatibility-center-action-review-receipt", "runtime daemon diagnostics must include action review receipts")
assert(diagnostics["action_review_receipt"]["decision_recorded"], "runtime daemon diagnostics must record review intent")
assert(!diagnostics["action_review_receipt"]["execution_enabled"], "runtime daemon diagnostics must not enable review receipt execution")
assert(!diagnostics["action_review_receipt"]["resource_grant_created"], "runtime daemon diagnostics must not create resource grants from review receipts")
assert(diagnostics["install_plan"]["plan_type"] == "compatibility-install-plan", "runtime daemon diagnostics must include install planning")
assert(diagnostics["install_plan"]["install_state"] == "planned", "runtime daemon diagnostics must expose install plan state")
assert(!diagnostics["install_plan"]["install_ready"], "runtime daemon diagnostics must not claim install readiness")
assert(!diagnostics["install_plan"]["download_enabled"], "runtime daemon diagnostics must not enable install downloads")
assert(!diagnostics["install_plan"]["install_enabled"], "runtime daemon diagnostics must not enable install execution")
assert(diagnostics["acquisition_preflight"]["preflight_type"] == "compatibility-acquisition-preflight", "runtime daemon diagnostics must include acquisition preflight")
assert(diagnostics["acquisition_preflight"]["preflight_state"] == "planned", "runtime daemon diagnostics must expose acquisition preflight state")
assert(!diagnostics["acquisition_preflight"]["acquisition_ready"], "runtime daemon diagnostics must not claim acquisition readiness")
assert(!diagnostics["acquisition_preflight"]["download_enabled"], "runtime daemon diagnostics must not enable downloads")
assert(diagnostics["artifact_manifest"]["manifest_type"] == "compatibility-artifact-manifest", "runtime daemon diagnostics must include artifact manifests")
assert(diagnostics["artifact_manifest"]["manifest_state"] == "planned", "runtime daemon diagnostics must expose artifact manifest state")
assert(!diagnostics["artifact_manifest"]["manifest_ready"], "runtime daemon diagnostics must not claim artifact manifest readiness")
assert(!diagnostics["artifact_manifest"]["download_enabled"], "runtime daemon diagnostics must not enable artifact downloads")
assert(diagnostics["package_source"]["source_type"] == "compatibility-package-source", "runtime daemon diagnostics must include package sources")
assert(diagnostics["package_source"]["source_selection_state"] == "planned", "runtime daemon diagnostics must expose package source state")
assert(!diagnostics["package_source"]["package_source_ready"], "runtime daemon diagnostics must not claim package source readiness")
assert(!diagnostics["package_source"]["install_enabled"], "runtime daemon diagnostics must not enable package installation")
assert(diagnostics["state_root"]["root_type"] == "compatibility-application-state-root", "runtime daemon diagnostics must include application state roots")
assert(diagnostics["state_root"]["allocation_state"] == "planned", "runtime daemon diagnostics must expose planned state roots")
assert(!diagnostics["state_root"]["user_documents_included"], "runtime daemon diagnostics must exclude user documents from state roots")
assert(diagnostics["backend_binding"]["binding_type"] == "compatibility-backend-binding", "runtime daemon diagnostics must include backend binding")
assert(!diagnostics["backend_binding"]["managed_binding_ready"], "runtime daemon diagnostics must not claim backend binding readiness")
assert(!diagnostics["backend_binding"]["launch_enabled"], "runtime daemon diagnostics must not enable backend launch yet")
assert(diagnostics["ai_diagnostic_input"]["input_type"] == "ai-diagnostic-input", "runtime daemon diagnostics must include AI diagnostic input")
assert(diagnostics["ai_diagnostic_input"]["safe_for_ai_diagnostics"], "runtime daemon diagnostics must mark AI diagnostic input safe")
assert(!diagnostics["ai_diagnostic_input"]["ai_provider_called"], "runtime daemon diagnostics must not claim an AI provider call")
assert(diagnostics["ai_diagnostic_recommendation"]["recommendation_type"] == "ai-diagnostic-recommendation", "runtime daemon diagnostics must include AI diagnostic recommendations")
assert(diagnostics["ai_diagnostic_recommendation"]["recommendation_count"] == 3, "runtime daemon diagnostics must count AI diagnostic recommendations")
assert(!diagnostics["ai_diagnostic_recommendation"]["ai_provider_called"], "runtime daemon diagnostics must not claim recommendation AI provider calls")
assert(diagnostics["ai_repair_approval_gate"]["gate_type"] == "ai-repair-approval-gate", "runtime daemon diagnostics must include AI repair approval gates")
assert(diagnostics["ai_repair_approval_gate"]["gate_decision"] == "blocked-until-approval", "runtime daemon diagnostics must block repair execution until approval")
assert(!diagnostics["ai_repair_approval_gate"]["auto_execution_allowed"], "runtime daemon diagnostics must not allow automatic AI repair execution")
assert(diagnostics["runtime_live_owner_gate"]["gate_type"] == "runtime-live-owner-gate", "runtime daemon diagnostics must include Runtime live owner gates")
assert(diagnostics["runtime_live_owner_gate"]["activation_binding_ready"], "runtime daemon diagnostics must expose live owner activation readiness")
assert(!diagnostics["runtime_live_owner_gate"]["live_dbus_owner_ready"], "runtime daemon diagnostics must not claim live D-Bus owner readiness")
assert(!diagnostics["runtime_live_owner_gate"]["production_owner_enabled"], "runtime daemon diagnostics must not enable production ownership")
assert(!diagnostics["runtime_live_owner_gate"]["owner_transition_ready"], "runtime daemon diagnostics must not enable owner transition")
assert(!diagnostics["runtime_live_owner_gate"]["smoke_adapter_is_production_owner"], "runtime daemon diagnostics must not treat smoke adapter as production owner")
assert(diagnostics["runtime_owner_smoke_plan"]["plan_type"] == "runtime-owner-smoke-plan", "runtime daemon diagnostics must include Runtime owner smoke plans")
assert(diagnostics["runtime_owner_smoke_plan"]["smoke_state"] == "planned", "runtime daemon diagnostics must keep owner smoke planned")
assert(diagnostics["runtime_owner_smoke_plan"]["pending_step_count"] == 6, "runtime daemon diagnostics must count pending owner smoke steps")
assert(!diagnostics["runtime_owner_smoke_plan"]["system_service_started"], "runtime daemon diagnostics must not start system services")
assert(!diagnostics["runtime_owner_smoke_plan"]["production_bus_claimed"], "runtime daemon diagnostics must not claim production bus ownership")
assert(diagnostics["runtime_method_parity_manifest"]["manifest_type"] == "runtime-method-parity-manifest", "runtime daemon diagnostics must include Runtime method parity manifests")
assert(diagnostics["runtime_method_parity_manifest"]["method_count"] == 28, "runtime daemon diagnostics must count read-only methods")
assert(diagnostics["runtime_method_parity_manifest"]["read_only_method_parity_ready"], "runtime daemon diagnostics must report read-only parity readiness")
assert(!diagnostics["runtime_method_parity_manifest"]["write_methods_supported"], "runtime daemon diagnostics must not claim write method support")
assert(!diagnostics["runtime_method_parity_manifest"]["write_method_dispatch_enabled"], "runtime daemon diagnostics must not enable write method dispatch")
assert(diagnostics["runtime_write_gate"]["gate_type"] == "runtime-write-gate", "runtime daemon diagnostics must include Runtime write gates")
assert(diagnostics["runtime_write_gate"]["method_name"] == "Launch", "runtime daemon diagnostics must summarize launch write gates")
assert(diagnostics["runtime_write_gate"]["gate_decision"] == "blocked-until-production-backend", "runtime daemon diagnostics must block write gates")
assert(!diagnostics["runtime_write_gate"]["write_method_enabled"], "runtime daemon diagnostics must not enable write gates")
assert(!diagnostics["runtime_write_gate"]["dispatch_enabled"], "runtime daemon diagnostics must not enable write dispatch")
assert(!diagnostics["runtime_write_gate"]["request_object_created"], "runtime daemon diagnostics must not create write request objects")
assert(diagnostics["runtime_service_binding"]["binding_type"] == "runtime-service-binding", "runtime daemon diagnostics must include Runtime service binding status")
assert(diagnostics["runtime_service_binding"]["activation_binding_ready"], "runtime daemon diagnostics must expose activation binding readiness")
assert(!diagnostics["runtime_service_binding"]["live_dbus_owner_ready"], "runtime daemon diagnostics must not claim live D-Bus ownership")
assert(diagnostics["settings"]["request_type"] == "settings-model", "runtime daemon diagnostics must include compatibility settings")
assert(diagnostics["settings"]["settings_state"] == "planned", "runtime daemon diagnostics must expose settings state")
assert(!diagnostics["settings"]["settings_persisted"], "runtime daemon diagnostics must not claim settings persistence")
assert(!diagnostics["settings"]["host_root_modified"], "runtime daemon diagnostics must not mutate host root for settings")
assert(diagnostics["settings_change_plan"]["plan_type"] == "settings-change-plan", "runtime daemon diagnostics must include settings change planning")
assert(diagnostics["settings_change_plan"]["change_state"] == "planned", "runtime daemon diagnostics must expose settings change plan state")
assert(!diagnostics["settings_change_plan"]["apply_enabled"], "runtime daemon diagnostics must not enable settings changes yet")
assert(!diagnostics["settings_change_plan"]["settings_persisted"], "runtime daemon diagnostics must not persist planned settings changes")
assert(diagnostics["repair_plan"]["plan_type"] == "compatibility-repair", "runtime daemon diagnostics must include repair planning")
assert(diagnostics["repair_plan"]["issue"] == "engine-binding-pending", "runtime daemon diagnostics must identify the pending repair issue")
assert(diagnostics["repair_plan"]["snapshot_required"], "runtime daemon diagnostics repair plan must require snapshots")
assert(diagnostics["repair_plan"]["snapshot_plan"]["plan_type"] == "compatibility-snapshot", "runtime daemon diagnostics must include snapshot planning")
assert(diagnostics["repair_plan"]["snapshot_plan"]["restore_available"], "runtime daemon diagnostics snapshot plan must expose restore availability")

diagnostics_json = JSON.pretty_generate(diagnostics)
assert(!diagnostics_json.match?(/wine|prefix|\.wine|proton|virtual machine/i), "runtime diagnostics must not expose backend implementation terms")

_stdout, stderr, status = Open3.capture3(*command, "diagnostics", "org.xnix.missing")
assert(!status.success?, "runtime daemon must reject unknown applications")
assert(stderr.include?("unknown application"), "runtime daemon must explain unknown applications")

stdout, stderr, status = Open3.capture3(*command, "test-plan", "org.xnix.sample.notepad")
assert(status.success?, "runtime daemon test-plan must exit successfully: #{stderr}")
test_plan = JSON.parse(stdout)
assert(test_plan["plan_type"] == "compatibility-test", "runtime daemon test-plan command must emit a test plan")
assert(test_plan["steps"].any? { |step| step["id"] == "portal-preflight" }, "runtime daemon test-plan must include Portal preflight")

stdout, stderr, status = Open3.capture3(*command, "test-result", "org.xnix.sample.notepad")
assert(status.success?, "runtime daemon test-result must exit successfully: #{stderr}")
test_result = JSON.parse(stdout)
assert(test_result["result_type"] == "compatibility-test-result", "runtime daemon test-result command must emit a test result")
assert(test_result["overall_status"] == "pending", "runtime daemon test-result must expose pending status")

stdout, stderr, status = Open3.capture3(*command, "action-queue", "org.xnix.sample.notepad")
assert(status.success?, "runtime daemon action-queue must exit successfully: #{stderr}")
action_queue = JSON.parse(stdout)
assert(action_queue["queue_type"] == "compatibility-center-action-queue", "runtime daemon action-queue command must emit an action queue")
assert(action_queue["action_count"] == 5, "runtime daemon action-queue command must count actions")
assert(!action_queue["execution_enabled"], "runtime daemon action-queue command must not enable execution")

stdout, stderr, status = Open3.capture3(*command, "action-review", "org.xnix.sample.notepad", "review-ai-repair", "approved")
assert(status.success?, "runtime daemon action-review must exit successfully: #{stderr}")
action_review = JSON.parse(stdout)
assert(action_review["receipt_type"] == "compatibility-center-action-review-receipt", "runtime daemon action-review command must emit a receipt")
assert(action_review["decision_recorded"], "runtime daemon action-review command must record review intent")
assert(!action_review["execution_enabled"], "runtime daemon action-review command must not enable execution")

stdout, stderr, status = Open3.capture3(*command, "backend-binding", "org.xnix.sample.notepad")
assert(status.success?, "runtime daemon backend-binding must exit successfully: #{stderr}")
backend_binding = JSON.parse(stdout)
assert(backend_binding["binding_type"] == "compatibility-backend-binding", "runtime daemon backend-binding command must emit a backend binding")
assert(!backend_binding["managed_binding_ready"], "runtime daemon backend-binding must not claim readiness")

stdout, stderr, status = Open3.capture3(*command, "state-root", "org.xnix.sample.notepad")
assert(status.success?, "runtime daemon state-root must exit successfully: #{stderr}")
state_root = JSON.parse(stdout)
assert(state_root["root_type"] == "compatibility-application-state-root", "runtime daemon state-root command must emit a state root")
assert(state_root["allocation_state"] == "planned", "runtime daemon state-root must not claim allocation")

stdout, stderr, status = Open3.capture3(*command, "package-source", "org.xnix.sample.notepad")
assert(status.success?, "runtime daemon package-source must exit successfully: #{stderr}")
package_source = JSON.parse(stdout)
assert(package_source["source_type"] == "compatibility-package-source", "runtime daemon package-source command must emit a package source")
assert(!package_source["install_enabled"], "runtime daemon package-source must not enable installation")

stdout, stderr, status = Open3.capture3(*command, "acquisition-preflight", "org.xnix.sample.notepad")
assert(status.success?, "runtime daemon acquisition-preflight must exit successfully: #{stderr}")
acquisition_preflight = JSON.parse(stdout)
assert(acquisition_preflight["preflight_type"] == "compatibility-acquisition-preflight", "runtime daemon acquisition-preflight command must emit acquisition preflight")
assert(!acquisition_preflight["download_enabled"], "runtime daemon acquisition-preflight must not enable downloads")

stdout, stderr, status = Open3.capture3(*command, "artifact-manifest", "org.xnix.sample.notepad")
assert(status.success?, "runtime daemon artifact-manifest must exit successfully: #{stderr}")
artifact_manifest = JSON.parse(stdout)
assert(artifact_manifest["manifest_type"] == "compatibility-artifact-manifest", "runtime daemon artifact-manifest command must emit artifact manifest")
assert(!artifact_manifest["download_enabled"], "runtime daemon artifact-manifest must not enable downloads")

stdout, stderr, status = Open3.capture3(*command, "install-plan", "org.xnix.sample.notepad")
assert(status.success?, "runtime daemon install-plan must exit successfully: #{stderr}")
install_plan = JSON.parse(stdout)
assert(install_plan["plan_type"] == "compatibility-install-plan", "runtime daemon install-plan command must emit install plan")
assert(!install_plan["download_enabled"], "runtime daemon install-plan must not enable downloads")
assert(!install_plan["install_enabled"], "runtime daemon install-plan must not enable installation")

stdout, stderr, status = Open3.capture3(*command, "ai-diagnostic-input", "org.xnix.sample.notepad")
assert(status.success?, "runtime daemon ai-diagnostic-input must exit successfully: #{stderr}")
ai_input = JSON.parse(stdout)
assert(ai_input["input_type"] == "ai-diagnostic-input", "runtime daemon ai-diagnostic-input command must emit an AI diagnostic input")
assert(ai_input["safe_for_ai_diagnostics"], "runtime daemon ai-diagnostic-input must be safe for AI diagnostics")

stdout, stderr, status = Open3.capture3(*command, "ai-diagnostic-recommendation", "org.xnix.sample.notepad")
assert(status.success?, "runtime daemon ai-diagnostic-recommendation must exit successfully: #{stderr}")
ai_recommendation = JSON.parse(stdout)
assert(ai_recommendation["recommendation_type"] == "ai-diagnostic-recommendation", "runtime daemon ai-diagnostic-recommendation command must emit recommendations")
assert(ai_recommendation["recommendations"].length == 3, "runtime daemon ai-diagnostic-recommendation must expose recommendations")

stdout, stderr, status = Open3.capture3(*command, "ai-repair-approval-gate", "org.xnix.sample.notepad")
assert(status.success?, "runtime daemon ai-repair-approval-gate must exit successfully: #{stderr}")
ai_gate = JSON.parse(stdout)
assert(ai_gate["gate_type"] == "ai-repair-approval-gate", "runtime daemon ai-repair-approval-gate command must emit a gate")
assert(ai_gate["gate_decision"] == "blocked-until-approval", "runtime daemon ai-repair-approval-gate must block until approval")

stdout, stderr, status = Open3.capture3(*command, "service-binding")
assert(status.success?, "runtime daemon service-binding must exit successfully: #{stderr}")
service_binding = JSON.parse(stdout)
assert(service_binding["binding_type"] == "runtime-service-binding", "runtime daemon service-binding command must emit service binding")
assert(service_binding["activation_binding_ready"], "runtime daemon service-binding must report activation readiness")

stdout, stderr, status = Open3.capture3(*command, "live-owner-gate")
assert(status.success?, "runtime daemon live-owner-gate must exit successfully: #{stderr}")
live_owner_gate = JSON.parse(stdout)
assert(live_owner_gate["gate_type"] == "runtime-live-owner-gate", "runtime daemon live-owner-gate command must emit a live owner gate")
assert(!live_owner_gate["production_owner_enabled"], "runtime daemon live-owner-gate must not enable production ownership")
assert(!live_owner_gate["owner_transition_ready"], "runtime daemon live-owner-gate must not enable owner transition")
assert(!live_owner_gate["smoke_adapter_is_production_owner"], "runtime daemon live-owner-gate must not treat the smoke adapter as production owner")

stdout, stderr, status = Open3.capture3(*command, "owner-smoke-plan")
assert(status.success?, "runtime daemon owner-smoke-plan must exit successfully: #{stderr}")
owner_smoke_plan = JSON.parse(stdout)
assert(owner_smoke_plan["plan_type"] == "runtime-owner-smoke-plan", "runtime daemon owner-smoke-plan command must emit a smoke plan")
assert(owner_smoke_plan["smoke_state"] == "planned", "runtime daemon owner-smoke-plan must stay planned")
assert(!owner_smoke_plan["system_service_started"], "runtime daemon owner-smoke-plan must not start a system service")
assert(!owner_smoke_plan["production_bus_claimed"], "runtime daemon owner-smoke-plan must not claim production bus ownership")

stdout, stderr, status = Open3.capture3(*command, "method-parity")
assert(status.success?, "runtime daemon method-parity must exit successfully: #{stderr}")
method_parity = JSON.parse(stdout)
assert(method_parity["manifest_type"] == "runtime-method-parity-manifest", "runtime daemon method-parity command must emit a manifest")
assert(method_parity["read_only_method_parity_ready"], "runtime daemon method-parity must report read-only parity readiness")
assert(!method_parity["write_methods_supported"], "runtime daemon method-parity must not claim write method support")

stdout, stderr, status = Open3.capture3(*command, "write-gate", "Launch")
assert(status.success?, "runtime daemon write-gate must exit successfully: #{stderr}")
write_gate = JSON.parse(stdout)
assert(write_gate["gate_type"] == "runtime-write-gate", "runtime daemon write-gate command must emit a write gate")
assert(write_gate["method_name"] == "Launch", "runtime daemon write-gate command must preserve the method name")
assert(write_gate["gate_decision"] == "blocked-until-production-backend", "runtime daemon write-gate must block production writes")
assert(!write_gate["write_method_enabled"], "runtime daemon write-gate must not enable write methods")

stdout, stderr, status = Open3.capture3(*command, "settings", "org.xnix.sample.notepad")
assert(status.success?, "runtime daemon settings must exit successfully: #{stderr}")
settings = JSON.parse(stdout)
assert(settings["request_type"] == "settings-model", "runtime daemon settings command must emit settings model")
assert(settings["runtime_owned"], "runtime daemon settings command must expose Runtime ownership")

stdout, stderr, status = Open3.capture3(*command, "settings-change", "org.xnix.sample.notepad", "resource-access", "documents", "ask")
assert(status.success?, "runtime daemon settings-change must exit successfully: #{stderr}")
settings_change = JSON.parse(stdout)
assert(settings_change["plan_type"] == "settings-change-plan", "runtime daemon settings-change command must emit a settings change plan")
assert(settings_change["change_state"] == "planned", "runtime daemon settings-change command must expose planned changes")
assert(!settings_change["apply_enabled"], "runtime daemon settings-change command must not enable application yet")
assert(!settings_change["settings_persisted"], "runtime daemon settings-change command must not persist settings yet")

puts "PASS: compatibility runtime daemon unit tests"
