#!/usr/bin/env ruby
# frozen_string_literal: true

require "pathname"

def assert(condition, message)
  return if condition

  warn "FAIL: #{message}"
  exit 1
end

project_root = Pathname.new(__dir__).join("..").realpath
script = project_root.join("scripts/dbus_session_smoke.rb")
source = project_root.join("runtime/dbus/xnix_compatd_smoke.c")
introspection = project_root.join("runtime/dbus/xnix_compatd_introspection.inc")
kde_center = project_root.join("runtime/dbus/xnix_compatd_kde_center.inc")
runtime_models = project_root.join("runtime/dbus/xnix_compatd_runtime_models.inc")
dockerfile = project_root.join("Dockerfile").read
contents = script.read

assert(script.file?, "D-Bus smoke script must exist")
assert(script.executable?, "D-Bus smoke script must be executable")
assert(source.file?, "D-Bus smoke adapter source must exist")
assert(introspection.file?, "D-Bus smoke adapter introspection include must exist")
assert(kde_center.file?, "D-Bus smoke adapter KDE Center include must exist")
assert(runtime_models.file?, "D-Bus smoke adapter Runtime models include must exist")
assert(source.read.include?("xnix_compatd_introspection.inc"), "D-Bus smoke adapter must include its introspection XML")
assert(source.read.include?("xnix_compatd_kde_center.inc"), "D-Bus smoke adapter must include its KDE Center read models")
assert(source.read.include?("xnix_compatd_runtime_models.inc"), "D-Bus smoke adapter must include its Runtime read models")
assert(source.read.include?("go_owner_service_call5"), "D-Bus smoke adapter must call the Go owner service boundary")
assert(source.read.include?("go_owner_service_call_available"), "D-Bus smoke adapter must expose Go owner service-call availability")
assert(source.read.include?("go_owner_trigger_available"), "D-Bus smoke adapter must expose Go owner trigger availability")
assert(source.read.include?("known-app-runtime-status-launch-owner-trigger-preview"), "D-Bus smoke adapter must consume Go owner trigger preview metadata")
assert(source.read.include?("xnix.runtime.owner_service_call.v1"), "D-Bus smoke adapter must expose Go owner service-call schema evidence")
assert(source.read.include?("build_runtime_controlled_launch_action"), "D-Bus smoke adapter must build controlled Runtime launch actions")
assert(source.read.include?("safe_evidence_relative_path"), "D-Bus smoke adapter must validate controlled-launch evidence paths")
assert(source.read.include?("ShowRuntimeControlledLaunch"), "D-Bus smoke adapter must route controlled Runtime launch actions")
assert(source.read.include?("kde_forwards_only_evidence_handle"), "D-Bus smoke adapter must keep KDE launch action handoffs evidence-only")
assert(introspection.read.include?("GetDesktopActivationTransactionPreview"), "D-Bus smoke adapter introspection must expose activation transaction previews")
assert(introspection.read.include?("GetDesktopActivationStatus"), "D-Bus smoke adapter introspection must expose activation status previews")
assert(introspection.read.include?("ShowRuntimeControlledLaunch"), "D-Bus smoke adapter introspection must expose controlled Runtime launch actions")
assert(kde_center.read.include?("build_kde_center_page"), "D-Bus smoke adapter KDE Center include must build application pages")
assert(kde_center.read.include?("GetNotificationPlan"), "D-Bus smoke adapter KDE Center include must preserve notification section routing")
assert(runtime_models.read.include?("build_portal_request_plan"), "D-Bus smoke adapter Runtime models include must build Portal request plans")
assert(runtime_models.read.include?("build_runtime_write_gate"), "D-Bus smoke adapter Runtime models include must preserve write-gate planning")
assert(dockerfile.include?("libglib2.0-dev"), "Dockerfile must install GIO headers for the smoke adapter")
assert(dockerfile.include?("pkg-config"), "Dockerfile must install pkg-config for the smoke adapter build")
assert(dockerfile.include?("xnix_compatd_smoke.c"), "Dockerfile must compile the smoke adapter")
assert(contents.include?("dbus-run-session"), "D-Bus smoke script must start a session bus")
assert(contents.include?("gdbus"), "D-Bus smoke script must use gdbus for runtime calls")
assert(contents.include?("go_owner_service_call_available"), "D-Bus smoke script must assert Go owner service-call availability")
assert(contents.include?("runtime-owner-service-call"), "D-Bus smoke script must assert Go owner service-call payload evidence")
assert(contents.include?("variant_string_field"), "D-Bus smoke script must extract GVariant string fields")
assert(contents.include?("assert_go_owner_service_call_envelope"), "D-Bus smoke script must assert Go owner service-call envelopes")
assert(contents.include?('"service_type": "go-runtime-owner-in-process-service"'), "D-Bus smoke script must assert service-call service type")
assert(contents.include?('"dispatch_ready": true'), "D-Bus smoke script must assert service-call dispatch readiness")
assert(contents.include?('"write_methods_enabled": false'), "D-Bus smoke script must assert service-call write gates")
assert(contents.include?("ListApplications"), "D-Bus smoke script must call ListApplications")
assert(contents.include?("GetDiagnostics"), "D-Bus smoke script must call GetDiagnostics")
assert(contents.include?("GetEngineCatalog"), "D-Bus smoke script must call GetEngineCatalog")
assert(contents.include?("GetRunPlan"), "D-Bus smoke script must call GetRunPlan")
assert(contents.include?("GetApplicationStateRoot"), "D-Bus smoke script must call GetApplicationStateRoot")
assert(contents.include?("GetCompatibilityPackageSource"), "D-Bus smoke script must call GetCompatibilityPackageSource")
assert(contents.include?("GetCompatibilityAcquisitionPreflight"), "D-Bus smoke script must call GetCompatibilityAcquisitionPreflight")
assert(contents.include?("GetCompatibilityArtifactManifest"), "D-Bus smoke script must call GetCompatibilityArtifactManifest")
assert(contents.include?("GetCompatibilityInstallPlan"), "D-Bus smoke script must call GetCompatibilityInstallPlan")
assert(contents.include?("GetBackendBinding"), "D-Bus smoke script must call GetBackendBinding")
assert(contents.include?("GetBackendCapabilityMatrix"), "D-Bus smoke script must call GetBackendCapabilityMatrix")
assert(contents.include?("GetBackendSelectionPlan"), "D-Bus smoke script must call GetBackendSelectionPlan")
assert(contents.include?("GetBackendLifecycle"), "D-Bus smoke script must call GetBackendLifecycle")
assert(contents.include?("GetBackendEnvironmentPlan"), "D-Bus smoke script must call GetBackendEnvironmentPlan")
assert(contents.include?("GetRepairPlan"), "D-Bus smoke script must call GetRepairPlan")
assert(contents.include?("GetTestPlan"), "D-Bus smoke script must call GetTestPlan")
assert(contents.include?("GetTestResult"), "D-Bus smoke script must call GetTestResult")
assert(contents.include?("GetExecutionReadiness"), "D-Bus smoke script must call GetExecutionReadiness")
assert(contents.include?("GetLaunchIntent"), "D-Bus smoke script must call GetLaunchIntent")
assert(contents.include?("GetAIDiagnosticInput"), "D-Bus smoke script must call GetAIDiagnosticInput")
assert(contents.include?("GetAIDiagnosticRecommendation"), "D-Bus smoke script must call GetAIDiagnosticRecommendation")
assert(contents.include?("GetAIRepairApprovalGate"), "D-Bus smoke script must call GetAIRepairApprovalGate")
assert(contents.include?("GetSnapshotPlan"), "D-Bus smoke script must call GetSnapshotPlan")
assert(contents.include?("GetPortalAccessPolicy"), "D-Bus smoke script must call GetPortalAccessPolicy")
assert(contents.include?("GetRuntimeServiceBinding"), "D-Bus smoke script must call GetRuntimeServiceBinding")
assert(contents.include?("GetRuntimeLiveOwnerGate"), "D-Bus smoke script must call GetRuntimeLiveOwnerGate")
assert(contents.include?("GetRuntimeOwnerSmokePlan"), "D-Bus smoke script must call GetRuntimeOwnerSmokePlan")
assert(contents.include?("GetRuntimeMethodParityManifest"), "D-Bus smoke script must call GetRuntimeMethodParityManifest")
assert(contents.include?("GetRuntimeWriteGate"), "D-Bus smoke script must call GetRuntimeWriteGate")
assert(contents.include?("ShowRuntimeControlledLaunch"), "D-Bus smoke script must call ShowRuntimeControlledLaunch")
assert(contents.include?("runtime-controlled-launch-dbus-action"), "D-Bus smoke script must assert controlled launch action evidence")
assert(contents.include?("desktop-action-dispatch"), "D-Bus smoke script must assert controlled launch action dispatch")
assert(contents.include?("evidence-relative-path"), "D-Bus smoke script must assert evidence-only launch handoff")
assert(contents.include?("desktop_receipt_fields_reconstructed"), "D-Bus smoke script must assert desktop receipt reconstruction remains disabled")
assert(contents.include?("desktop_kde_state_root_access"), "D-Bus smoke script must assert desktop state-root access remains disabled")
assert(contents.include?("GetCompatibilitySettings"), "D-Bus smoke script must call GetCompatibilitySettings")
assert(contents.include?("GetCompatibilitySettingsChangePlan"), "D-Bus smoke script must call GetCompatibilitySettingsChangePlan")
assert(contents.include?("GetDesktopIconPlan"), "D-Bus smoke script must call GetDesktopIconPlan")
assert(contents.include?("GetCompatibilityModeSwitchPlan"), "D-Bus smoke script must call GetCompatibilityModeSwitchPlan")
assert(contents.include?("GetCompatibilityPermissionReviewPlan"), "D-Bus smoke script must call GetCompatibilityPermissionReviewPlan")
assert(contents.include?("GetCompatibilityReviewFlowPlan"), "D-Bus smoke script must call GetCompatibilityReviewFlowPlan")
assert(contents.include?("GetCompatibilityActionQueue"), "D-Bus smoke script must call GetCompatibilityActionQueue")
assert(contents.include?("GetCompatibilityActionReviewReceipt"), "D-Bus smoke script must call GetCompatibilityActionReviewReceipt")
assert(contents.include?("GetKDECenterPage"), "D-Bus smoke script must call GetKDECenterPage")
assert(contents.include?("GetKDECenterPageSections"), "D-Bus smoke script must call GetKDECenterPageSections")
assert(contents.include?("GetKDECenterPageSectionDetail"), "D-Bus smoke script must call GetKDECenterPageSectionDetail")
assert(contents.include?("GetKRunnerQueryPlan"), "D-Bus smoke script must call GetKRunnerQueryPlan")
assert(contents.include?("bin/xnix-krunner-model"), "D-Bus smoke script must verify the KRunner D-Bus read model")
assert(contents.include?("GetKDEIntegrationStatus"), "D-Bus smoke script must call GetKDEIntegrationStatus")
assert(contents.include?("bin/xnix-kde-integration-status"), "D-Bus smoke script must verify the KDE integration D-Bus read model")
assert(contents.include?("GetKDEShellIntegrationPlan"), "D-Bus smoke script must call GetKDEShellIntegrationPlan")
assert(contents.include?("GetKWinWindowRulePlan"), "D-Bus smoke script must call GetKWinWindowRulePlan")
assert(contents.include?("bin/xnix-kwin-window-rule"), "D-Bus smoke script must verify the KWin D-Bus read model")

puts "PASS: compatibility runtime D-Bus smoke script unit tests"
