#!/usr/bin/env ruby
# frozen_string_literal: true

require "json"
require "open3"
require "pathname"
require "tmpdir"

def assert(condition, message)
  return if condition

  warn "FAIL: #{message}"
  exit 1
end

project_root = Pathname.new(__dir__).join("..").realpath
core_source = project_root.join("runtime/core/xnix_runtime_core.c")
core_header = project_root.join("runtime/core/xnix_runtime_core.h")
core_cli = project_root.join("runtime/core/xnix_runtime_core_cli.c")

assert(core_header.read.include?("#define XNIX_RUNTIME_VERSION \"0.2.70\""), "C Runtime core must expose the current version")
assert(core_header.read.include?("XNIX_RUNTIME_WRITE_ERROR"), "C Runtime core must define the write-method D-Bus error")
assert(core_header.read.include?("XnixRuntimeApplication"), "C Runtime core must define application catalog records")
assert(core_header.read.include?("XnixRuntimeEngine"), "C Runtime core must define compatibility engine records")
assert(core_header.read.include?("XnixRuntimePortalPolicy"), "C Runtime core must define Portal access policy records")
assert(core_header.read.include?("XnixRuntimeSnapshotPolicy"), "C Runtime core must define snapshot policy records")
assert(core_header.read.include?("XnixRuntimeStateRootPolicy"), "C Runtime core must define state root policy records")
assert(core_header.read.include?("XnixRuntimeInstallReadinessPolicy"), "C Runtime core must define install readiness policy records")
assert(core_header.read.include?("XnixRuntimeArtifactManifestPolicy"), "C Runtime core must define artifact manifest policy records")
assert(core_header.read.include?("XnixRuntimeAcquisitionPreflightPolicy"), "C Runtime core must define acquisition preflight policy records")
assert(core_header.read.include?("XnixRuntimePackageSourcePolicy"), "C Runtime core must define package source policy records")
assert(core_header.read.include?("XnixRuntimeBackendBindingPolicy"), "C Runtime core must define backend binding policy records")
assert(core_header.read.include?("XnixRuntimeSettingsPolicy"), "C Runtime core must define settings policy records")
assert(core_header.read.include?("XnixRuntimeSettingsChangePolicy"), "C Runtime core must define settings change policy records")
assert(core_header.read.include?("XnixRuntimeServiceBindingPolicy"), "C Runtime core must define service binding policy records")
assert(core_header.read.include?("XnixRuntimeLiveOwnerGatePolicy"), "C Runtime core must define live owner gate policy records")
assert(core_source.read.include?("xnix_runtime_write_gate"), "C Runtime core must implement write gate logic")
assert(core_source.read.include?("blocked-until-production-backend"), "C Runtime core must keep write gates blocked")
assert(core_source.read.include?("xnix_runtime_find_application"), "C Runtime core must query application catalog records")
assert(core_source.read.include?("xnix_runtime_select_engine_for_mode"), "C Runtime core must select engine records by recipe mode")
assert(core_source.read.include?("xnix_runtime_find_portal_policy"), "C Runtime core must query Portal access policies")
assert(core_source.read.include?("xnix_runtime_find_snapshot_policy"), "C Runtime core must query snapshot policies")
assert(core_source.read.include?("xnix_runtime_find_state_root_policy"), "C Runtime core must query state root policies")
assert(core_source.read.include?("xnix_runtime_find_install_readiness_policy"), "C Runtime core must query install readiness policies")
assert(core_source.read.include?("xnix_runtime_find_artifact_manifest_policy"), "C Runtime core must query artifact manifest policies")
assert(core_source.read.include?("xnix_runtime_find_acquisition_preflight_policy"), "C Runtime core must query acquisition preflight policies")
assert(core_source.read.include?("xnix_runtime_find_package_source_policy"), "C Runtime core must query package source policies")
assert(core_source.read.include?("xnix_runtime_find_backend_binding_policy"), "C Runtime core must query backend binding policies")
assert(core_source.read.include?("xnix_runtime_find_settings_policy"), "C Runtime core must query settings policies")
assert(core_source.read.include?("xnix_runtime_find_settings_change_policy"), "C Runtime core must query settings change policies")
assert(core_source.read.include?("xnix_runtime_service_binding_policy"), "C Runtime core must expose service binding policy")
assert(core_source.read.include?("xnix_runtime_live_owner_gate_policy"), "C Runtime core must expose live owner gate policy")
assert(core_cli.read.include?("business_logic_runtime"), "C Runtime core CLI must identify the business runtime language")
assert(core_cli.read.include?("list-applications"), "C Runtime core CLI must expose application catalog listing")
assert(core_cli.read.include?("list-engines"), "C Runtime core CLI must expose engine catalog listing")
assert(core_cli.read.include?("list-portal-policies"), "C Runtime core CLI must expose Portal policy listing")
assert(core_cli.read.include?("list-snapshot-policies"), "C Runtime core CLI must expose snapshot policy listing")
assert(core_cli.read.include?("list-state-root-policies"), "C Runtime core CLI must expose state root policy listing")
assert(core_cli.read.include?("list-install-readiness-policies"), "C Runtime core CLI must expose install readiness policy listing")
assert(core_cli.read.include?("list-artifact-manifest-policies"), "C Runtime core CLI must expose artifact manifest policy listing")
assert(core_cli.read.include?("list-acquisition-preflight-policies"), "C Runtime core CLI must expose acquisition preflight policy listing")
assert(core_cli.read.include?("list-package-source-policies"), "C Runtime core CLI must expose package source policy listing")
assert(core_cli.read.include?("list-backend-binding-policies"), "C Runtime core CLI must expose backend binding policy listing")
assert(core_cli.read.include?("list-settings-policies"), "C Runtime core CLI must expose settings policy listing")
assert(core_cli.read.include?("list-settings-change-policies"), "C Runtime core CLI must expose settings change policy listing")
assert(core_cli.read.include?("runtime-service-binding"), "C Runtime core CLI must expose service binding policy")
assert(core_cli.read.include?("runtime-live-owner-gate"), "C Runtime core CLI must expose live owner gate policy")

Dir.mktmpdir("xnix-runtime-core") do |dir|
  binary = Pathname.new(dir).join("xnix-runtime-core")
  _stdout, stderr, status = Open3.capture3(
    "cc",
    "-std=c11",
    "-Wall",
    "-Wextra",
    "-Werror",
    core_source.to_s,
    core_cli.to_s,
    "-o",
    binary.to_s
  )
  assert(status.success?, "C Runtime core must compile cleanly: #{stderr}")

  stdout, stderr, status = Open3.capture3(binary.to_s, "probe")
  assert(status.success?, "C Runtime core probe must exit successfully: #{stderr}")
  probe = JSON.parse(stdout)
  assert(probe["version"] == "0.2.70", "C Runtime core probe must expose the current version")
  assert(probe["core_language"] == "c", "C Runtime core must report C as its implementation language")
  assert(probe["business_logic_runtime"] == "c", "important Runtime business logic must be C-owned")
  assert(probe["ruby_role"] == "tests-and-development-tools", "Ruby must be limited to tests and development tooling")
  assert(probe["bus_name"] == "org.xnix.Compatibility1", "C Runtime core must keep the stable bus name")
  assert(probe["runtime_owned"], "C Runtime core must expose Runtime ownership")
  assert(!probe["kde_policy_owner"], "KDE must not own Runtime policy")
  assert(probe["application_catalog_owner"] == "c", "C Runtime core must own the first application catalog layer")
  assert(probe["application_count"] == 1, "C Runtime core must count registered applications")
  assert(probe["engine_catalog_owner"] == "c", "C Runtime core must own the first engine catalog layer")
  assert(probe["engine_count"] == 3, "C Runtime core must count registered engines")
  assert(probe["portal_policy_owner"] == "c", "C Runtime core must own the first Portal policy layer")
  assert(probe["portal_policy_count"] == 7, "C Runtime core must count registered Portal policies")
  assert(probe["snapshot_policy_owner"] == "c", "C Runtime core must own the first snapshot policy layer")
  assert(probe["snapshot_policy_count"] == 3, "C Runtime core must count registered snapshot policies")
  assert(probe["state_root_policy_owner"] == "c", "C Runtime core must own the first state root policy layer")
  assert(probe["state_root_policy_count"] == 1, "C Runtime core must count registered state root policies")
  assert(probe["install_readiness_policy_owner"] == "c", "C Runtime core must own the first install readiness layer")
  assert(probe["install_readiness_policy_count"] == 1, "C Runtime core must count registered install readiness policies")
  assert(probe["artifact_manifest_policy_owner"] == "c", "C Runtime core must own the first artifact manifest layer")
  assert(probe["artifact_manifest_policy_count"] == 1, "C Runtime core must count registered artifact manifest policies")
  assert(probe["acquisition_preflight_policy_owner"] == "c", "C Runtime core must own the first acquisition preflight layer")
  assert(probe["acquisition_preflight_policy_count"] == 1, "C Runtime core must count registered acquisition preflight policies")
  assert(probe["package_source_policy_owner"] == "c", "C Runtime core must own the first package source layer")
  assert(probe["package_source_policy_count"] == 1, "C Runtime core must count registered package source policies")
  assert(probe["backend_binding_policy_owner"] == "c", "C Runtime core must own the first backend binding layer")
  assert(probe["backend_binding_policy_count"] == 1, "C Runtime core must count registered backend binding policies")
  assert(probe["settings_policy_owner"] == "c", "C Runtime core must own the first settings layer")
  assert(probe["settings_policy_count"] == 1, "C Runtime core must count registered settings policies")
  assert(probe["settings_change_policy_owner"] == "c", "C Runtime core must own the first settings change layer")
  assert(probe["settings_change_policy_count"] == 1, "C Runtime core must count registered settings change policies")
  assert(probe["service_binding_policy_owner"] == "c", "C Runtime core must own the first service binding layer")
  assert(probe["service_binding_policy_count"] == 1, "C Runtime core must count service binding policies")
  assert(probe["live_owner_gate_policy_owner"] == "c", "C Runtime core must own the first live owner gate layer")
  assert(probe["live_owner_gate_policy_count"] == 1, "C Runtime core must count live owner gate policies")
  assert(probe["write_methods"] == %w[InstallRecipe Launch CreateSnapshot RestoreSnapshot], "C Runtime core must list reserved write methods")
  assert(probe["write_method_count"] == 4, "C Runtime core must count write methods")
  assert(!probe["write_methods_supported"], "C Runtime core must not claim write method support")
  assert(!probe["write_method_dispatch_enabled"], "C Runtime core must not enable write dispatch")

  stdout, stderr, status = Open3.capture3(binary.to_s, "list-applications")
  assert(status.success?, "C Runtime core application list must exit successfully: #{stderr}")
  applications = JSON.parse(stdout)
  assert(applications.length == 1, "C Runtime core must list the sample application")
  application = applications.first
  assert(application["id"] == "org.xnix.sample.notepad", "C Runtime core must preserve the recipe id")
  assert(application["name"] == "Sample Notepad", "C Runtime core must preserve the recipe name")
  assert(application["icon"] == "accessories-text-editor", "C Runtime core must preserve the desktop icon")
  assert(application["runtime_mode"] == "automatic", "C Runtime core must preserve the runtime mode")
  assert(application["desktop_category"] == "Utility", "C Runtime core must expose a safe desktop category")
  assert(application["launcher_command"] == "xnix-compat-launch --app org.xnix.sample.notepad %U", "C Runtime core must expose the managed launcher")
  assert(application["primary_extension"] == ".txt", "C Runtime core must expose the primary file extension")
  assert(application["primary_mime_type"] == "application/x-xnix-txt", "C Runtime core must expose the primary MIME type")
  assert(application["runtime_owned"], "C Runtime core application catalog must be Runtime-owned")
  assert(!application["kde_policy_owner"], "C Runtime core application catalog must not make KDE the policy owner")
  assert(!application["backend_details_exposed"], "C Runtime core application catalog must hide backend details")
  assert(!stdout.match?(/wine|prefix|proton|virtual machine/i), "C Runtime core application catalog must not expose backend details")

  stdout, stderr, status = Open3.capture3(binary.to_s, "get-application", "org.xnix.sample.notepad")
  assert(status.success?, "C Runtime core application lookup must exit successfully: #{stderr}")
  found_application = JSON.parse(stdout)
  assert(found_application == application, "C Runtime core lookup must return the catalog record")

  _stdout, stderr, status = Open3.capture3(binary.to_s, "get-application", "org.xnix.unknown")
  assert(!status.success?, "C Runtime core must reject unknown application ids")
  assert(stderr.include?("not registered"), "C Runtime core must explain unknown application validation")

  stdout, stderr, status = Open3.capture3(binary.to_s, "list-engines")
  assert(status.success?, "C Runtime core engine catalog must exit successfully: #{stderr}")
  engine_catalog = JSON.parse(stdout)
  assert(engine_catalog["version"] == "0.2.70", "C Runtime core engine catalog must expose the current version")
  assert(engine_catalog["catalog_type"] == "compatibility-engine", "C Runtime core engine catalog must identify the catalog type")
  assert(engine_catalog["runtime_policy_owner"], "C Runtime core must own engine policy")
  assert(!engine_catalog["desktop_shell_policy_owner"], "C Runtime core must not make the desktop shell the engine policy owner")
  assert(engine_catalog["catalog_owner"] == "c", "C Runtime core engine catalog must be C-owned")
  assert(!engine_catalog["backend_details_exposed"], "C Runtime core engine catalog must hide backend details")
  assert(engine_catalog["engine_count"] == 3, "C Runtime core engine catalog must count engines")
  engines = engine_catalog.fetch("engines")
  assert(engines.map { |engine| engine.fetch("id") } == %w[automatic-managed local-compatibility-engine isolated-compatibility-engine], "C Runtime core must keep engine order stable")
  assert(engines.all? { |engine| !engine.fetch("ready") }, "C Runtime core must not claim engine readiness")
  assert(engines.all? { |engine| !engine.fetch("launch_enabled") }, "C Runtime core must not claim launch enablement")
  assert(engines.all? { |engine| engine.fetch("user_visible") }, "C Runtime core must expose engines as user-visible Runtime strategies")
  assert(engines.all? { |engine| !engine.fetch("backend_details_exposed") }, "C Runtime core engines must hide backend details")
  assert(!stdout.match?(/prefix|\.wine|proton|virtual machine/i), "C Runtime core engine catalog must not expose backend implementation terms")

  stdout, stderr, status = Open3.capture3(binary.to_s, "select-engine", "automatic")
  assert(status.success?, "C Runtime core automatic engine selection must exit successfully: #{stderr}")
  automatic = JSON.parse(stdout)
  assert(automatic["engine_id"] == "automatic-managed", "automatic mode must select the automatic-managed engine")
  assert(!automatic["launch_enabled"], "automatic mode must not enable launch yet")

  stdout, stderr, status = Open3.capture3(binary.to_s, "select-engine", "wine")
  assert(status.success?, "C Runtime core local engine selection must exit successfully: #{stderr}")
  local = JSON.parse(stdout)
  assert(local["engine_id"] == "local-compatibility-engine", "local recipe mode must select the local compatibility engine")
  assert(!local["backend_details_exposed"], "local engine selection must hide backend details")

  stdout, stderr, status = Open3.capture3(binary.to_s, "select-engine", "vm")
  assert(status.success?, "C Runtime core isolated engine selection must exit successfully: #{stderr}")
  isolated = JSON.parse(stdout)
  assert(isolated["engine_id"] == "isolated-compatibility-engine", "isolated recipe mode must select the isolated compatibility engine")

  _stdout, stderr, status = Open3.capture3(binary.to_s, "select-engine", "unknown")
  assert(!status.success?, "C Runtime core must reject unknown recipe modes")
  assert(stderr.include?("mode must be one of"), "C Runtime core must explain recipe mode validation")

  stdout, stderr, status = Open3.capture3(binary.to_s, "list-portal-policies")
  assert(status.success?, "C Runtime core Portal policy catalog must exit successfully: #{stderr}")
  portal_catalog = JSON.parse(stdout)
  assert(portal_catalog["version"] == "0.2.70", "C Runtime core Portal policy catalog must expose the current version")
  assert(portal_catalog["catalog_type"] == "portal-access-policy", "C Runtime core Portal policy catalog must identify the catalog type")
  assert(portal_catalog["runtime_policy_owner"], "C Runtime core must own Portal policy")
  assert(!portal_catalog["desktop_shell_policy_owner"], "C Runtime core must not make the desktop shell the Portal policy owner")
  assert(portal_catalog["catalog_owner"] == "c", "C Runtime core Portal policy catalog must be C-owned")
  assert(!portal_catalog["backend_details_exposed"], "C Runtime core Portal policy catalog must hide backend details")
  assert(portal_catalog["policy_count"] == 7, "C Runtime core Portal policy catalog must count policies")
  policies = portal_catalog.fetch("policies")
  assert(policies.map { |policy| policy.fetch("operation") } == %w[file-open uri-open print screenshot clipboard camera remote-desktop], "C Runtime core must keep Portal policy order stable")
  assert(policies.all? { |policy| policy.fetch("portal_required") }, "C Runtime core policies must require portals")
  assert(policies.all? { |policy| policy.fetch("user_mediation_required") }, "C Runtime core policies must require user mediation")
  assert(policies.all? { |policy| !policy.fetch("direct_access_allowed") }, "C Runtime core policies must deny direct desktop access")
  assert(policies.all? { |policy| policy.fetch("runtime_policy_owner") }, "C Runtime core policies must be Runtime-owned")
  assert(policies.all? { |policy| !policy.fetch("desktop_shell_policy_owner") }, "C Runtime core policies must not be KDE-owned")
  assert(policies.all? { |policy| !policy.fetch("backend_details_exposed") }, "C Runtime core policies must hide backend details")
  assert(!stdout.match?(/wine|prefix|\.wine|proton|virtual machine/i), "C Runtime core Portal policy catalog must not expose backend implementation terms")

  stdout, stderr, status = Open3.capture3(binary.to_s, "portal-policy", "org.xnix.sample.notepad", "file-open")
  assert(status.success?, "C Runtime core file Portal policy must exit successfully: #{stderr}")
  file_policy = JSON.parse(stdout)
  assert(file_policy["policy_type"] == "portal-access", "C Runtime core Portal policy must identify the policy type")
  assert(file_policy["desktop"] == "KDE Plasma", "C Runtime core Portal policy must target KDE Plasma")
  assert(file_policy["application_id"] == "org.xnix.sample.notepad", "C Runtime core Portal policy must preserve the application id")
  assert(file_policy["operation"] == "file-open", "C Runtime core Portal policy must preserve the operation")
  assert(file_policy["decision"] == "ask", "C Runtime core must ask for file access")
  assert(file_policy["portal_interface"] == "org.freedesktop.portal.FileChooser", "C Runtime core must select the file chooser Portal")
  assert(file_policy["resources"].include?("selected-files"), "C Runtime core must scope selected files")
  assert(file_policy["request_flow"]["dbus_api"] == "XDG Desktop Portal", "C Runtime core Portal policy must use XDG Desktop Portal")
  assert(file_policy["request_flow"]["runtime_policy_owner"], "C Runtime core Portal request flow must be Runtime-owned")
  assert(!file_policy["request_flow"]["desktop_shell_policy_owner"], "C Runtime core Portal request flow must not be KDE-owned")
  assert(!file_policy["direct_access_allowed"], "C Runtime core Portal policy must deny direct access")
  assert(!file_policy["backend_details_exposed"], "C Runtime core Portal policy must hide backend details")

  stdout, stderr, status = Open3.capture3(binary.to_s, "portal-policy", "org.xnix.sample.notepad", "camera")
  assert(status.success?, "C Runtime core camera Portal policy must exit successfully: #{stderr}")
  camera_policy = JSON.parse(stdout)
  assert(camera_policy["decision"] == "deny", "C Runtime core must deny camera access by default")

  _stdout, stderr, status = Open3.capture3(binary.to_s, "portal-policy", "org.xnix.unknown", "file-open")
  assert(!status.success?, "C Runtime core must reject Portal policy for unknown applications")
  assert(stderr.include?("application is not registered"), "C Runtime core must explain unknown Portal application validation")

  _stdout, stderr, status = Open3.capture3(binary.to_s, "portal-policy", "org.xnix.sample.notepad", "unknown")
  assert(!status.success?, "C Runtime core must reject unknown Portal operations")
  assert(stderr.include?("registered sensitive desktop operation"), "C Runtime core must explain unknown Portal operation validation")

  stdout, stderr, status = Open3.capture3(binary.to_s, "list-snapshot-policies")
  assert(status.success?, "C Runtime core snapshot policy catalog must exit successfully: #{stderr}")
  snapshot_catalog = JSON.parse(stdout)
  assert(snapshot_catalog["version"] == "0.2.70", "C Runtime core snapshot policy catalog must expose the current version")
  assert(snapshot_catalog["catalog_type"] == "snapshot-policy", "C Runtime core snapshot policy catalog must identify the catalog type")
  assert(snapshot_catalog["runtime_policy_owner"], "C Runtime core must own snapshot policy")
  assert(!snapshot_catalog["desktop_shell_policy_owner"], "C Runtime core must not make the desktop shell the snapshot policy owner")
  assert(snapshot_catalog["catalog_owner"] == "c", "C Runtime core snapshot policy catalog must be C-owned")
  assert(!snapshot_catalog["backend_details_exposed"], "C Runtime core snapshot policy catalog must hide backend details")
  assert(!snapshot_catalog["host_root_modified"], "C Runtime core snapshot policy catalog must not mutate the host root")
  assert(snapshot_catalog["policy_count"] == 3, "C Runtime core snapshot policy catalog must count policies")
  snapshot_policies = snapshot_catalog.fetch("policies")
  assert(snapshot_policies.map { |policy| policy.fetch("reason") } == %w[before-repair before-engine-change manual], "C Runtime core must keep snapshot policy order stable")
  assert(snapshot_policies.all? { |policy| policy.fetch("enabled_by_default") }, "C Runtime core snapshot policies must default to enabled")
  assert(snapshot_policies.all? { |policy| policy.fetch("snapshot_scope").fetch("application_state") }, "C Runtime core snapshot policies must include application state")
  assert(snapshot_policies.all? { |policy| policy.fetch("snapshot_scope").fetch("runtime_metadata") }, "C Runtime core snapshot policies must include Runtime metadata")
  assert(snapshot_policies.all? { |policy| policy.fetch("snapshot_scope").fetch("desktop_activation_receipts") }, "C Runtime core snapshot policies must include desktop activation receipts")
  assert(snapshot_policies.all? { |policy| !policy.fetch("snapshot_scope").fetch("user_documents") }, "C Runtime core snapshot policies must exclude user documents")
  assert(snapshot_policies.all? { |policy| !policy.fetch("snapshot_scope").fetch("host_system") }, "C Runtime core snapshot policies must exclude the host system")
  assert(snapshot_policies.all? { |policy| policy.fetch("restore").fetch("requires_user_confirmation") }, "C Runtime core snapshot restore must require confirmation")
  assert(snapshot_policies.all? { |policy| policy.fetch("restore").fetch("preserve_user_documents") }, "C Runtime core snapshot restore must preserve user documents")
  assert(snapshot_policies.all? { |policy| policy.fetch("retention").fetch("policy") == "bounded" }, "C Runtime core snapshot policies must use bounded retention")
  assert(snapshot_policies.all? { |policy| policy.fetch("retention").fetch("keep_latest") == 5 }, "C Runtime core snapshot policies must keep a bounded latest set")
  assert(snapshot_policies.all? { |policy| policy.fetch("safety").fetch("runtime_policy_owner") }, "C Runtime core snapshot policies must be Runtime-owned")
  assert(snapshot_policies.all? { |policy| !policy.fetch("safety").fetch("desktop_shell_policy_owner") }, "C Runtime core snapshot policies must not be KDE-owned")
  assert(snapshot_policies.all? { |policy| !policy.fetch("safety").fetch("backend_details_exposed") }, "C Runtime core snapshot policies must hide backend details")
  assert(snapshot_policies.all? { |policy| !policy.fetch("safety").fetch("host_root_modified") }, "C Runtime core snapshot policies must not mutate the host root")
  assert(!stdout.match?(/wine|prefix|\.wine|proton|virtual machine/i), "C Runtime core snapshot policy catalog must not expose backend implementation terms")

  stdout, stderr, status = Open3.capture3(binary.to_s, "snapshot-policy", "org.xnix.sample.notepad", "before-repair")
  assert(status.success?, "C Runtime core snapshot policy must exit successfully: #{stderr}")
  snapshot_policy = JSON.parse(stdout)
  assert(snapshot_policy["plan_type"] == "compatibility-snapshot", "C Runtime core snapshot policy must identify the plan type")
  assert(snapshot_policy["application_id"] == "org.xnix.sample.notepad", "C Runtime core snapshot policy must preserve the application id")
  assert(snapshot_policy["reason"] == "before-repair", "C Runtime core snapshot policy must preserve the reason")
  assert(snapshot_policy["restore"]["method"] == "Runtime.RestoreSnapshot", "C Runtime core snapshot policy must expose the restore method")
  assert(snapshot_policy["retention"]["keep_latest"] == 5, "C Runtime core snapshot policy must expose retention")

  _stdout, stderr, status = Open3.capture3(binary.to_s, "snapshot-policy", "org.xnix.unknown", "manual")
  assert(!status.success?, "C Runtime core must reject snapshot policy for unknown applications")
  assert(stderr.include?("application is not registered"), "C Runtime core must explain unknown snapshot application validation")

  _stdout, stderr, status = Open3.capture3(binary.to_s, "snapshot-policy", "org.xnix.sample.notepad", "unknown")
  assert(!status.success?, "C Runtime core must reject unknown snapshot reasons")
  assert(stderr.include?("registered snapshot reason"), "C Runtime core must explain unknown snapshot reason validation")

  stdout, stderr, status = Open3.capture3(binary.to_s, "list-state-root-policies")
  assert(status.success?, "C Runtime core state root policy catalog must exit successfully: #{stderr}")
  state_root_catalog = JSON.parse(stdout)
  assert(state_root_catalog["version"] == "0.2.70", "C Runtime core state root policy catalog must expose the current version")
  assert(state_root_catalog["catalog_type"] == "application-state-root-policy", "C Runtime core state root policy catalog must identify the catalog type")
  assert(state_root_catalog["runtime_policy_owner"], "C Runtime core must own state root policy")
  assert(!state_root_catalog["desktop_shell_policy_owner"], "C Runtime core must not make the desktop shell the state root policy owner")
  assert(state_root_catalog["catalog_owner"] == "c", "C Runtime core state root policy catalog must be C-owned")
  assert(!state_root_catalog["backend_details_exposed"], "C Runtime core state root policy catalog must hide backend details")
  assert(!state_root_catalog["host_root_modified"], "C Runtime core state root policy catalog must not mutate the host root")
  assert(state_root_catalog["policy_count"] == 1, "C Runtime core state root policy catalog must count policies")
  state_root_records = state_root_catalog.fetch("policies")
  state_root_record = state_root_records.fetch(0)
  assert(state_root_record["application_id"] == "org.xnix.sample.notepad", "C Runtime core state root policy must preserve the application id")
  assert(state_root_record["state_namespace"] == "org.xnix.sample.notepad", "C Runtime core state root policy must expose a stable namespace")
  assert(state_root_record["storage_scope"] == "per-application", "C Runtime core state root policy must remain per-application")
  assert(state_root_record["allocation_state"] == "planned", "C Runtime core state root policy must not claim allocation")
  assert(state_root_record["runtime_owned"], "C Runtime core state root policy must be Runtime-owned")
  assert(!state_root_record["kde_policy_owner"], "C Runtime core state root policy must not be KDE-owned")
  assert(!state_root_record["directories_created"], "C Runtime core state root policy must not create directories")
  assert(!state_root_record["host_root_modified"], "C Runtime core state root policy must not mutate the host root")
  assert(!state_root_record["user_documents_included"], "C Runtime core state root policy must exclude user documents")
  assert(state_root_record["portal_required_for_user_files"], "C Runtime core state root policy must require Portal access for user files")
  assert(state_root_record["snapshot_eligible"], "C Runtime core state root policy must be snapshot eligible")
  assert(state_root_record["restore_requires_confirmation"], "C Runtime core state root policy restore must require confirmation")
  assert(state_root_record["managed_scopes"] == %w[application-data runtime-metadata diagnostic-cache desktop-activation-receipts], "C Runtime core state root policy must keep managed scope order stable")
  assert(!state_root_record["backend_details_exposed"], "C Runtime core state root policy must hide backend details")
  assert(!stdout.match?(/wine|prefix|\.wine|proton|virtual machine/i), "C Runtime core state root policy catalog must not expose backend implementation terms")
  assert(!stdout.match?(%r{/Users|/home|/var|/opt|/tmp}), "C Runtime core state root policy catalog must not expose host storage paths")

  stdout, stderr, status = Open3.capture3(binary.to_s, "state-root-policy", "org.xnix.sample.notepad")
  assert(status.success?, "C Runtime core state root policy must exit successfully: #{stderr}")
  state_root_policy = JSON.parse(stdout)
  assert(state_root_policy["root_type"] == "compatibility-application-state-root", "C Runtime core state root policy must identify the root type")
  assert(state_root_policy["application"]["id"] == "org.xnix.sample.notepad", "C Runtime core state root policy must preserve the application id")
  assert(state_root_policy["application"]["requested_mode"] == "automatic", "C Runtime core state root policy must preserve the requested mode")
  assert(state_root_policy["retention_policy"]["automatic_restore_points"] == 5, "C Runtime core state root policy must expose automatic retention")
  assert(state_root_policy["retention_policy"]["manual_restore_points"] == 10, "C Runtime core state root policy must expose manual retention")
  assert(state_root_policy["retention_policy"]["user_documents_excluded"], "C Runtime core state root retention must exclude user documents")
  assert(state_root_policy["managed_scopes"].map { |scope| scope.fetch("id") } == %w[application-data runtime-metadata diagnostic-cache desktop-activation-receipts], "C Runtime core state root policy must expose managed scope objects")
  assert(!state_root_policy["managed_scopes"].find { |scope| scope.fetch("id") == "diagnostic-cache" }.fetch("snapshot_included"), "C Runtime core state root policy must exclude diagnostic cache from snapshots")
  assert(state_root_policy["blocked_actions"].include?("expose host storage paths to KDE"), "C Runtime core state root policy must block host path exposure")
  assert(!state_root_policy["backend_details_exposed"], "C Runtime core state root policy must hide backend details")

  _stdout, stderr, status = Open3.capture3(binary.to_s, "state-root-policy", "org.xnix.unknown")
  assert(!status.success?, "C Runtime core must reject state root policy for unknown applications")
  assert(stderr.include?("state root policy catalog"), "C Runtime core must explain unknown state root application validation")

  stdout, stderr, status = Open3.capture3(binary.to_s, "list-install-readiness-policies")
  assert(status.success?, "C Runtime core install readiness catalog must exit successfully: #{stderr}")
  install_catalog = JSON.parse(stdout)
  assert(install_catalog["version"] == "0.2.70", "C Runtime core install readiness catalog must expose the current version")
  assert(install_catalog["catalog_type"] == "install-readiness-policy", "C Runtime core install readiness catalog must identify the catalog type")
  assert(install_catalog["runtime_policy_owner"], "C Runtime core must own install readiness policy")
  assert(!install_catalog["desktop_shell_policy_owner"], "C Runtime core must not make the desktop shell the install readiness owner")
  assert(install_catalog["catalog_owner"] == "c", "C Runtime core install readiness catalog must be C-owned")
  assert(!install_catalog["backend_details_exposed"], "C Runtime core install readiness catalog must hide backend details")
  assert(!install_catalog["host_root_modified"], "C Runtime core install readiness catalog must not mutate the host root")
  assert(install_catalog["policy_count"] == 1, "C Runtime core install readiness catalog must count policies")
  install_record = install_catalog.fetch("policies").fetch(0)
  assert(install_record["application_id"] == "org.xnix.sample.notepad", "C Runtime core install readiness must preserve the application id")
  assert(install_record["install_state"] == "planned", "C Runtime core install readiness must stay planned")
  assert(!install_record["install_ready"], "C Runtime core install readiness must not claim install readiness")
  assert(!install_record["desktop_activation_ready"], "C Runtime core install readiness must not claim desktop activation readiness")
  assert(!install_record["download_enabled"], "C Runtime core install readiness must not enable downloads")
  assert(!install_record["install_enabled"], "C Runtime core install readiness must not enable installation")
  assert(!install_record["host_root_modified"], "C Runtime core install readiness must not mutate the host root")
  assert(install_record["selected_strategy"] == "automatic-managed", "C Runtime core install readiness must preserve the selected strategy")
  assert(!install_record["backend_details_exposed"], "C Runtime core install readiness must hide backend details")
  assert(!stdout.match?(/wine|prefix|\.wine|proton|virtual machine/i), "C Runtime core install readiness catalog must not expose backend implementation terms")
  assert(!stdout.match?(%r{/Users|/home|/var|/opt|/tmp}), "C Runtime core install readiness catalog must not expose host storage paths")

  stdout, stderr, status = Open3.capture3(binary.to_s, "install-readiness-policy", "org.xnix.sample.notepad", "development")
  assert(status.success?, "C Runtime core development install readiness must exit successfully: #{stderr}")
  install_policy = JSON.parse(stdout)
  install_phase_ids = install_policy.fetch("phases").map { |phase| phase.fetch("id") }
  assert(install_policy["plan_type"] == "compatibility-install-readiness", "C Runtime core install readiness must identify the plan type")
  assert(install_policy["application"]["id"] == "org.xnix.sample.notepad", "C Runtime core install readiness must preserve the application id")
  assert(install_policy["environment"] == "development", "C Runtime core install readiness must preserve the environment")
  assert(install_policy["runtime_owned"], "C Runtime core install readiness must be Runtime-owned")
  assert(!install_policy["kde_policy_owner"], "C Runtime core install readiness must not be KDE-owned")
  assert(!install_policy["readiness"]["artifact_manifest_ready"], "C Runtime core install readiness must wait for artifact manifests")
  assert(!install_policy["readiness"]["artifact_signature_verified"], "C Runtime core install readiness must wait for artifact signatures")
  assert(!install_policy["readiness"]["acquisition_ready"], "C Runtime core install readiness must wait for acquisition readiness")
  assert(!install_policy["readiness"]["package_source_ready"], "C Runtime core install readiness must wait for package sources")
  assert(!install_policy["readiness"]["state_root_allocated"], "C Runtime core install readiness must wait for state allocation")
  assert(install_policy["readiness"]["recipe_install_allowed"], "C Runtime core development install readiness must allow digest-verified staging")
  assert(install_policy["readiness"]["recipe_install_decision"] == "allow", "C Runtime core development install readiness must expose the allow decision")
  assert(install_phase_ids == %w[resolve-artifact-manifest verify-artifact-digests prepare-package-source allocate-application-state stage-desktop-integration enable-launch-binding], "C Runtime core install readiness must keep phase order stable")
  assert(install_policy["blocked_actions"].include?("mutate the host root during install planning"), "C Runtime core install readiness must block host root mutation")
  assert(!install_policy["download_enabled"], "C Runtime core install readiness must not enable downloads")
  assert(!install_policy["install_enabled"], "C Runtime core install readiness must not enable installation")
  assert(!install_policy["network_request_created"], "C Runtime core install readiness must not create network requests")
  assert(!install_policy["artifacts_downloaded"], "C Runtime core install readiness must not download artifacts")
  assert(!install_policy["privileged_container_required"], "C Runtime core install readiness must not require privileged containers")
  assert(!install_policy["desktop_shell_command_exposed"], "C Runtime core install readiness must not expose desktop shell commands")
  assert(!install_policy["backend_details_exposed"], "C Runtime core install readiness must hide backend details")

  stdout, stderr, status = Open3.capture3(binary.to_s, "install-readiness-policy", "org.xnix.sample.notepad", "production")
  assert(status.success?, "C Runtime core production install readiness must exit successfully: #{stderr}")
  production_install_policy = JSON.parse(stdout)
  assert(!production_install_policy["readiness"]["recipe_install_allowed"], "C Runtime core production install readiness must block development-only registries")
  assert(production_install_policy["readiness"]["recipe_install_decision"] == "block", "C Runtime core production install readiness must expose the blocked decision")

  _stdout, stderr, status = Open3.capture3(binary.to_s, "install-readiness-policy", "org.xnix.sample.notepad", "unknown")
  assert(!status.success?, "C Runtime core must reject unknown install readiness environments")
  assert(stderr.include?("environment must be development or production"), "C Runtime core must explain install readiness environment validation")

  _stdout, stderr, status = Open3.capture3(binary.to_s, "install-readiness-policy", "org.xnix.unknown", "development")
  assert(!status.success?, "C Runtime core must reject install readiness for unknown applications")
  assert(stderr.include?("install readiness policy catalog"), "C Runtime core must explain unknown install readiness application validation")

  stdout, stderr, status = Open3.capture3(binary.to_s, "list-artifact-manifest-policies")
  assert(status.success?, "C Runtime core artifact manifest catalog must exit successfully: #{stderr}")
  artifact_catalog = JSON.parse(stdout)
  assert(artifact_catalog["version"] == "0.2.70", "C Runtime core artifact manifest catalog must expose the current version")
  assert(artifact_catalog["catalog_type"] == "artifact-manifest-policy", "C Runtime core artifact manifest catalog must identify the catalog type")
  assert(artifact_catalog["runtime_policy_owner"], "C Runtime core must own artifact manifest policy")
  assert(!artifact_catalog["desktop_shell_policy_owner"], "C Runtime core must not make the desktop shell the artifact manifest owner")
  assert(artifact_catalog["catalog_owner"] == "c", "C Runtime core artifact manifest catalog must be C-owned")
  assert(!artifact_catalog["backend_details_exposed"], "C Runtime core artifact manifest catalog must hide backend details")
  assert(!artifact_catalog["host_root_modified"], "C Runtime core artifact manifest catalog must not mutate the host root")
  assert(artifact_catalog["policy_count"] == 1, "C Runtime core artifact manifest catalog must count policies")
  artifact_record = artifact_catalog.fetch("policies").fetch(0)
  assert(artifact_record["application_id"] == "org.xnix.sample.notepad", "C Runtime core artifact manifest must preserve the application id")
  assert(artifact_record["manifest_state"] == "planned", "C Runtime core artifact manifest must stay planned")
  assert(!artifact_record["manifest_ready"], "C Runtime core artifact manifest must not claim readiness")
  assert(!artifact_record["signature_verified"], "C Runtime core artifact manifest must not claim signature verification")
  assert(!artifact_record["download_enabled"], "C Runtime core artifact manifest must not enable downloads")
  assert(!artifact_record["artifacts_downloaded"], "C Runtime core artifact manifest must not download artifacts")
  assert(!artifact_record["host_root_modified"], "C Runtime core artifact manifest must not mutate the host root")
  assert(artifact_record["selected_strategy"] == "automatic-managed", "C Runtime core artifact manifest must preserve the selected strategy")
  assert(!artifact_record["backend_details_exposed"], "C Runtime core artifact manifest must hide backend details")
  assert(!stdout.match?(/wine|prefix|\.wine|proton|virtual machine/i), "C Runtime core artifact manifest catalog must not expose backend implementation terms")
  assert(!stdout.match?(%r{/Users|/home|/var|/opt|/tmp}), "C Runtime core artifact manifest catalog must not expose host storage paths")

  stdout, stderr, status = Open3.capture3(binary.to_s, "artifact-manifest-policy", "org.xnix.sample.notepad")
  assert(status.success?, "C Runtime core artifact manifest must exit successfully: #{stderr}")
  artifact_manifest = JSON.parse(stdout)
  artifact_group_ids = artifact_manifest.fetch("artifact_groups").map { |group| group.fetch("id") }
  artifact_preflight_ids = artifact_manifest.fetch("required_preflight").map { |preflight| preflight.fetch("id") }
  assert(artifact_manifest["manifest_type"] == "compatibility-artifact-manifest", "C Runtime core artifact manifest must identify the manifest type")
  assert(artifact_manifest["application"]["id"] == "org.xnix.sample.notepad", "C Runtime core artifact manifest must preserve the application id")
  assert(artifact_manifest["runtime_owned"], "C Runtime core artifact manifest must be Runtime-owned")
  assert(!artifact_manifest["kde_policy_owner"], "C Runtime core artifact manifest must not be KDE-owned")
  assert(artifact_manifest["selected_strategy"] == "automatic-managed", "C Runtime core artifact manifest must align with the selected strategy")
  assert(artifact_manifest["manifest_state"] == "planned", "C Runtime core artifact manifest must not claim resolution")
  assert(!artifact_manifest["manifest_ready"], "C Runtime core artifact manifest must not claim readiness")
  assert(!artifact_manifest["signature_verified"], "C Runtime core artifact manifest must not claim signature verification")
  assert(!artifact_manifest["acquisition_preflight_ready"], "C Runtime core artifact manifest must inherit pending acquisition preflight")
  assert(!artifact_manifest["download_enabled"], "C Runtime core artifact manifest must not enable downloads")
  assert(!artifact_manifest["install_enabled"], "C Runtime core artifact manifest must not enable installation")
  assert(!artifact_manifest["network_request_created"], "C Runtime core artifact manifest must not create network requests")
  assert(!artifact_manifest["artifacts_downloaded"], "C Runtime core artifact manifest must not download artifacts")
  assert(!artifact_manifest["host_root_modified"], "C Runtime core artifact manifest must not mutate the host root")
  assert(!artifact_manifest["privileged_container_required"], "C Runtime core artifact manifest must not require privileged containers")
  assert(!artifact_manifest["desktop_shell_command_exposed"], "C Runtime core artifact manifest must not expose desktop shell commands")
  assert(artifact_group_ids == %w[runtime-launch-metadata local-execution-artifacts isolated-environment-artifacts], "C Runtime core artifact manifest must expose expected artifact groups")
  assert(artifact_preflight_ids == %w[acquisition-preflight-ready manifest-signature-verification artifact-digest-verification cache-namespace-allocation rollback-reference], "C Runtime core artifact manifest must expose expected preflight")
  assert(artifact_manifest["artifact_groups"].none? { |group| group.fetch("resolved") }, "C Runtime core artifact manifest must not claim artifact resolution")
  assert(artifact_manifest["artifact_groups"].none? { |group| group.fetch("downloaded") }, "C Runtime core artifact manifest must not claim artifact downloads")
  assert(artifact_manifest["blocked_actions"].include?("expose artifact cache paths to KDE"), "C Runtime core artifact manifest must block cache path exposure")
  assert(!artifact_manifest["backend_details_exposed"], "C Runtime core artifact manifest must hide backend details")

  _stdout, stderr, status = Open3.capture3(binary.to_s, "artifact-manifest-policy", "org.xnix.unknown")
  assert(!status.success?, "C Runtime core must reject artifact manifests for unknown applications")
  assert(stderr.include?("artifact manifest policy catalog"), "C Runtime core must explain unknown artifact manifest application validation")

  stdout, stderr, status = Open3.capture3(binary.to_s, "list-acquisition-preflight-policies")
  assert(status.success?, "C Runtime core acquisition preflight catalog must exit successfully: #{stderr}")
  acquisition_catalog = JSON.parse(stdout)
  assert(acquisition_catalog["version"] == "0.2.70", "C Runtime core acquisition preflight catalog must expose the current version")
  assert(acquisition_catalog["catalog_type"] == "acquisition-preflight-policy", "C Runtime core acquisition preflight catalog must identify the catalog type")
  assert(acquisition_catalog["runtime_policy_owner"], "C Runtime core must own acquisition preflight policy")
  assert(!acquisition_catalog["desktop_shell_policy_owner"], "C Runtime core must not make the desktop shell the acquisition preflight owner")
  assert(acquisition_catalog["catalog_owner"] == "c", "C Runtime core acquisition preflight catalog must be C-owned")
  assert(!acquisition_catalog["backend_details_exposed"], "C Runtime core acquisition preflight catalog must hide backend details")
  assert(!acquisition_catalog["host_root_modified"], "C Runtime core acquisition preflight catalog must not mutate the host root")
  assert(acquisition_catalog["policy_count"] == 1, "C Runtime core acquisition preflight catalog must count policies")
  acquisition_record = acquisition_catalog.fetch("policies").fetch(0)
  assert(acquisition_record["application_id"] == "org.xnix.sample.notepad", "C Runtime core acquisition preflight must preserve the application id")
  assert(acquisition_record["preflight_state"] == "planned", "C Runtime core acquisition preflight must stay planned")
  assert(!acquisition_record["acquisition_ready"], "C Runtime core acquisition preflight must not claim readiness")
  assert(!acquisition_record["download_enabled"], "C Runtime core acquisition preflight must not enable downloads")
  assert(!acquisition_record["network_request_created"], "C Runtime core acquisition preflight must not create network requests")
  assert(!acquisition_record["artifacts_downloaded"], "C Runtime core acquisition preflight must not download artifacts")
  assert(!acquisition_record["host_root_modified"], "C Runtime core acquisition preflight must not mutate the host root")
  assert(acquisition_record["selected_strategy"] == "automatic-managed", "C Runtime core acquisition preflight must preserve the selected strategy")
  assert(!acquisition_record["backend_details_exposed"], "C Runtime core acquisition preflight must hide backend details")
  assert(!stdout.match?(/wine|prefix|\.wine|proton|virtual machine/i), "C Runtime core acquisition preflight catalog must not expose backend implementation terms")
  assert(!stdout.match?(%r{/Users|/home|/var|/opt|/tmp}), "C Runtime core acquisition preflight catalog must not expose host storage paths")

  stdout, stderr, status = Open3.capture3(binary.to_s, "acquisition-preflight-policy", "org.xnix.sample.notepad")
  assert(status.success?, "C Runtime core acquisition preflight must exit successfully: #{stderr}")
  acquisition_preflight = JSON.parse(stdout)
  acquisition_check_ids = acquisition_preflight.fetch("checks").map { |check| check.fetch("id") }
  assert(acquisition_preflight["preflight_type"] == "compatibility-acquisition-preflight", "C Runtime core acquisition preflight must identify the preflight type")
  assert(acquisition_preflight["application"]["id"] == "org.xnix.sample.notepad", "C Runtime core acquisition preflight must preserve the application id")
  assert(acquisition_preflight["runtime_owned"], "C Runtime core acquisition preflight must be Runtime-owned")
  assert(!acquisition_preflight["kde_policy_owner"], "C Runtime core acquisition preflight must not be KDE-owned")
  assert(acquisition_preflight["selected_strategy"] == "automatic-managed", "C Runtime core acquisition preflight must align with selected strategy")
  assert(acquisition_preflight["preflight_state"] == "planned", "C Runtime core acquisition preflight must not claim execution")
  assert(!acquisition_preflight["acquisition_ready"], "C Runtime core acquisition preflight must not claim readiness")
  assert(!acquisition_preflight["download_enabled"], "C Runtime core acquisition preflight must not enable downloads")
  assert(!acquisition_preflight["install_enabled"], "C Runtime core acquisition preflight must not enable installation")
  assert(!acquisition_preflight["network_required_for_planning"], "C Runtime core acquisition preflight planning must not require network access")
  assert(!acquisition_preflight["network_request_created"], "C Runtime core acquisition preflight must not create network requests")
  assert(!acquisition_preflight["artifacts_downloaded"], "C Runtime core acquisition preflight must not download artifacts")
  assert(!acquisition_preflight["host_root_modified"], "C Runtime core acquisition preflight must not mutate the host root")
  assert(!acquisition_preflight["privileged_container_required"], "C Runtime core acquisition preflight must not require privileged containers")
  assert(!acquisition_preflight["desktop_shell_command_exposed"], "C Runtime core acquisition preflight must not expose desktop shell commands")
  assert(!acquisition_preflight["package_source_ready"], "C Runtime core acquisition preflight must inherit pending package source readiness")
  assert(acquisition_check_ids == %w[package-source-ready signed-artifact-manifest runtime-cache-space network-policy-review rollback-marker], "C Runtime core acquisition preflight must expose expected checks")
  assert(acquisition_preflight["blocked_actions"].include?("invoke network access from KDE"), "C Runtime core acquisition preflight must block KDE network access")
  assert(!acquisition_preflight["backend_details_exposed"], "C Runtime core acquisition preflight must hide backend details")

  _stdout, stderr, status = Open3.capture3(binary.to_s, "acquisition-preflight-policy", "org.xnix.unknown")
  assert(!status.success?, "C Runtime core must reject acquisition preflight for unknown applications")
  assert(stderr.include?("acquisition preflight policy catalog"), "C Runtime core must explain unknown acquisition preflight application validation")

  stdout, stderr, status = Open3.capture3(binary.to_s, "list-package-source-policies")
  assert(status.success?, "C Runtime core package source catalog must exit successfully: #{stderr}")
  package_source_catalog = JSON.parse(stdout)
  assert(package_source_catalog["version"] == "0.2.70", "C Runtime core package source catalog must expose the current version")
  assert(package_source_catalog["catalog_type"] == "package-source-policy", "C Runtime core package source catalog must identify the catalog type")
  assert(package_source_catalog["runtime_policy_owner"], "C Runtime core must own package source policy")
  assert(!package_source_catalog["desktop_shell_policy_owner"], "C Runtime core must not make the desktop shell the package source owner")
  assert(package_source_catalog["catalog_owner"] == "c", "C Runtime core package source catalog must be C-owned")
  assert(!package_source_catalog["backend_details_exposed"], "C Runtime core package source catalog must hide backend details")
  assert(!package_source_catalog["host_root_modified"], "C Runtime core package source catalog must not mutate the host root")
  assert(package_source_catalog["policy_count"] == 1, "C Runtime core package source catalog must count policies")
  package_source_record = package_source_catalog.fetch("policies").fetch(0)
  assert(package_source_record["application_id"] == "org.xnix.sample.notepad", "C Runtime core package source must preserve the application id")
  assert(package_source_record["source_selection_state"] == "planned", "C Runtime core package source must stay planned")
  assert(!package_source_record["package_source_ready"], "C Runtime core package source must not claim readiness")
  assert(!package_source_record["install_enabled"], "C Runtime core package source must not enable installation")
  assert(!package_source_record["network_required_for_planning"], "C Runtime core package source planning must not require network access")
  assert(!package_source_record["host_root_modified"], "C Runtime core package source must not mutate the host root")
  assert(package_source_record["selected_strategy"] == "automatic-managed", "C Runtime core package source must preserve the selected strategy")
  assert(!package_source_record["backend_details_exposed"], "C Runtime core package source must hide backend details")
  assert(!stdout.match?(/wine|prefix|\.wine|proton|virtual machine/i), "C Runtime core package source catalog must not expose backend implementation terms")
  assert(!stdout.match?(%r{/Users|/home|/var|/opt|/tmp}), "C Runtime core package source catalog must not expose host storage paths")

  stdout, stderr, status = Open3.capture3(binary.to_s, "package-source-policy", "org.xnix.sample.notepad")
  assert(status.success?, "C Runtime core package source must exit successfully: #{stderr}")
  package_source = JSON.parse(stdout)
  source_channel_ids = package_source.fetch("source_channels").map { |channel| channel.fetch("id") }
  package_preflight_ids = package_source.fetch("required_preflight").map { |preflight| preflight.fetch("id") }
  assert(package_source["source_type"] == "compatibility-package-source", "C Runtime core package source must identify the source type")
  assert(package_source["application"]["id"] == "org.xnix.sample.notepad", "C Runtime core package source must preserve the application id")
  assert(package_source["runtime_owned"], "C Runtime core package source must be Runtime-owned")
  assert(!package_source["kde_policy_owner"], "C Runtime core package source must not be KDE-owned")
  assert(package_source["selected_strategy"] == "automatic-managed", "C Runtime core package source must align with selected strategy")
  assert(package_source["source_selection_state"] == "planned", "C Runtime core package source must not claim source selection")
  assert(!package_source["package_source_ready"], "C Runtime core package source must not claim readiness")
  assert(!package_source["install_enabled"], "C Runtime core package source must not enable installation")
  assert(!package_source["network_required_for_planning"], "C Runtime core package source planning must not require network access")
  assert(!package_source["host_root_modified"], "C Runtime core package source must not mutate the host root")
  assert(!package_source["privileged_container_required"], "C Runtime core package source must not require privileged containers")
  assert(!package_source["desktop_shell_command_exposed"], "C Runtime core package source must not expose desktop shell commands")
  assert(package_source["source_policy"]["signed_source_required"], "C Runtime core package source must require signed sources")
  assert(package_source["source_policy"]["runtime_cache_required"], "C Runtime core package source must require Runtime cache planning")
  assert(!package_source["source_policy"]["direct_desktop_install_allowed"], "C Runtime core package source must block direct desktop installation")
  assert(!package_source["source_policy"]["host_package_manager_invoked"], "C Runtime core package source must not invoke a host package manager")
  assert(source_channel_ids == %w[os-managed-compatibility-packages runtime-managed-toolcache isolated-environment-template-catalog], "C Runtime core package source must expose expected source channels")
  assert(package_preflight_ids == %w[signed-source-verification source-policy-review runtime-cache-quota offline-fallback], "C Runtime core package source must expose expected preflight")
  assert(package_source["source_channels"].all? { |channel| channel.fetch("runtime_owned") }, "C Runtime core package source channels must be Runtime-owned")
  assert(package_source["source_channels"].none? { |channel| channel.fetch("selection_state") != "planned" }, "C Runtime core package source channels must remain planned")
  assert(package_source["blocked_actions"].include?("expose package manager commands to KDE"), "C Runtime core package source must block package command exposure")
  assert(!package_source["backend_details_exposed"], "C Runtime core package source must hide backend details")

  _stdout, stderr, status = Open3.capture3(binary.to_s, "package-source-policy", "org.xnix.unknown")
  assert(!status.success?, "C Runtime core must reject package source for unknown applications")
  assert(stderr.include?("package source policy catalog"), "C Runtime core must explain unknown package source application validation")

  stdout, stderr, status = Open3.capture3(binary.to_s, "list-backend-binding-policies")
  assert(status.success?, "C Runtime core backend binding catalog must exit successfully: #{stderr}")
  backend_binding_catalog = JSON.parse(stdout)
  assert(backend_binding_catalog["version"] == "0.2.70", "C Runtime core backend binding catalog must expose the current version")
  assert(backend_binding_catalog["catalog_type"] == "backend-binding-policy", "C Runtime core backend binding catalog must identify the catalog type")
  assert(backend_binding_catalog["runtime_policy_owner"], "C Runtime core must own backend binding policy")
  assert(!backend_binding_catalog["desktop_shell_policy_owner"], "C Runtime core must not make the desktop shell the backend binding owner")
  assert(backend_binding_catalog["catalog_owner"] == "c", "C Runtime core backend binding catalog must be C-owned")
  assert(!backend_binding_catalog["backend_details_exposed"], "C Runtime core backend binding catalog must hide backend details")
  assert(!backend_binding_catalog["host_root_modified"], "C Runtime core backend binding catalog must not mutate the host root")
  assert(backend_binding_catalog["policy_count"] == 1, "C Runtime core backend binding catalog must count policies")
  backend_binding_record = backend_binding_catalog.fetch("policies").fetch(0)
  assert(backend_binding_record["application_id"] == "org.xnix.sample.notepad", "C Runtime core backend binding must preserve the application id")
  assert(backend_binding_record["selected_strategy"] == "automatic-managed", "C Runtime core backend binding must preserve the selected strategy")
  assert(!backend_binding_record["managed_binding_ready"], "C Runtime core backend binding must not claim readiness")
  assert(!backend_binding_record["launch_enabled"], "C Runtime core backend binding must not enable launch")
  assert(!backend_binding_record["execution_request_created"], "C Runtime core backend binding must not create execution requests")
  assert(!backend_binding_record["host_root_modified"], "C Runtime core backend binding must not mutate the host root")
  assert(!backend_binding_record["network_required"], "C Runtime core backend binding must not require network access")
  assert(!backend_binding_record["backend_details_exposed"], "C Runtime core backend binding must hide backend details")
  assert(!stdout.match?(/wine|prefix|\.wine|proton|virtual machine/i), "C Runtime core backend binding catalog must not expose backend implementation terms")
  assert(!stdout.match?(%r{/Users|/home|/var|/opt|/tmp}), "C Runtime core backend binding catalog must not expose host storage paths")

  stdout, stderr, status = Open3.capture3(binary.to_s, "backend-binding-policy", "org.xnix.sample.notepad")
  assert(status.success?, "C Runtime core backend binding must exit successfully: #{stderr}")
  backend_binding = JSON.parse(stdout)
  backend_preflight_ids = backend_binding.fetch("required_preflight").map { |preflight| preflight.fetch("id") }
  assert(backend_binding["binding_type"] == "compatibility-backend-binding", "C Runtime core backend binding must identify the binding type")
  assert(backend_binding["application"]["id"] == "org.xnix.sample.notepad", "C Runtime core backend binding must preserve the application id")
  assert(backend_binding["application"]["supported_extensions"] == [".txt"], "C Runtime core backend binding must expose safe extension metadata")
  assert(backend_binding["runtime_owned"], "C Runtime core backend binding must be Runtime-owned")
  assert(!backend_binding["kde_policy_owner"], "C Runtime core backend binding must not be KDE-owned")
  assert(backend_binding["selected_strategy"] == "automatic-managed", "C Runtime core backend binding must align with selected strategy")
  assert(!backend_binding["managed_binding_ready"], "C Runtime core backend binding must not claim readiness")
  assert(!backend_binding["launch_enabled"], "C Runtime core backend binding must not enable launch")
  assert(!backend_binding["execution_request_created"], "C Runtime core backend binding must not create execution requests")
  assert(!backend_binding["host_root_modified"], "C Runtime core backend binding must not mutate the host root")
  assert(!backend_binding["network_required"], "C Runtime core backend binding must not require network access")
  assert(!backend_binding["privileged_container_required"], "C Runtime core backend binding must not require privileged containers")
  assert(backend_preflight_ids == %w[engine-package-source application-state-root portal-policy-review snapshot-baseline], "C Runtime core backend binding must expose expected preflight")
  assert(backend_binding["blocked_actions"].include?("expose backend command to desktop shell"), "C Runtime core backend binding must block backend command exposure")
  assert(!backend_binding["backend_details_exposed"], "C Runtime core backend binding must hide backend details")

  _stdout, stderr, status = Open3.capture3(binary.to_s, "backend-binding-policy", "org.xnix.unknown")
  assert(!status.success?, "C Runtime core must reject backend binding for unknown applications")
  assert(stderr.include?("backend binding policy catalog"), "C Runtime core must explain unknown backend binding application validation")

  stdout, stderr, status = Open3.capture3(binary.to_s, "list-settings-policies")
  assert(status.success?, "C Runtime core settings catalog must exit successfully: #{stderr}")
  settings_catalog = JSON.parse(stdout)
  assert(settings_catalog["version"] == "0.2.70", "C Runtime core settings catalog must expose the current version")
  assert(settings_catalog["catalog_type"] == "settings-policy", "C Runtime core settings catalog must identify the catalog type")
  assert(settings_catalog["runtime_policy_owner"], "C Runtime core must own settings policy")
  assert(!settings_catalog["desktop_shell_policy_owner"], "C Runtime core must not make the desktop shell the settings owner")
  assert(settings_catalog["catalog_owner"] == "c", "C Runtime core settings catalog must be C-owned")
  assert(!settings_catalog["backend_details_exposed"], "C Runtime core settings catalog must hide backend details")
  assert(!settings_catalog["host_root_modified"], "C Runtime core settings catalog must not mutate the host root")
  assert(settings_catalog["policy_count"] == 1, "C Runtime core settings catalog must count policies")
  settings_record = settings_catalog.fetch("policies").fetch(0)
  assert(settings_record["application_id"] == "org.xnix.sample.notepad", "C Runtime core settings must preserve the application id")
  assert(settings_record["settings_state"] == "planned", "C Runtime core settings must stay planned")
  assert(!settings_record["settings_persisted"], "C Runtime core settings must not claim persistence")
  assert(!settings_record["host_root_modified"], "C Runtime core settings must not mutate the host root")
  assert(settings_record["section_count"] == 5, "C Runtime core settings must count sections")
  assert(!settings_record["backend_details_exposed"], "C Runtime core settings must hide backend details")
  assert(!stdout.match?(/wine|prefix|\.wine|proton|virtual machine/i), "C Runtime core settings catalog must not expose backend implementation terms")
  assert(!stdout.match?(%r{/Users|/home|/var|/opt|/tmp}), "C Runtime core settings catalog must not expose host storage paths")

  stdout, stderr, status = Open3.capture3(binary.to_s, "settings-policy", "org.xnix.sample.notepad")
  assert(status.success?, "C Runtime core settings policy must exit successfully: #{stderr}")
  settings_policy = JSON.parse(stdout)
  settings_section_ids = settings_policy.fetch("sections").map { |section| section.fetch("id") }
  settings_fields = settings_policy.fetch("sections").flat_map { |section| section.fetch("fields") }
  settings_values = settings_fields.each_with_object({}) { |field, memo| memo[field.fetch("id")] = field.fetch("value") }
  assert(settings_policy["request_type"] == "settings-model", "C Runtime core settings must identify the request type")
  assert(settings_policy["desktop"] == "KDE Plasma", "C Runtime core settings must target KDE Plasma")
  assert(settings_policy["application_id"] == "org.xnix.sample.notepad", "C Runtime core settings must preserve the application id")
  assert(settings_policy["application"]["id"] == "org.xnix.sample.notepad", "C Runtime core settings must include safe application metadata")
  assert(settings_policy["runtime_owned"], "C Runtime core settings must be Runtime-owned")
  assert(!settings_policy["kde_policy_owner"], "C Runtime core settings must not be KDE-owned")
  assert(settings_policy["settings_state"] == "planned", "C Runtime core settings must stay planned")
  assert(!settings_policy["settings_persisted"], "C Runtime core settings must not claim persistence")
  assert(!settings_policy["host_root_modified"], "C Runtime core settings must not mutate the host root")
  assert(!settings_policy["backend_details_exposed"], "C Runtime core settings must hide backend details")
  assert(settings_policy["section_count"] == 5, "C Runtime core settings must expose section count")
  assert(settings_section_ids == %w[run-mode resource-access devices network snapshots], "C Runtime core settings must expose expected sections")
  assert(settings_values["mode"] == "automatic", "C Runtime core settings must default to automatic mode")
  assert(settings_values["preference"] == "compatibility", "C Runtime core settings must default to compatibility priority")
  assert(settings_values["documents"] == "ask", "C Runtime core settings must default documents to ask")
  assert(settings_values["downloads"] == "ask", "C Runtime core settings must default downloads to ask")
  assert(settings_values["camera"] == "deny", "C Runtime core settings must default camera to deny")
  assert(settings_values["network"] == "allow", "C Runtime core settings must default network to allow")
  assert(settings_values["snapshots"] == "enabled", "C Runtime core settings must default snapshots to enabled")
  assert(settings_fields.find { |field| field.fetch("id") == "mode" }.fetch("options") == %w[automatic performance compatibility], "C Runtime core settings must expose run mode options")

  _stdout, stderr, status = Open3.capture3(binary.to_s, "settings-policy", "org.xnix.unknown")
  assert(!status.success?, "C Runtime core must reject settings for unknown applications")
  assert(stderr.include?("settings policy catalog"), "C Runtime core must explain unknown settings application validation")

  stdout, stderr, status = Open3.capture3(binary.to_s, "list-settings-change-policies")
  assert(status.success?, "C Runtime core settings change catalog must exit successfully: #{stderr}")
  settings_change_catalog = JSON.parse(stdout)
  assert(settings_change_catalog["version"] == "0.2.70", "C Runtime core settings change catalog must expose the current version")
  assert(settings_change_catalog["catalog_type"] == "settings-change-policy", "C Runtime core settings change catalog must identify the catalog type")
  assert(settings_change_catalog["runtime_policy_owner"], "C Runtime core must own settings change policy")
  assert(!settings_change_catalog["desktop_shell_policy_owner"], "C Runtime core must not make the desktop shell the settings change owner")
  assert(settings_change_catalog["catalog_owner"] == "c", "C Runtime core settings change catalog must be C-owned")
  assert(!settings_change_catalog["backend_details_exposed"], "C Runtime core settings change catalog must hide backend details")
  assert(!settings_change_catalog["host_root_modified"], "C Runtime core settings change catalog must not mutate the host root")
  assert(settings_change_catalog["policy_count"] == 1, "C Runtime core settings change catalog must count policies")
  settings_change_record = settings_change_catalog.fetch("policies").fetch(0)
  assert(settings_change_record["application_id"] == "org.xnix.sample.notepad", "C Runtime core settings change must preserve the application id")
  assert(settings_change_record["section_id"] == "resource-access", "C Runtime core settings change must preserve the section id")
  assert(settings_change_record["field_id"] == "documents", "C Runtime core settings change must preserve the field id")
  assert(settings_change_record["requested_value"] == "allow", "C Runtime core settings change must preserve the requested value")
  assert(settings_change_record["change_state"] == "planned", "C Runtime core settings change must stay planned")
  assert(!settings_change_record["apply_enabled"], "C Runtime core settings change must not enable apply")
  assert(!settings_change_record["settings_persisted"], "C Runtime core settings change must not claim persistence")
  assert(!settings_change_record["host_root_modified"], "C Runtime core settings change must not mutate the host root")
  assert(settings_change_record["portal_policy_review_required"], "C Runtime core settings change must require Portal review")
  assert(!settings_change_record["backend_details_exposed"], "C Runtime core settings change must hide backend details")
  assert(!stdout.match?(/wine|prefix|\.wine|proton|virtual machine/i), "C Runtime core settings change catalog must not expose backend implementation terms")
  assert(!stdout.match?(%r{/Users|/home|/var|/opt|/tmp}), "C Runtime core settings change catalog must not expose host storage paths")

  stdout, stderr, status = Open3.capture3(binary.to_s, "settings-change-policy", "org.xnix.sample.notepad")
  assert(status.success?, "C Runtime core settings change policy must exit successfully: #{stderr}")
  settings_change_policy = JSON.parse(stdout)
  settings_change_step_ids = settings_change_policy.fetch("steps").map { |step| step.fetch("id") }
  assert(settings_change_policy["plan_type"] == "settings-change-plan", "C Runtime core settings change must identify the plan type")
  assert(settings_change_policy["desktop"] == "KDE Plasma", "C Runtime core settings change must target KDE Plasma")
  assert(settings_change_policy["application_id"] == "org.xnix.sample.notepad", "C Runtime core settings change must preserve the application id")
  assert(settings_change_policy["application"]["id"] == "org.xnix.sample.notepad", "C Runtime core settings change must include safe application metadata")
  assert(settings_change_policy["runtime_owned"], "C Runtime core settings change must be Runtime-owned")
  assert(!settings_change_policy["kde_policy_owner"], "C Runtime core settings change must not be KDE-owned")
  assert(settings_change_policy["section_id"] == "resource-access", "C Runtime core settings change must preserve the section id")
  assert(settings_change_policy["field_id"] == "documents", "C Runtime core settings change must preserve the field id")
  assert(settings_change_policy["requested_value"] == "allow", "C Runtime core settings change must preserve the requested value")
  assert(settings_change_policy["change_state"] == "planned", "C Runtime core settings change must stay planned")
  assert(!settings_change_policy["apply_enabled"], "C Runtime core settings change must not enable apply")
  assert(!settings_change_policy["settings_persisted"], "C Runtime core settings change must not claim persistence")
  assert(!settings_change_policy["host_root_modified"], "C Runtime core settings change must not mutate the host root")
  assert(!settings_change_policy["backend_details_exposed"], "C Runtime core settings change must hide backend details")
  assert(settings_change_policy["user_confirmation_required"], "C Runtime core settings change must require user confirmation")
  assert(!settings_change_policy["snapshot_recommended"], "C Runtime core resource access settings change must not recommend snapshots")
  assert(settings_change_policy["portal_policy_review_required"], "C Runtime core resource access settings change must require Portal review")
  assert(!settings_change_policy["runtime_restart_required"], "C Runtime core settings change must not require a Runtime restart")
  assert(settings_change_policy["affected_policy"]["options"] == %w[allow ask deny], "C Runtime core settings change must expose safe options")
  assert(settings_change_step_ids == %w[validate-setting review-user-confirmation review-portal-policy prepare-restore-point persist-runtime-setting], "C Runtime core settings change must expose expected steps")
  assert(settings_change_policy["blocked_actions"].include?("grant desktop resources without Portal policy review"), "C Runtime core settings change must block direct resource grants")
  assert(!stdout.match?(/wine|prefix|\.wine|proton|virtual machine/i), "C Runtime core settings change policy must not expose backend implementation terms")
  assert(!stdout.match?(%r{/Users|/home|/var|/opt|/tmp}), "C Runtime core settings change policy must not expose host storage paths")

  _stdout, stderr, status = Open3.capture3(binary.to_s, "settings-change-policy", "org.xnix.unknown")
  assert(!status.success?, "C Runtime core must reject settings changes for unknown applications")
  assert(stderr.include?("settings change policy catalog"), "C Runtime core must explain unknown settings change application validation")

  stdout, stderr, status = Open3.capture3(binary.to_s, "runtime-service-binding")
  assert(status.success?, "C Runtime core service binding must exit successfully: #{stderr}")
  service_binding = JSON.parse(stdout)
  service_check_ids = service_binding.fetch("checks").map { |check| check.fetch("id") }
  assert(service_binding["version"] == "0.2.70", "C Runtime core service binding must expose the current version")
  assert(service_binding["binding_type"] == "runtime-service-binding", "C Runtime core service binding must identify the binding type")
  assert(service_binding["runtime_owned"], "C Runtime core service binding must be Runtime-owned")
  assert(!service_binding["kde_policy_owner"], "C Runtime core service binding must not be KDE-owned")
  assert(service_binding["bus_name"] == "org.xnix.Compatibility1", "C Runtime core service binding must expose the stable bus name")
  assert(service_binding["object_path"] == "/org/xnix/Compatibility1", "C Runtime core service binding must expose the stable object path")
  assert(service_binding["interface"] == "org.xnix.Compatibility1", "C Runtime core service binding must expose the stable interface")
  assert(service_binding["activation"]["dbus_service_file"] == "runtime/dbus/org.xnix.Compatibility1.service", "C Runtime core service binding must expose the D-Bus service file")
  assert(service_binding["activation"]["systemd_unit"] == "runtime/systemd/xnix-compatd.service", "C Runtime core service binding must expose the systemd unit")
  assert(service_binding["activation"]["libexec_wrapper"] == "libexec/xnix/compatd", "C Runtime core service binding must expose the libexec wrapper")
  assert(service_binding["activation"]["dbus_contract"] == "runtime/dbus/org.xnix.Compatibility1.xml", "C Runtime core service binding must expose the D-Bus contract")
  assert(service_binding["activation"]["packaged_wrapper"] == "/usr/libexec/xnix/compatd", "C Runtime core service binding must expose the packaged wrapper")
  assert(service_check_ids == %w[dbus-service-activation systemd-service-hardening libexec-wrapper dbus-contract live-dbus-owner], "C Runtime core service binding must expose expected checks")
  assert(service_binding["counts"] == { "total" => 5, "passed" => 4, "pending" => 1, "blocked" => 0 }, "C Runtime core service binding must count activation checks")
  assert(service_binding["activation_binding_ready"], "C Runtime core service binding must report activation files ready")
  assert(!service_binding["live_dbus_owner_ready"], "C Runtime core service binding must not claim live ownership")
  assert(service_binding["smoke_adapter_available"], "C Runtime core service binding must report smoke adapter availability")
  assert(!service_binding["network_required"], "C Runtime core service binding must not require network access")
  assert(!service_binding["host_root_modified"], "C Runtime core service binding must not mutate the host root")
  assert(!service_binding["privileged_container_required"], "C Runtime core service binding must not require privileged containers")
  assert(!service_binding["backend_details_exposed"], "C Runtime core service binding must hide backend details")
  assert(!stdout.match?(/wine|prefix|\.wine|proton|virtual machine/i), "C Runtime core service binding must not expose backend implementation terms")

  stdout, stderr, status = Open3.capture3(binary.to_s, "runtime-live-owner-gate")
  assert(status.success?, "C Runtime core live owner gate must exit successfully: #{stderr}")
  live_owner_gate = JSON.parse(stdout)
  live_owner_gate_ids = live_owner_gate.fetch("required_gates").map { |gate| gate.fetch("id") }
  live_owner_gate_statuses = live_owner_gate.fetch("required_gates").map { |gate| gate.fetch("status") }
  assert(live_owner_gate["version"] == "0.2.70", "C Runtime core live owner gate must expose the current version")
  assert(live_owner_gate["gate_type"] == "runtime-live-owner-gate", "C Runtime core live owner gate must identify the gate type")
  assert(live_owner_gate["runtime_owned"], "C Runtime core live owner gate must be Runtime-owned")
  assert(!live_owner_gate["kde_policy_owner"], "C Runtime core live owner gate must not be KDE-owned")
  assert(live_owner_gate["bus_name"] == "org.xnix.Compatibility1", "C Runtime core live owner gate must expose the stable bus name")
  assert(live_owner_gate["object_path"] == "/org/xnix/Compatibility1", "C Runtime core live owner gate must expose the stable object path")
  assert(live_owner_gate["interface"] == "org.xnix.Compatibility1", "C Runtime core live owner gate must expose the stable interface")
  assert(live_owner_gate["activation_binding_ready"], "C Runtime core live owner gate must require aligned activation files")
  assert(!live_owner_gate["live_dbus_owner_ready"], "C Runtime core live owner gate must not claim live ownership")
  assert(!live_owner_gate["production_owner_enabled"], "C Runtime core live owner gate must not enable production ownership")
  assert(!live_owner_gate["owner_transition_ready"], "C Runtime core live owner gate must not allow transition while gates are pending")
  assert(live_owner_gate["smoke_adapter_available"], "C Runtime core live owner gate must report smoke adapter availability")
  assert(!live_owner_gate["smoke_adapter_is_production_owner"], "C Runtime core smoke adapter must not be production owner")
  assert(!live_owner_gate["kde_may_claim_runtime_ownership"], "C Runtime core must not let KDE claim Runtime ownership")
  assert(live_owner_gate_ids == %w[activation-binding long-running-runtime-owner bus-name-acquisition read-only-method-parity production-recipe-trust], "C Runtime core live owner gate must expose expected gates")
  assert(live_owner_gate_statuses == %w[pass pending pending pending pending], "C Runtime core live owner gate must keep production gates pending")
  assert(live_owner_gate["blocked_reasons"].length == 5, "C Runtime core live owner gate must expose blocked reasons")
  assert(!live_owner_gate["network_required"], "C Runtime core live owner gate must not require network access")
  assert(!live_owner_gate["host_root_modified"], "C Runtime core live owner gate must not mutate the host root")
  assert(!live_owner_gate["privileged_container_required"], "C Runtime core live owner gate must not require privileged containers")
  assert(!live_owner_gate["backend_details_exposed"], "C Runtime core live owner gate must hide backend details")
  assert(!stdout.match?(/wine|prefix|\.wine|proton|virtual machine/i), "C Runtime core live owner gate must not expose backend implementation terms")

  stdout, stderr, status = Open3.capture3(binary.to_s, "write-gate", "Launch")
  assert(status.success?, "C Runtime core write-gate must exit successfully: #{stderr}")
  gate = JSON.parse(stdout)
  assert(gate["gate_type"] == "runtime-write-gate", "C Runtime core must emit write gate models")
  assert(gate["method_name"] == "Launch", "C Runtime core write gate must preserve the method")
  assert(gate["gate_decision"] == "blocked-until-production-backend", "C Runtime core must block writes until production backend")
  assert(!gate["write_method_enabled"], "C Runtime core must not enable writes")
  assert(!gate["dispatch_enabled"], "C Runtime core must not enable write dispatch")
  assert(!gate["request_object_created"], "C Runtime core must not create request objects")
  assert(!gate["execution_started"], "C Runtime core must not start execution")
  assert(gate["denial_error_name"] == "org.xnix.Compatibility1.Error.WriteMethodDisabled", "C Runtime core must expose the write denial error")

  _stdout, stderr, status = Open3.capture3(binary.to_s, "write-gate", "Unknown")
  assert(!status.success?, "C Runtime core must reject unknown write gate methods")
  assert(stderr.include?("reserved Runtime write method"), "C Runtime core must explain write gate validation")
end

puts "PASS: C Runtime core unit tests"
