#!/usr/bin/env ruby
# frozen_string_literal: true

require "json"
require "open3"
require "pathname"
require_relative "../lib/xnix/compatibility/kde_center_model"
require_relative "../lib/xnix/compatibility/recipe_store"
require_relative "../lib/xnix/compatibility/runtime_daemon"

def assert(condition, message)
  return if condition

  warn "FAIL: #{message}"
  exit 1
end

project_root = Pathname.new(__dir__).join("..").realpath
runtime = Xnix::Compatibility::RuntimeDaemon.new(
  recipe_store: Xnix::Compatibility::RecipeStore.new(path: project_root.join("runtime/recipes"))
)
model = Xnix::Compatibility::KdeCenterModel.new(runtime: runtime).to_h

assert(model["version"] == "0.2.191", "KDE center model must expose the current version")
assert(model["source"]["kind"] == "runtime-local-read-model", "KDE center model must describe the local fallback read model")
assert(model["source"]["bus_name"] == "org.xnix.Compatibility1", "KDE center model must keep the Runtime bus boundary visible")
assert(model["summary"]["application_count"] == 1, "KDE center model must summarize bundled applications")
assert(model["summary"]["known_application_count"] == 1, "KDE center model must summarize known applications")
assert(model["summary"]["pending_action_count"] == 1, "KDE center model must summarize pending compatibility work")
assert(model["summary"]["queued_compatibility_action_count"] == 5, "KDE center model must summarize queued Compatibility Center actions")
assert(model["summary"]["queued_user_review_count"] == 3, "KDE center model must summarize queued review actions")
assert(model["summary"]["recorded_action_review_count"] == 1, "KDE center model must summarize recorded action reviews")
assert(model["summary"]["compatibility_center_summary_count"] == 1, "KDE center model must summarize Compatibility Center summaries")
assert(model["summary"]["kde_shell_integration_plan_count"] == 1, "KDE center model must summarize KDE shell integration plans")
assert(model["summary"]["kde_shell_component_count"] == 9, "KDE center model must summarize KDE shell component counts")
assert(model["summary"]["compatibility_center_known_issue_count"] == 1, "KDE center model must summarize Compatibility Center known issues")
assert(model["summary"]["pending_test_step_count"] == 3, "KDE center model must summarize pending compatibility test work")
assert(model["summary"]["pending_test_result_count"] == 1, "KDE center model must summarize pending test results")
assert(model["summary"]["pending_install_plan_count"] == 1, "KDE center model must summarize pending install plans")
assert(model["summary"]["pending_acquisition_preflight_count"] == 1, "KDE center model must summarize pending acquisition preflight")
assert(model["summary"]["pending_artifact_manifest_count"] == 1, "KDE center model must summarize pending artifact manifests")
assert(model["summary"]["pending_package_source_count"] == 1, "KDE center model must summarize pending package sources")
assert(model["summary"]["planned_state_root_count"] == 1, "KDE center model must summarize planned state roots")
assert(model["summary"]["pending_backend_binding_count"] == 1, "KDE center model must summarize pending backend bindings")
assert(model["summary"]["pending_backend_capability_matrix_count"] == 1, "KDE center model must summarize pending backend capability matrices")
assert(model["summary"]["pending_backend_selection_count"] == 1, "KDE center model must summarize pending backend selections")
assert(model["summary"]["ai_diagnostic_ready_count"] == 1, "KDE center model must summarize AI diagnostic readiness")
assert(model["summary"]["ai_recommendation_ready_count"] == 1, "KDE center model must summarize AI recommendation readiness")
assert(model["summary"]["blocked_ai_repair_gate_count"] == 1, "KDE center model must summarize blocked AI repair gates")
assert(model["summary"]["pending_runtime_live_owner_gate_count"] == 1, "KDE center model must summarize pending Runtime live owner gates")
assert(model["summary"]["pending_runtime_owner_smoke_plan_count"] == 1, "KDE center model must summarize pending Runtime owner smoke plans")
assert(model["summary"]["runtime_method_parity_ready_count"] == 1, "KDE center model must summarize Runtime method parity readiness")
assert(model["summary"]["runtime_service_binding_ready_count"] == 1, "KDE center model must summarize Runtime service binding readiness")
assert(model["summary"]["blocked_runtime_write_gate_count"] == 1, "KDE center model must summarize blocked Runtime write gates")
assert(model["summary"]["runtime_settings_model_count"] == 1, "KDE center model must summarize Runtime settings models")
assert(model["summary"]["pending_settings_change_plan_count"] == 1, "KDE center model must summarize pending settings change plans")
assert(model["summary"]["pending_mode_switch_plan_count"] == 1, "KDE center model must summarize pending compatibility mode switch plans")
assert(model["summary"]["pending_permission_review_plan_count"] == 1, "KDE center model must summarize pending compatibility permission review plans")
assert(model["summary"]["pending_review_flow_plan_count"] == 1, "KDE center model must summarize pending compatibility review flow plans")

application = model.fetch("applications").first
assert(application["id"] == "org.xnix.sample.notepad", "KDE center model must include the sample application")
assert(application["mode_label"] == "Automatic", "KDE center model must present user-facing mode labels")
assert(application["compatibility_label"] == "Known", "KDE center model must present user-facing status labels")
assert(application["summary"] == "1 compatibility task pending", "KDE center model must present a concise task summary")
assert(application["repair"]["issue"] == "engine-binding-pending", "KDE center model must expose repair issue summaries")
assert(application["repair"]["snapshot_required"], "KDE center model must expose repair snapshot requirements")
assert(application["repair"]["snapshot"]["plan_type"] == "compatibility-snapshot", "KDE center model must expose snapshot summaries")
assert(application["repair"]["notification_event"] == "approval-required", "KDE center model must map repair plans to notifications")
assert(application["test_plan"]["plan_type"] == "compatibility-test", "KDE center model must expose test plan summaries")
assert(application["test_plan"]["pending_step_count"] == 3, "KDE center model must expose pending test steps")
assert(application["test_result"]["result_type"] == "compatibility-test-result", "KDE center model must expose test result summaries")
assert(application["test_result"]["overall_status"] == "pending", "KDE center model must expose test result status")
assert(application["action_queue"]["queue_type"] == "compatibility-center-action-queue", "KDE center model must expose action queues")
assert(application["action_queue"]["action_count"] == 5, "KDE center model must expose action queue counts")
assert(application["action_queue"]["user_review_required_count"] == 3, "KDE center model must expose review action counts")
assert(!application["action_queue"]["execution_enabled"], "KDE center model must not enable action queue execution")
assert(!application["action_queue"]["backend_details_exposed"], "KDE center model must hide action queue backend details")
assert(application["action_review_receipt"]["receipt_type"] == "compatibility-center-action-review-receipt", "KDE center model must expose action review receipts")
assert(application["action_review_receipt"]["decision_recorded"], "KDE center model must expose recorded review intent")
assert(!application["action_review_receipt"]["execution_enabled"], "KDE center model must not enable action review execution")
assert(!application["action_review_receipt"]["resource_grant_created"], "KDE center model must not claim resource grants from action reviews")
assert(!application["action_review_receipt"]["backend_details_exposed"], "KDE center model must hide action review backend details")
assert(application["compatibility_center_summary"]["summary_type"] == "compatibility-center-summary", "KDE center model must expose Compatibility Center summaries")
assert(application["compatibility_center_summary"]["compatibility_state"] == "review-required", "KDE center model must expose Compatibility Center review state")
assert(application["compatibility_center_summary"]["known_issue_count"] == 1, "KDE center model must expose Compatibility Center issue counts")
assert(application["compatibility_center_summary"]["repair_record_state"] == "pending-review", "KDE center model must expose Compatibility Center repair state")
assert(application["compatibility_center_summary"]["action_count"] == 4, "KDE center model must expose Compatibility Center action counts")
assert(!application["compatibility_center_summary"]["action_execution_enabled"], "KDE center model must not enable Compatibility Center actions")
assert(!application["compatibility_center_summary"]["repair_execution_enabled"], "KDE center model must not enable Compatibility Center repairs")
assert(!application["compatibility_center_summary"]["backend_launch_enabled"], "KDE center model must not enable Compatibility Center backend launch")
assert(!application["compatibility_center_summary"]["backend_details_exposed"], "KDE center model must hide Compatibility Center backend details")
assert(application["install_plan"]["plan_type"] == "compatibility-install-plan", "KDE center model must expose install plan summaries")
assert(application["install_plan"]["install_state"] == "planned", "KDE center model must expose install plan state")
assert(!application["install_plan"]["install_ready"], "KDE center model must not claim install readiness")
assert(!application["install_plan"]["desktop_activation_ready"], "KDE center model must not claim desktop activation readiness")
assert(!application["install_plan"]["download_enabled"], "KDE center model must not enable install plan downloads")
assert(!application["install_plan"]["install_enabled"], "KDE center model must not enable install plan execution")
assert(application["acquisition_preflight"]["preflight_type"] == "compatibility-acquisition-preflight", "KDE center model must expose acquisition preflight summaries")
assert(application["acquisition_preflight"]["preflight_state"] == "planned", "KDE center model must expose acquisition preflight state")
assert(!application["acquisition_preflight"]["acquisition_ready"], "KDE center model must not claim acquisition readiness")
assert(!application["acquisition_preflight"]["download_enabled"], "KDE center model must not enable downloads")
assert(application["artifact_manifest"]["manifest_type"] == "compatibility-artifact-manifest", "KDE center model must expose artifact manifest summaries")
assert(application["artifact_manifest"]["manifest_state"] == "planned", "KDE center model must expose artifact manifest state")
assert(!application["artifact_manifest"]["manifest_ready"], "KDE center model must not claim artifact manifest readiness")
assert(!application["artifact_manifest"]["download_enabled"], "KDE center model must not enable artifact downloads")
assert(application["package_source"]["source_type"] == "compatibility-package-source", "KDE center model must expose package source summaries")
assert(application["package_source"]["source_selection_state"] == "planned", "KDE center model must expose package source state")
assert(!application["package_source"]["package_source_ready"], "KDE center model must not claim package source readiness")
assert(!application["package_source"]["install_enabled"], "KDE center model must not enable package installation")
assert(application["state_root"]["root_type"] == "compatibility-application-state-root", "KDE center model must expose application state roots")
assert(application["state_root"]["allocation_state"] == "planned", "KDE center model must expose state root allocation")
assert(!application["state_root"]["user_documents_included"], "KDE center model must expose state root document exclusions")
assert(application["backend_binding"]["binding_type"] == "compatibility-backend-binding", "KDE center model must expose backend binding summaries")
assert(!application["backend_binding"]["managed_binding_ready"], "KDE center model must not claim backend binding readiness")
assert(!application["backend_binding"]["launch_enabled"], "KDE center model must not enable backend launches")
assert(application["backend_capability_matrix"]["matrix_type"] == "compatibility-backend-capability-matrix", "KDE center model must expose backend capability matrix summaries")
assert(application["backend_capability_matrix"]["runtime_method"] == "GetBackendCapabilityMatrix", "KDE center model must expose backend capability matrix Runtime methods")
assert(application["backend_capability_matrix"]["profile_count"] == 2, "KDE center model must expose backend capability profile counts")
assert(application["backend_capability_matrix"]["capability_count"] == 7, "KDE center model must expose backend capability counts")
assert(!application["backend_capability_matrix"]["selection_enabled"], "KDE center model must not enable backend selection")
assert(!application["backend_capability_matrix"]["backend_launch_enabled"], "KDE center model must not enable backend capability launch")
assert(!application["backend_capability_matrix"]["capability_activation_enabled"], "KDE center model must not enable backend capability activation")
assert(!application["backend_capability_matrix"]["request_objects_created"], "KDE center model must not create backend capability request objects")
assert(!application["backend_capability_matrix"]["state_root_created"], "KDE center model must not create backend capability state roots")
assert(!application["backend_capability_matrix"]["snapshots_created"], "KDE center model must not create backend capability snapshots")
assert(!application["backend_capability_matrix"]["host_root_modified"], "KDE center model must not mutate host root from backend capability matrix")
assert(!application["backend_capability_matrix"]["backend_details_exposed"], "KDE center model must hide backend capability details")
assert(application["backend_selection_plan"]["plan_type"] == "compatibility-backend-selection-plan", "KDE center model must expose backend selection plan summaries")
assert(application["backend_selection_plan"]["runtime_method"] == "GetBackendSelectionPlan", "KDE center model must expose backend selection Runtime methods")
assert(application["backend_selection_plan"]["candidate_count"] == 2, "KDE center model must expose backend selection candidate counts")
assert(!application["backend_selection_plan"]["selection_committed"], "KDE center model must not claim backend selection commits")
assert(!application["backend_selection_plan"]["selection_change_enabled"], "KDE center model must not enable backend selection changes")
assert(!application["backend_selection_plan"]["backend_launch_enabled"], "KDE center model must not enable backend launch from selection plans")
assert(!application["backend_selection_plan"]["environment_created"], "KDE center model must not claim backend selection environment creation")
assert(!application["backend_selection_plan"]["request_object_created"], "KDE center model must not create backend selection request objects")
assert(!application["backend_selection_plan"]["host_root_modified"], "KDE center model must not mutate host root from backend selection")
assert(!application["backend_selection_plan"]["backend_details_exposed"], "KDE center model must hide backend selection details")
assert(application["backend_environment_plan"]["plan_type"] == "compatibility-backend-environment-plan", "KDE center model must expose backend environment plan summaries")
assert(application["backend_environment_plan"]["environment_state"] == "planned", "KDE center model must expose backend environment state")
assert(application["backend_environment_plan"]["profile_count"] == 2, "KDE center model must expose backend environment profile counts")
assert(!application["backend_environment_plan"]["environment_created"], "KDE center model must not claim backend environment creation")
assert(!application["backend_environment_plan"]["backend_process_started"], "KDE center model must not claim backend environment process starts")
assert(!application["backend_environment_plan"]["launch_enabled"], "KDE center model must not enable backend environment launch")
assert(application["kde_shell_integration_plan"]["plan_type"] == "kde-shell-integration-plan", "KDE center model must expose KDE shell integration summaries")
assert(application["kde_shell_integration_plan"]["runtime_method"] == "GetKDEShellIntegrationPlan", "KDE center model must expose KDE shell integration Runtime methods")
assert(application["kde_shell_integration_plan"]["component_count"] == 9, "KDE center model must expose KDE shell component counts")
assert(application["kde_shell_integration_plan"]["initial_component_count"] == 8, "KDE center model must expose initial KDE shell component counts")
assert(!application["kde_shell_integration_plan"]["plasma_fork_required"], "KDE center model must not require Plasma forks")
assert(!application["kde_shell_integration_plan"]["shell_configuration_written"], "KDE center model must not write KDE shell configuration")
assert(!application["kde_shell_integration_plan"]["component_activation_enabled"], "KDE center model must not activate KDE shell components")
assert(!application["kde_shell_integration_plan"]["backend_launch_enabled"], "KDE center model must not enable backend launch from KDE shell plans")
assert(application["kde_application_surface_plan"]["plan_type"] == "kde-application-surface-plan", "KDE center model must expose KDE application surface summaries")
assert(application["kde_application_surface_plan"]["entry_point_count"] == 7, "KDE center model must expose KDE surface entry point counts")
assert(application["kde_application_surface_plan"]["normal_linux_application_surface"], "KDE center model must preserve normal Linux app presentation")
assert(application["kde_application_surface_plan"]["standard_launcher_visible"], "KDE center model must preserve standard launcher visibility")
assert(!application["kde_application_surface_plan"]["launch_enabled"], "KDE center model must not enable KDE surface launch")
assert(!application["kde_application_surface_plan"]["backend_process_started"], "KDE center model must not start backends from KDE surfaces")
assert(application["desktop_resource_bridge_plan"]["plan_type"] == "desktop-resource-bridge-plan", "KDE center model must expose desktop resource bridge summaries")
assert(application["desktop_resource_bridge_plan"]["resource_count"] == 5, "KDE center model must expose desktop resource bridge counts")
assert(application["desktop_resource_bridge_plan"]["portal_mediated"], "KDE center model must preserve Portal-mediated bridge policy")
assert(application["desktop_resource_bridge_plan"]["file_bridge_planned"], "KDE center model must expose file bridge planning")
assert(application["desktop_resource_bridge_plan"]["print_bridge_planned"], "KDE center model must expose print bridge planning")
assert(application["desktop_resource_bridge_plan"]["clipboard_bridge_planned"], "KDE center model must expose clipboard bridge planning")
assert(!application["desktop_resource_bridge_plan"]["bridges_enabled"], "KDE center model must not enable desktop resource bridges")
assert(application["backend_lifecycle"]["lifecycle_type"] == "compatibility-backend-lifecycle", "KDE center model must expose backend lifecycle summaries")
assert(application["backend_lifecycle"]["lifecycle_state"] == "blocked", "KDE center model must expose backend lifecycle state")
assert(application["backend_lifecycle"]["overall_status"] == "not-ready", "KDE center model must not claim backend lifecycle readiness")
assert(application["backend_lifecycle"]["stage_count"] == 5, "KDE center model must expose backend lifecycle stage counts")
assert(!application["backend_lifecycle"]["backend_process_started"], "KDE center model must not claim backend process starts")
assert(!application["backend_lifecycle"]["launch_enabled"], "KDE center model must not enable lifecycle launch")
assert(application["ai_diagnostic_input"]["input_type"] == "ai-diagnostic-input", "KDE center model must expose AI diagnostic input summaries")
assert(application["ai_diagnostic_input"]["safe_for_ai_diagnostics"], "KDE center model must expose AI diagnostic safety")
assert(!application["ai_diagnostic_input"]["ai_provider_called"], "KDE center model must not claim AI provider calls")
assert(application["ai_diagnostic_recommendation"]["recommendation_type"] == "ai-diagnostic-recommendation", "KDE center model must expose AI diagnostic recommendation summaries")
assert(application["ai_diagnostic_recommendation"]["recommendation_count"] == 3, "KDE center model must expose AI recommendation counts")
assert(!application["ai_diagnostic_recommendation"]["ai_provider_called"], "KDE center model must not claim recommendation AI provider calls")
assert(application["ai_repair_approval_gate"]["gate_type"] == "ai-repair-approval-gate", "KDE center model must expose AI repair approval gates")
assert(application["ai_repair_approval_gate"]["gate_decision"] == "blocked-until-approval", "KDE center model must expose AI repair gate decisions")
assert(!application["ai_repair_approval_gate"]["auto_execution_allowed"], "KDE center model must not allow automatic AI repair execution")
assert(application["runtime_live_owner_gate"]["gate_type"] == "runtime-live-owner-gate", "KDE center model must expose Runtime live owner gates")
assert(application["runtime_live_owner_gate"]["activation_binding_ready"], "KDE center model must expose Runtime live owner activation readiness")
assert(!application["runtime_live_owner_gate"]["live_dbus_owner_ready"], "KDE center model must not claim Runtime live D-Bus ownership")
assert(!application["runtime_live_owner_gate"]["production_owner_enabled"], "KDE center model must not enable production Runtime ownership")
assert(!application["runtime_live_owner_gate"]["owner_transition_ready"], "KDE center model must not enable Runtime owner transition")
assert(!application["runtime_live_owner_gate"]["smoke_adapter_is_production_owner"], "KDE center model must not treat smoke adapter as production owner")
assert(application["runtime_owner_smoke_plan"]["plan_type"] == "runtime-owner-smoke-plan", "KDE center model must expose Runtime owner smoke plans")
assert(application["runtime_owner_smoke_plan"]["smoke_state"] == "planned", "KDE center model must expose owner smoke plan state")
assert(application["runtime_owner_smoke_plan"]["smoke_environment"] == "restricted-session", "KDE center model must expose owner smoke environment")
assert(application["runtime_owner_smoke_plan"]["pending_step_count"] == 6, "KDE center model must expose pending owner smoke steps")
assert(!application["runtime_owner_smoke_plan"]["system_service_started"], "KDE center model must not claim started system services")
assert(!application["runtime_owner_smoke_plan"]["production_bus_claimed"], "KDE center model must not claim production bus ownership")
assert(application["runtime_method_parity_manifest"]["manifest_type"] == "runtime-method-parity-manifest", "KDE center model must expose Runtime method parity manifests")
assert(application["runtime_method_parity_manifest"]["method_count"] == 57, "KDE center model must expose Runtime method counts")
assert(application["runtime_method_parity_manifest"]["read_only_method_parity_ready"], "KDE center model must expose Runtime method parity readiness")
assert(application["runtime_method_parity_manifest"]["passed_check_count"] == 5, "KDE center model must expose Runtime method parity pass counts")
assert(application["runtime_method_parity_manifest"]["blocked_check_count"].zero?, "KDE center model must expose Runtime method parity blocked counts")
assert(!application["runtime_method_parity_manifest"]["write_methods_supported"], "KDE center model must not claim write method support")
assert(!application["runtime_method_parity_manifest"]["write_method_dispatch_enabled"], "KDE center model must not claim write method dispatch")
assert(application["runtime_write_gate"]["gate_type"] == "runtime-write-gate", "KDE center model must expose Runtime write gates")
assert(application["runtime_write_gate"]["method_name"] == "Launch", "KDE center model must expose launch write gate status")
assert(application["runtime_write_gate"]["gate_decision"] == "blocked-until-production-backend", "KDE center model must expose write gate decisions")
assert(!application["runtime_write_gate"]["write_method_enabled"], "KDE center model must not enable write methods")
assert(!application["runtime_write_gate"]["dispatch_enabled"], "KDE center model must not enable write dispatch")
assert(!application["runtime_write_gate"]["request_object_created"], "KDE center model must not claim write request objects")
assert(application["runtime_write_gate"]["required_gate_count"] == 6, "KDE center model must expose required write gate counts")
assert(!application["runtime_write_gate"]["backend_details_exposed"], "KDE center model must hide write gate backend details")
assert(application["runtime_service_binding"]["binding_type"] == "runtime-service-binding", "KDE center model must expose Runtime service binding")
assert(application["runtime_service_binding"]["activation_binding_ready"], "KDE center model must expose activation binding readiness")
assert(!application["runtime_service_binding"]["live_dbus_owner_ready"], "KDE center model must not claim live D-Bus ownership")
assert(application["settings"]["request_type"] == "settings-model", "KDE center model must expose compatibility settings")
assert(application["settings"]["settings_state"] == "planned", "KDE center model must expose settings state")
assert(!application["settings"]["settings_persisted"], "KDE center model must not claim settings persistence")
assert(!application["settings"]["host_root_modified"], "KDE center model must not mutate host root for settings")
assert(!application["settings"]["backend_details_exposed"], "KDE center model must hide settings backend details")
assert(application["settings_change_plan"]["plan_type"] == "settings-change-plan", "KDE center model must expose settings change plans")
assert(application["settings_change_plan"]["change_state"] == "planned", "KDE center model must expose settings change plan state")
assert(!application["settings_change_plan"]["apply_enabled"], "KDE center model must not enable planned settings changes")
assert(!application["settings_change_plan"]["settings_persisted"], "KDE center model must not claim settings change persistence")
assert(!application["settings_change_plan"]["backend_details_exposed"], "KDE center model must hide settings change backend details")
assert(application["compatibility_mode_switch_plan"]["plan_type"] == "compatibility-mode-switch-plan", "KDE center model must expose compatibility mode switch plans")
assert(application["compatibility_mode_switch_plan"]["runtime_method"] == "GetCompatibilityModeSwitchPlan", "KDE center model must expose compatibility mode switch Runtime methods")
assert(application["compatibility_mode_switch_plan"]["mode_state"] == "planned", "KDE center model must keep mode switches planned")
assert(application["compatibility_mode_switch_plan"]["mode_count"] == 4, "KDE center model must expose compatibility mode counts")
assert(application["compatibility_mode_switch_plan"]["requires_user_confirmation"], "KDE center model must expose mode switch confirmation gates")
assert(application["compatibility_mode_switch_plan"]["snapshot_required"], "KDE center model must expose mode switch snapshot gates")
assert(!application["compatibility_mode_switch_plan"]["settings_persistence_enabled"], "KDE center model must not enable mode switch persistence")
assert(!application["compatibility_mode_switch_plan"]["backend_reconfiguration_enabled"], "KDE center model must not reconfigure backends from mode switches")
assert(!application["compatibility_mode_switch_plan"]["backend_process_started"], "KDE center model must not start backend processes from mode switches")
assert(!application["compatibility_mode_switch_plan"]["backend_details_exposed"], "KDE center model must hide mode switch backend details")
assert(application["compatibility_permission_review_plan"]["plan_type"] == "compatibility-permission-review-plan", "KDE center model must expose compatibility permission review plans")
assert(application["compatibility_permission_review_plan"]["runtime_method"] == "GetCompatibilityPermissionReviewPlan", "KDE center model must expose compatibility permission review Runtime methods")
assert(application["compatibility_permission_review_plan"]["review_state"] == "planned", "KDE center model must keep permission reviews planned")
assert(application["compatibility_permission_review_plan"]["permission_count"] == 7, "KDE center model must expose permission review counts")
assert(!application["compatibility_permission_review_plan"]["permissions_granted"], "KDE center model must not grant permissions")
assert(!application["compatibility_permission_review_plan"]["settings_persisted"], "KDE center model must not persist permission settings")
assert(!application["compatibility_permission_review_plan"]["host_permission_changed"], "KDE center model must not change host permissions")
assert(!application["compatibility_permission_review_plan"]["backend_details_exposed"], "KDE center model must hide permission review backend details")
assert(application["compatibility_review_flow_plan"]["plan_type"] == "compatibility-review-flow-plan", "KDE center model must expose compatibility review flow plans")
assert(application["compatibility_review_flow_plan"]["runtime_method"] == "GetCompatibilityReviewFlowPlan", "KDE center model must expose compatibility review flow Runtime methods")
assert(application["compatibility_review_flow_plan"]["review_state"] == "planned", "KDE center model must keep review flows planned")
assert(application["compatibility_review_flow_plan"]["step_count"] == 5, "KDE center model must expose review flow step counts")
assert(application["compatibility_review_flow_plan"]["user_confirmation_required"], "KDE center model must expose review flow confirmation gates")
assert(application["compatibility_review_flow_plan"]["portal_policy_review_required"], "KDE center model must expose review flow Portal gates")
assert(!application["compatibility_review_flow_plan"]["apply_enabled"], "KDE center model must not apply review flows")
assert(!application["compatibility_review_flow_plan"]["permission_granted"], "KDE center model must not grant permissions through review flows")
assert(!application["compatibility_review_flow_plan"]["settings_persisted"], "KDE center model must not persist settings through review flows")
assert(!application["compatibility_review_flow_plan"]["execution_started"], "KDE center model must not start execution through review flows")
assert(!application["compatibility_review_flow_plan"]["host_root_modified"], "KDE center model must not mutate the host root through review flows")
assert(!application["compatibility_review_flow_plan"]["backend_details_exposed"], "KDE center model must hide review flow backend details")
assert(application["supported_extensions"].include?(".txt"), "KDE center model must include supported file extensions")

json = JSON.pretty_generate(model)
assert(!json.match?(/prefix|\.wine|proton|virtual machine/i), "KDE center model must not expose backend storage or implementation terms")

MinimalRuntime = Struct.new(:application) do
  def list_applications
    [application]
  end

  def diagnostics(_application_id)
    {
      "application_id" => application.fetch("id"),
      "status" => "known",
      "runtime_mode" => "automatic"
    }
  end

  def source_metadata
    {
      "kind" => "runtime-dbus-session",
      "bus_name" => "org.xnix.Compatibility1",
      "object_path" => "/org/xnix/Compatibility1",
      "interface" => "org.xnix.Compatibility1"
    }
  end
end

minimal_model = Xnix::Compatibility::KdeCenterModel.new(runtime: MinimalRuntime.new(runtime.list_applications.first)).to_h
assert(minimal_model["summary"]["pending_test_step_count"].zero?, "KDE center model must tolerate missing D-Bus test plan summaries")
assert(minimal_model["summary"]["queued_compatibility_action_count"].zero?, "KDE center model must tolerate missing D-Bus action queue summaries")
assert(minimal_model["summary"]["recorded_action_review_count"].zero?, "KDE center model must tolerate missing D-Bus action review summaries")
assert(minimal_model["summary"]["compatibility_center_summary_count"].zero?, "KDE center model must tolerate missing D-Bus Compatibility Center summaries")
assert(minimal_model["summary"]["pending_runtime_live_owner_gate_count"].zero?, "KDE center model must tolerate missing D-Bus live owner gate summaries")
assert(minimal_model["summary"]["pending_runtime_owner_smoke_plan_count"].zero?, "KDE center model must tolerate missing D-Bus owner smoke plan summaries")
assert(minimal_model["summary"]["runtime_method_parity_ready_count"].zero?, "KDE center model must tolerate missing D-Bus method parity summaries")
assert(minimal_model["summary"]["runtime_service_binding_ready_count"].zero?, "KDE center model must tolerate missing D-Bus service binding summaries")
assert(minimal_model["summary"]["blocked_runtime_write_gate_count"].zero?, "KDE center model must tolerate missing D-Bus write gate summaries")

stdout, stderr, status = Open3.capture3("ruby", project_root.join("bin/xnix-kde-center-model").to_s, "--source", "local")
assert(status.success?, "KDE center model CLI must exit successfully: #{stderr}")
cli_model = JSON.parse(stdout)
assert(cli_model == model, "KDE center model CLI must emit the same model")

puts "PASS: KDE compatibility center model unit tests"
