#!/usr/bin/env ruby
# frozen_string_literal: true

require "json"
require "open3"
require "pathname"

def assert(condition, message)
  return if condition

  warn "FAIL: #{message}"
  exit 1
end

project_root = Pathname.new(__dir__).join("..").realpath
command = ["ruby", project_root.join("bin/xnix-compatd").to_s]

stdout, stderr, status = Open3.capture3(*command, "probe")
assert(status.success?, "runtime daemon probe must exit successfully: #{stderr}")
probe = JSON.parse(stdout)
assert(probe["version"] == "0.2.123", "runtime daemon probe must report the current version")
assert(probe["bus_name"] == "org.xnix.Compatibility1", "runtime daemon probe must keep the stable bus name")
assert(probe["capabilities"]["recipe_store"], "runtime daemon probe must expose recipe store capability")
assert(probe["capabilities"]["registry_backed_recipe_store"], "runtime daemon probe must expose registry-backed recipe loading")
assert(probe["capabilities"]["application_state_roots"], "runtime daemon probe must expose application state roots")
assert(probe["capabilities"]["compatibility_acquisition_preflight"], "runtime daemon probe must expose acquisition preflight capability")
assert(probe["capabilities"]["compatibility_action_queues"], "runtime daemon probe must expose action queue capability")
assert(probe["capabilities"]["compatibility_action_review_receipts"], "runtime daemon probe must expose action review receipt capability")
assert(probe["capabilities"]["compatibility_center_summaries"], "runtime daemon probe must expose Compatibility Center summary capability")
assert(probe["capabilities"]["compatibility_artifact_manifests"], "runtime daemon probe must expose artifact manifest capability")
assert(probe["capabilities"]["compatibility_engine_catalog"], "runtime daemon probe must expose engine catalog capability")
assert(probe["capabilities"]["compatibility_install_planning"], "runtime daemon probe must expose install planning capability")
assert(probe["capabilities"]["compatibility_mode_switch_planning"], "runtime daemon probe must expose compatibility mode switch planning capability")
assert(probe["capabilities"]["compatibility_permission_review_planning"], "runtime daemon probe must expose compatibility permission review planning capability")
assert(probe["capabilities"]["compatibility_review_flow_planning"], "runtime daemon probe must expose compatibility review flow planning capability")
assert(probe["capabilities"]["compatibility_package_sources"], "runtime daemon probe must expose package source capability")
assert(probe["capabilities"]["compatibility_backend_binding"], "runtime daemon probe must expose backend binding capability")
assert(probe["capabilities"]["compatibility_backend_capability_matrix"], "runtime daemon probe must expose backend capability matrix capability")
assert(probe["capabilities"]["compatibility_backend_selection_plans"], "runtime daemon probe must expose backend selection planning capability")
assert(probe["capabilities"]["compatibility_backend_environment_plans"], "runtime daemon probe must expose backend environment planning capability")
assert(probe["capabilities"]["compatibility_backend_lifecycle"], "runtime daemon probe must expose backend lifecycle capability")
assert(probe["capabilities"]["compatibility_run_planning"], "runtime daemon probe must expose run planning capability")
assert(probe["capabilities"]["kde_integration_status"], "runtime daemon probe must expose KDE integration status capability")
assert(probe["capabilities"]["kde_shell_integration_plans"], "runtime daemon probe must expose KDE shell integration plan capability")
assert(probe["capabilities"]["kde_application_surface_plans"], "runtime daemon probe must expose KDE application surface planning capability")
assert(probe["capabilities"]["desktop_resource_bridge_plans"], "runtime daemon probe must expose desktop resource bridge planning capability")
assert(probe["capabilities"]["desktop_entry_planning"], "runtime daemon probe must expose desktop entry planning capability")
assert(probe["capabilities"]["task_manager_identity_planning"], "runtime daemon probe must expose task manager identity planning capability")
assert(probe["capabilities"]["kwin_window_rule_planning"], "runtime daemon probe must expose KWin window rule planning capability")
assert(probe["capabilities"]["file_association_planning"], "runtime daemon probe must expose file association planning capability")
assert(probe["capabilities"]["notification_planning"], "runtime daemon probe must expose notification planning capability")
assert(probe["capabilities"]["tray_status_planning"], "runtime daemon probe must expose tray status planning capability")
assert(probe["capabilities"]["krunner_query_planning"], "runtime daemon probe must expose KRunner query planning capability")
assert(probe["capabilities"]["compatibility_repair_planning"], "runtime daemon probe must expose repair planning capability")
assert(probe["capabilities"]["compatibility_test_planning"], "runtime daemon probe must expose test planning capability")
assert(probe["capabilities"]["compatibility_test_results"], "runtime daemon probe must expose test result capability")
assert(probe["capabilities"]["compatibility_execution_readiness"], "runtime daemon probe must expose execution readiness capability")
assert(probe["capabilities"]["compatibility_launch_intents"], "runtime daemon probe must expose launch intent capability")
assert(probe["capabilities"]["ai_diagnostic_inputs"], "runtime daemon probe must expose AI diagnostic input capability")
assert(probe["capabilities"]["ai_diagnostic_recommendations"], "runtime daemon probe must expose AI diagnostic recommendation capability")
assert(probe["capabilities"]["ai_repair_approval_gates"], "runtime daemon probe must expose AI repair approval gate capability")
assert(probe["capabilities"]["runtime_live_owner_gates"], "runtime daemon probe must expose Runtime live owner gate capability")
assert(probe["capabilities"]["runtime_method_parity_manifests"], "runtime daemon probe must expose Runtime method parity manifest capability")
assert(probe["capabilities"]["runtime_owner_smoke_plans"], "runtime daemon probe must expose Runtime owner smoke plan capability")
assert(probe["capabilities"]["runtime_service_binding"], "runtime daemon probe must expose Runtime service binding capability")
assert(probe["capabilities"]["runtime_write_gates"], "runtime daemon probe must expose Runtime write gate capability")
assert(probe["capabilities"]["compatibility_settings"], "runtime daemon probe must expose compatibility settings capability")
assert(probe["capabilities"]["compatibility_settings_change_planning"], "runtime daemon probe must expose settings change planning capability")
assert(probe["capabilities"]["dbus_method_dispatch"], "runtime daemon probe must expose method dispatch capability")
assert(!probe["capabilities"]["dbus_binding"], "runtime daemon must not claim a D-Bus binding before it exists")
assert(probe["recipe_trust"]["registry_backed"], "runtime daemon probe must report registry-backed recipe loading")
assert(probe["recipe_trust"]["digest_verified"], "runtime daemon probe must report digest-verified recipes")
assert(!probe["recipe_trust"]["signed_recipe_validation"], "runtime daemon probe must not claim production recipe signatures yet")

stdout, stderr, status = Open3.capture3(*command, "list-applications")
assert(status.success?, "runtime daemon list must exit successfully: #{stderr}")
applications = JSON.parse(stdout)
assert(applications.length == 1, "runtime daemon must list the bundled sample application")
assert(applications.first["id"] == "org.xnix.sample.notepad", "runtime daemon must expose sample recipe id")
assert(applications.first["mime_types"].include?("application/x-xnix-txt"), "runtime daemon must expose MIME types")

stdout, stderr, status = Open3.capture3(*command, "diagnostics", "org.xnix.sample.notepad")
assert(status.success?, "runtime daemon diagnostics must exit successfully: #{stderr}")
diagnostics = JSON.parse(stdout)
assert(diagnostics["status"] == "known", "runtime daemon diagnostics must know bundled recipes")
assert(diagnostics["checks"].any? { |check| check["status"] == "pending" }, "runtime daemon must report backend work as pending")
assert(diagnostics["test_plan"]["plan_type"] == "compatibility-test", "runtime daemon diagnostics must include compatibility test planning")
assert(diagnostics["test_plan"]["pending_step_count"] == 3, "runtime daemon diagnostics must count pending test steps")
assert(diagnostics["test_result"]["result_type"] == "compatibility-test-result", "runtime daemon diagnostics must include compatibility test results")
assert(diagnostics["test_result"]["overall_status"] == "pending", "runtime daemon diagnostics must expose pending test status")
assert(diagnostics["test_result"]["counts"]["pending"] == 3, "runtime daemon diagnostics must count pending test results")
assert(diagnostics["action_queue"]["queue_type"] == "compatibility-center-action-queue", "runtime daemon diagnostics must include action queues")
assert(diagnostics["action_queue"]["action_count"] == 5, "runtime daemon diagnostics must count action queue items")
assert(diagnostics["action_queue"]["user_review_required_count"] == 3, "runtime daemon diagnostics must count review-required actions")
assert(!diagnostics["action_queue"]["execution_enabled"], "runtime daemon diagnostics must not enable queued action execution")
assert(diagnostics["action_review_receipt"]["receipt_type"] == "compatibility-center-action-review-receipt", "runtime daemon diagnostics must include action review receipts")
assert(diagnostics["action_review_receipt"]["decision_recorded"], "runtime daemon diagnostics must record review intent")
assert(!diagnostics["action_review_receipt"]["execution_enabled"], "runtime daemon diagnostics must not enable review receipt execution")
assert(!diagnostics["action_review_receipt"]["resource_grant_created"], "runtime daemon diagnostics must not create resource grants from review receipts")
assert(diagnostics["compatibility_center_summary"]["summary_type"] == "compatibility-center-summary", "runtime daemon diagnostics must include Compatibility Center summaries")
assert(diagnostics["compatibility_center_summary"]["compatibility_state"] == "review-required", "runtime daemon diagnostics must expose Compatibility Center state")
assert(diagnostics["compatibility_center_summary"]["known_issue_count"] == 1, "runtime daemon diagnostics must count Compatibility Center issues")
assert(diagnostics["compatibility_center_summary"]["repair_record_state"] == "pending-review", "runtime daemon diagnostics must expose Compatibility Center repair state")
assert(diagnostics["compatibility_center_summary"]["action_count"] == 4, "runtime daemon diagnostics must count Compatibility Center actions")
assert(!diagnostics["compatibility_center_summary"]["action_execution_enabled"], "runtime daemon diagnostics must keep Compatibility Center actions disabled")
assert(!diagnostics["compatibility_center_summary"]["repair_execution_enabled"], "runtime daemon diagnostics must keep Compatibility Center repairs disabled")
assert(!diagnostics["compatibility_center_summary"]["backend_launch_enabled"], "runtime daemon diagnostics must keep Compatibility Center backend launch disabled")
assert(!diagnostics["compatibility_center_summary"]["backend_details_exposed"], "runtime daemon diagnostics must hide Compatibility Center backend details")
assert(diagnostics["install_plan"]["plan_type"] == "compatibility-install-plan", "runtime daemon diagnostics must include install planning")
assert(diagnostics["install_plan"]["install_state"] == "planned", "runtime daemon diagnostics must expose install plan state")
assert(!diagnostics["install_plan"]["install_ready"], "runtime daemon diagnostics must not claim install readiness")
assert(!diagnostics["install_plan"]["download_enabled"], "runtime daemon diagnostics must not enable install downloads")
assert(!diagnostics["install_plan"]["install_enabled"], "runtime daemon diagnostics must not enable install execution")
assert(diagnostics["acquisition_preflight"]["preflight_type"] == "compatibility-acquisition-preflight", "runtime daemon diagnostics must include acquisition preflight")
assert(diagnostics["acquisition_preflight"]["preflight_state"] == "planned", "runtime daemon diagnostics must expose acquisition preflight state")
assert(!diagnostics["acquisition_preflight"]["acquisition_ready"], "runtime daemon diagnostics must not claim acquisition readiness")
assert(!diagnostics["acquisition_preflight"]["download_enabled"], "runtime daemon diagnostics must not enable downloads")
assert(diagnostics["artifact_manifest"]["manifest_type"] == "compatibility-artifact-manifest", "runtime daemon diagnostics must include artifact manifests")
assert(diagnostics["artifact_manifest"]["manifest_state"] == "planned", "runtime daemon diagnostics must expose artifact manifest state")
assert(!diagnostics["artifact_manifest"]["manifest_ready"], "runtime daemon diagnostics must not claim artifact manifest readiness")
assert(!diagnostics["artifact_manifest"]["download_enabled"], "runtime daemon diagnostics must not enable artifact downloads")
assert(diagnostics["package_source"]["source_type"] == "compatibility-package-source", "runtime daemon diagnostics must include package sources")
assert(diagnostics["package_source"]["source_selection_state"] == "planned", "runtime daemon diagnostics must expose package source state")
assert(!diagnostics["package_source"]["package_source_ready"], "runtime daemon diagnostics must not claim package source readiness")
assert(!diagnostics["package_source"]["install_enabled"], "runtime daemon diagnostics must not enable package installation")
assert(diagnostics["state_root"]["root_type"] == "compatibility-application-state-root", "runtime daemon diagnostics must include application state roots")
assert(diagnostics["state_root"]["allocation_state"] == "planned", "runtime daemon diagnostics must expose planned state roots")
assert(!diagnostics["state_root"]["user_documents_included"], "runtime daemon diagnostics must exclude user documents from state roots")
assert(diagnostics["backend_binding"]["binding_type"] == "compatibility-backend-binding", "runtime daemon diagnostics must include backend binding")
assert(!diagnostics["backend_binding"]["managed_binding_ready"], "runtime daemon diagnostics must not claim backend binding readiness")
assert(!diagnostics["backend_binding"]["launch_enabled"], "runtime daemon diagnostics must not enable backend launch yet")
assert(diagnostics["backend_capability_matrix"]["matrix_type"] == "compatibility-backend-capability-matrix", "runtime daemon diagnostics must include backend capability matrix")
assert(diagnostics["backend_capability_matrix"]["runtime_method"] == "GetBackendCapabilityMatrix", "runtime daemon diagnostics must expose backend capability matrix Runtime methods")
assert(diagnostics["backend_capability_matrix"]["profile_count"] == 2, "runtime daemon diagnostics must expose backend capability profile counts")
assert(diagnostics["backend_capability_matrix"]["capability_count"] == 7, "runtime daemon diagnostics must expose backend capability counts")
assert(!diagnostics["backend_capability_matrix"]["selection_enabled"], "runtime daemon diagnostics must not enable backend selection")
assert(!diagnostics["backend_capability_matrix"]["backend_launch_enabled"], "runtime daemon diagnostics must not enable backend capability launch")
assert(!diagnostics["backend_capability_matrix"]["capability_activation_enabled"], "runtime daemon diagnostics must not activate backend capabilities")
assert(!diagnostics["backend_capability_matrix"]["request_objects_created"], "runtime daemon diagnostics must not create backend capability request objects")
assert(!diagnostics["backend_capability_matrix"]["state_root_created"], "runtime daemon diagnostics must not create backend state roots")
assert(!diagnostics["backend_capability_matrix"]["snapshots_created"], "runtime daemon diagnostics must not create backend snapshots")
assert(!diagnostics["backend_capability_matrix"]["host_root_modified"], "runtime daemon diagnostics must not mutate host root from backend capability matrix")
assert(!diagnostics["backend_capability_matrix"]["backend_details_exposed"], "runtime daemon diagnostics must hide backend capability details")
assert(diagnostics["backend_selection_plan"]["plan_type"] == "compatibility-backend-selection-plan", "runtime daemon diagnostics must include backend selection plans")
assert(diagnostics["backend_selection_plan"]["runtime_method"] == "GetBackendSelectionPlan", "runtime daemon diagnostics must expose backend selection Runtime methods")
assert(diagnostics["backend_selection_plan"]["candidate_count"] == 2, "runtime daemon diagnostics must expose backend selection candidates")
assert(!diagnostics["backend_selection_plan"]["selection_committed"], "runtime daemon diagnostics must not commit backend selection")
assert(!diagnostics["backend_selection_plan"]["selection_change_enabled"], "runtime daemon diagnostics must not enable backend selection changes")
assert(!diagnostics["backend_selection_plan"]["backend_launch_enabled"], "runtime daemon diagnostics must not enable backend launch from selection plans")
assert(!diagnostics["backend_selection_plan"]["environment_created"], "runtime daemon diagnostics must not create backend environments from selection plans")
assert(!diagnostics["backend_selection_plan"]["request_object_created"], "runtime daemon diagnostics must not create selection request objects")
assert(!diagnostics["backend_selection_plan"]["host_root_modified"], "runtime daemon diagnostics must not mutate host root from backend selection")
assert(!diagnostics["backend_selection_plan"]["backend_details_exposed"], "runtime daemon diagnostics must hide backend selection details")
assert(diagnostics["backend_environment_plan"]["plan_type"] == "compatibility-backend-environment-plan", "runtime daemon diagnostics must include backend environment plans")
assert(diagnostics["backend_environment_plan"]["environment_state"] == "planned", "runtime daemon diagnostics must expose planned backend environments")
assert(!diagnostics["backend_environment_plan"]["environment_created"], "runtime daemon diagnostics must not claim backend environment creation")
assert(!diagnostics["backend_environment_plan"]["backend_process_started"], "runtime daemon diagnostics must not claim backend environment process starts")
assert(diagnostics["kde_shell_integration_plan"]["plan_type"] == "kde-shell-integration-plan", "runtime daemon diagnostics must include KDE shell integration plans")
assert(diagnostics["kde_shell_integration_plan"]["runtime_method"] == "GetKDEShellIntegrationPlan", "runtime daemon diagnostics must expose KDE shell integration Runtime methods")
assert(diagnostics["kde_shell_integration_plan"]["component_count"] == 9, "runtime daemon diagnostics must count KDE shell components")
assert(diagnostics["kde_shell_integration_plan"]["initial_component_count"] == 8, "runtime daemon diagnostics must count initial KDE shell components")
assert(!diagnostics["kde_shell_integration_plan"]["plasma_fork_required"], "runtime daemon diagnostics must not require Plasma forks")
assert(!diagnostics["kde_shell_integration_plan"]["shell_configuration_written"], "runtime daemon diagnostics must not write KDE shell configuration")
assert(!diagnostics["kde_shell_integration_plan"]["component_activation_enabled"], "runtime daemon diagnostics must not activate KDE shell components")
assert(!diagnostics["kde_shell_integration_plan"]["backend_launch_enabled"], "runtime daemon diagnostics must not launch backends from KDE shell planning")
assert(diagnostics["kde_application_surface_plan"]["plan_type"] == "kde-application-surface-plan", "runtime daemon diagnostics must include KDE application surface plans")
assert(diagnostics["kde_application_surface_plan"]["normal_linux_application_surface"], "runtime daemon diagnostics must present compatibility apps as normal Linux apps")
assert(diagnostics["kde_application_surface_plan"]["standard_launcher_visible"], "runtime daemon diagnostics must keep standard launcher visibility")
assert(!diagnostics["kde_application_surface_plan"]["launch_enabled"], "runtime daemon diagnostics must not enable KDE surface launch")
assert(!diagnostics["kde_application_surface_plan"]["backend_process_started"], "runtime daemon diagnostics must not start backends from KDE surfaces")
assert(diagnostics["desktop_resource_bridge_plan"]["plan_type"] == "desktop-resource-bridge-plan", "runtime daemon diagnostics must include desktop resource bridge plans")
assert(diagnostics["desktop_resource_bridge_plan"]["portal_mediated"], "runtime daemon diagnostics must require Portal-mediated resource bridges")
assert(diagnostics["desktop_resource_bridge_plan"]["file_bridge_planned"], "runtime daemon diagnostics must plan file bridges")
assert(diagnostics["desktop_resource_bridge_plan"]["print_bridge_planned"], "runtime daemon diagnostics must plan print bridges")
assert(diagnostics["desktop_resource_bridge_plan"]["clipboard_bridge_planned"], "runtime daemon diagnostics must plan clipboard bridges")
assert(!diagnostics["desktop_resource_bridge_plan"]["bridges_enabled"], "runtime daemon diagnostics must not enable desktop resource bridges")
assert(!diagnostics["desktop_resource_bridge_plan"]["requests_created"], "runtime daemon diagnostics must not create Portal requests")
assert(diagnostics["backend_lifecycle"]["lifecycle_type"] == "compatibility-backend-lifecycle", "runtime daemon diagnostics must include backend lifecycle")
assert(diagnostics["backend_lifecycle"]["lifecycle_state"] == "blocked", "runtime daemon diagnostics must expose blocked backend lifecycle state")
assert(!diagnostics["backend_lifecycle"]["backend_process_started"], "runtime daemon diagnostics must not claim backend process starts")
assert(!diagnostics["backend_lifecycle"]["launch_enabled"], "runtime daemon diagnostics must not enable backend lifecycle launch")
assert(diagnostics["ai_diagnostic_input"]["input_type"] == "ai-diagnostic-input", "runtime daemon diagnostics must include AI diagnostic input")
assert(diagnostics["ai_diagnostic_input"]["safe_for_ai_diagnostics"], "runtime daemon diagnostics must mark AI diagnostic input safe")
assert(!diagnostics["ai_diagnostic_input"]["ai_provider_called"], "runtime daemon diagnostics must not claim an AI provider call")
assert(diagnostics["ai_diagnostic_recommendation"]["recommendation_type"] == "ai-diagnostic-recommendation", "runtime daemon diagnostics must include AI diagnostic recommendations")
assert(diagnostics["ai_diagnostic_recommendation"]["recommendation_count"] == 3, "runtime daemon diagnostics must count AI diagnostic recommendations")
assert(!diagnostics["ai_diagnostic_recommendation"]["ai_provider_called"], "runtime daemon diagnostics must not claim recommendation AI provider calls")
assert(diagnostics["ai_repair_approval_gate"]["gate_type"] == "ai-repair-approval-gate", "runtime daemon diagnostics must include AI repair approval gates")
assert(diagnostics["ai_repair_approval_gate"]["gate_decision"] == "blocked-until-approval", "runtime daemon diagnostics must block repair execution until approval")
assert(!diagnostics["ai_repair_approval_gate"]["auto_execution_allowed"], "runtime daemon diagnostics must not allow automatic AI repair execution")
assert(diagnostics["runtime_live_owner_gate"]["gate_type"] == "runtime-live-owner-gate", "runtime daemon diagnostics must include Runtime live owner gates")
assert(diagnostics["runtime_live_owner_gate"]["activation_binding_ready"], "runtime daemon diagnostics must expose live owner activation readiness")
assert(!diagnostics["runtime_live_owner_gate"]["live_dbus_owner_ready"], "runtime daemon diagnostics must not claim live D-Bus owner readiness")
assert(!diagnostics["runtime_live_owner_gate"]["production_owner_enabled"], "runtime daemon diagnostics must not enable production ownership")
assert(!diagnostics["runtime_live_owner_gate"]["owner_transition_ready"], "runtime daemon diagnostics must not enable owner transition")
assert(!diagnostics["runtime_live_owner_gate"]["smoke_adapter_is_production_owner"], "runtime daemon diagnostics must not treat smoke adapter as production owner")
assert(diagnostics["runtime_owner_smoke_plan"]["plan_type"] == "runtime-owner-smoke-plan", "runtime daemon diagnostics must include Runtime owner smoke plans")
assert(diagnostics["runtime_owner_smoke_plan"]["smoke_state"] == "planned", "runtime daemon diagnostics must keep owner smoke planned")
assert(diagnostics["runtime_owner_smoke_plan"]["pending_step_count"] == 6, "runtime daemon diagnostics must count pending owner smoke steps")
assert(!diagnostics["runtime_owner_smoke_plan"]["system_service_started"], "runtime daemon diagnostics must not start system services")
assert(!diagnostics["runtime_owner_smoke_plan"]["production_bus_claimed"], "runtime daemon diagnostics must not claim production bus ownership")
assert(diagnostics["runtime_method_parity_manifest"]["manifest_type"] == "runtime-method-parity-manifest", "runtime daemon diagnostics must include Runtime method parity manifests")
assert(diagnostics["runtime_method_parity_manifest"]["method_count"] == 51, "runtime daemon diagnostics must count read-only methods")
assert(diagnostics["execution_readiness"]["readiness_type"] == "compatibility-execution-readiness", "runtime daemon diagnostics must include execution readiness")
assert(!diagnostics["execution_readiness"]["launch_allowed"], "runtime daemon diagnostics must keep execution readiness launch gated")
assert(diagnostics["launch_intent"]["intent_type"] == "runtime-launch-intent", "runtime daemon diagnostics must include launch intent")
assert(diagnostics["launch_intent"]["runtime_method"] == "Launch", "runtime daemon diagnostics must route launch intent to Launch")
assert(diagnostics["launch_intent"]["read_method"] == "GetLaunchIntent", "runtime daemon diagnostics must expose launch intent read method")
assert(!diagnostics["launch_intent"]["launch_allowed"], "runtime daemon diagnostics must keep launch intent gated")
assert(!diagnostics["launch_intent"]["launch_enabled"], "runtime daemon diagnostics must not enable launch intent execution")
assert(!diagnostics["launch_intent"]["execution_request_created"], "runtime daemon diagnostics must not create launch request objects")
assert(diagnostics["portal_request_plan"]["request_type"] == "portal-request", "runtime daemon diagnostics must summarize Portal request plans")
assert(!diagnostics["portal_request_plan"]["host_permission_changed"], "runtime daemon diagnostics must not report host permission changes")
assert(diagnostics["desktop_activation_manifest"]["artifact_count"] == 7, "runtime daemon diagnostics must summarize desktop activation manifests")
assert(diagnostics["desktop_entry_plan"]["plan_type"] == "desktop-entry-plan", "runtime daemon diagnostics must include desktop entry plans")
assert(diagnostics["desktop_entry_plan"]["standard_desktop_entry"], "runtime daemon diagnostics must expose standard desktop entry status")
assert(diagnostics["desktop_entry_plan"]["launch_uses_runtime"], "runtime daemon diagnostics must expose Runtime launcher usage")
assert(!diagnostics["desktop_entry_plan"]["backend_command_exposed"], "runtime daemon diagnostics must not expose backend commands")
assert(!diagnostics["desktop_entry_plan"]["raw_windows_executable_exposed"], "runtime daemon diagnostics must not expose raw Windows executables")
assert(!diagnostics["desktop_entry_plan"]["compatibility_storage_path_exposed"], "runtime daemon diagnostics must not expose prefix paths")
assert(diagnostics["task_manager_identity_plan"]["plan_type"] == "task-manager-identity-plan", "runtime daemon diagnostics must include task manager identity plans")
assert(diagnostics["task_manager_identity_plan"]["desktop_file"] == "xnix-org.xnix.sample.notepad.desktop", "runtime daemon diagnostics must summarize task manager desktop files")
assert(diagnostics["task_manager_identity_plan"]["class_group"] == "xnix-compatibility", "runtime daemon diagnostics must summarize task manager class groups")
assert(diagnostics["task_manager_identity_plan"]["grouping_key"] == "org.xnix.sample.notepad", "runtime daemon diagnostics must summarize task manager grouping keys")
assert(diagnostics["task_manager_identity_plan"]["pinning_allowed"], "runtime daemon diagnostics must expose task manager pinning")
assert(diagnostics["task_manager_identity_plan"]["restore_allowed"], "runtime daemon diagnostics must expose task manager restore")
assert(!diagnostics["task_manager_identity_plan"]["skip_taskbar"], "runtime daemon diagnostics must keep taskbar visibility")
assert(diagnostics["task_manager_identity_plan"]["show_in_switcher"], "runtime daemon diagnostics must keep switcher visibility")
assert(diagnostics["task_manager_identity_plan"]["window_manager_policy_only"], "runtime daemon diagnostics must constrain task manager identity to window-manager policy")
assert(!diagnostics["task_manager_identity_plan"]["backend_details_exposed"], "runtime daemon diagnostics must not expose task manager backend details")
assert(diagnostics["file_association_plan"]["plan_type"] == "file-association-plan", "runtime daemon diagnostics must include file association plans")
assert(diagnostics["file_association_plan"]["desktop_file"] == "xnix-org.xnix.sample.notepad.desktop", "runtime daemon diagnostics must summarize file association desktop files")
assert(diagnostics["file_association_plan"]["mimeapps_path"] == "usr/share/applications/mimeapps.list", "runtime daemon diagnostics must summarize mimeapps paths")
assert(diagnostics["file_association_plan"]["association_count"] == 2, "runtime daemon diagnostics must count file associations")
assert(diagnostics["file_association_plan"]["standard_mimeapps_list"], "runtime daemon diagnostics must expose standard mimeapps status")
assert(diagnostics["file_association_plan"]["staged_root_only"], "runtime daemon diagnostics must keep file associations staged")
assert(!diagnostics["file_association_plan"]["overwrite_existing_mimeapps"], "runtime daemon diagnostics must not overwrite mimeapps")
assert(diagnostics["file_association_plan"]["portal_required_for_file_open"], "runtime daemon diagnostics must require portals for file opens")
assert(!diagnostics["file_association_plan"]["backend_details_exposed"], "runtime daemon diagnostics must not expose file association backend details")
assert(diagnostics["notification_plan"]["plan_type"] == "notification-plan", "runtime daemon diagnostics must include notification plans")
assert(diagnostics["notification_plan"]["event_type"] == "approval-required", "runtime daemon diagnostics must summarize notification events")
assert(diagnostics["notification_plan"]["urgency"] == "critical", "runtime daemon diagnostics must summarize notification urgency")
assert(diagnostics["notification_plan"]["action_count"] == 2, "runtime daemon diagnostics must count notification actions")
assert(diagnostics["notification_plan"]["requires_user_review"], "runtime daemon diagnostics must expose notification review requirements")
assert(!diagnostics["notification_plan"]["action_execution_enabled"], "runtime daemon diagnostics must keep notification actions disabled")
assert(!diagnostics["notification_plan"]["repair_execution_enabled"], "runtime daemon diagnostics must keep notification repairs disabled")
assert(!diagnostics["notification_plan"]["settings_persistence_enabled"], "runtime daemon diagnostics must keep notification settings persistence disabled")
assert(!diagnostics["notification_plan"]["backend_details_exposed"], "runtime daemon diagnostics must not expose notification backend details")
assert(diagnostics["tray_status"]["status_type"] == "tray-status-plan", "runtime daemon diagnostics must include tray status plans")
assert(diagnostics["tray_status"]["active_application_count"] == 1, "runtime daemon diagnostics must summarize tray active counts")
assert(diagnostics["tray_status"]["attention_required_count"] == 1, "runtime daemon diagnostics must summarize tray attention counts")
assert(diagnostics["tray_status"]["compatibility_state"] == "attention-required", "runtime daemon diagnostics must summarize tray compatibility state")
assert(diagnostics["tray_status"]["tray_bridge_state"] == "idle", "runtime daemon diagnostics must summarize tray bridge state")
assert(diagnostics["tray_status"]["bridged_tray_application_count"] == 0, "runtime daemon diagnostics must count bridged tray applications")
assert(!diagnostics["tray_status"]["live_backend_bridge_enabled"], "runtime daemon diagnostics must keep live tray bridges disabled")
assert(!diagnostics["tray_status"]["bridge_configuration_persisted"], "runtime daemon diagnostics must keep tray persistence disabled")
assert(!diagnostics["tray_status"]["backend_details_exposed"], "runtime daemon diagnostics must not expose tray backend details")
assert(diagnostics["runtime_method_parity_manifest"]["read_only_method_parity_ready"], "runtime daemon diagnostics must report read-only parity readiness")
assert(!diagnostics["runtime_method_parity_manifest"]["write_methods_supported"], "runtime daemon diagnostics must not claim write method support")
assert(!diagnostics["runtime_method_parity_manifest"]["write_method_dispatch_enabled"], "runtime daemon diagnostics must not enable write method dispatch")
assert(diagnostics["runtime_write_gate"]["gate_type"] == "runtime-write-gate", "runtime daemon diagnostics must include Runtime write gates")
assert(diagnostics["runtime_write_gate"]["method_name"] == "Launch", "runtime daemon diagnostics must summarize launch write gates")
assert(diagnostics["runtime_write_gate"]["gate_decision"] == "blocked-until-production-backend", "runtime daemon diagnostics must block write gates")
assert(!diagnostics["runtime_write_gate"]["write_method_enabled"], "runtime daemon diagnostics must not enable write gates")
assert(!diagnostics["runtime_write_gate"]["dispatch_enabled"], "runtime daemon diagnostics must not enable write dispatch")
assert(!diagnostics["runtime_write_gate"]["request_object_created"], "runtime daemon diagnostics must not create write request objects")
assert(diagnostics["runtime_service_binding"]["binding_type"] == "runtime-service-binding", "runtime daemon diagnostics must include Runtime service binding status")
assert(diagnostics["runtime_service_binding"]["activation_binding_ready"], "runtime daemon diagnostics must expose activation binding readiness")
assert(!diagnostics["runtime_service_binding"]["live_dbus_owner_ready"], "runtime daemon diagnostics must not claim live D-Bus ownership")
assert(diagnostics["settings"]["request_type"] == "settings-model", "runtime daemon diagnostics must include compatibility settings")
assert(diagnostics["settings"]["settings_state"] == "planned", "runtime daemon diagnostics must expose settings state")
assert(!diagnostics["settings"]["settings_persisted"], "runtime daemon diagnostics must not claim settings persistence")
assert(!diagnostics["settings"]["host_root_modified"], "runtime daemon diagnostics must not mutate host root for settings")
assert(diagnostics["settings_change_plan"]["plan_type"] == "settings-change-plan", "runtime daemon diagnostics must include settings change planning")
assert(diagnostics["settings_change_plan"]["change_state"] == "planned", "runtime daemon diagnostics must expose settings change plan state")
assert(!diagnostics["settings_change_plan"]["apply_enabled"], "runtime daemon diagnostics must not enable settings changes yet")
assert(!diagnostics["settings_change_plan"]["settings_persisted"], "runtime daemon diagnostics must not persist planned settings changes")
assert(diagnostics["compatibility_mode_switch_plan"]["plan_type"] == "compatibility-mode-switch-plan", "runtime daemon diagnostics must include compatibility mode switch planning")
assert(diagnostics["compatibility_mode_switch_plan"]["runtime_method"] == "GetCompatibilityModeSwitchPlan", "runtime daemon diagnostics must expose compatibility mode switch Runtime methods")
assert(diagnostics["compatibility_mode_switch_plan"]["mode_state"] == "planned", "runtime daemon diagnostics must keep compatibility mode switches planned")
assert(diagnostics["compatibility_mode_switch_plan"]["mode_count"] == 4, "runtime daemon diagnostics must expose compatibility mode counts")
assert(!diagnostics["compatibility_mode_switch_plan"]["settings_persistence_enabled"], "runtime daemon diagnostics must not persist compatibility mode switches")
assert(!diagnostics["compatibility_mode_switch_plan"]["backend_reconfiguration_enabled"], "runtime daemon diagnostics must not reconfigure backends from compatibility mode switches")
assert(!diagnostics["compatibility_mode_switch_plan"]["backend_process_started"], "runtime daemon diagnostics must not start backend processes from compatibility mode switches")
assert(diagnostics["compatibility_permission_review_plan"]["plan_type"] == "compatibility-permission-review-plan", "runtime daemon diagnostics must include compatibility permission review planning")
assert(diagnostics["compatibility_permission_review_plan"]["runtime_method"] == "GetCompatibilityPermissionReviewPlan", "runtime daemon diagnostics must expose compatibility permission review Runtime methods")
assert(diagnostics["compatibility_permission_review_plan"]["review_state"] == "planned", "runtime daemon diagnostics must keep permission reviews planned")
assert(diagnostics["compatibility_permission_review_plan"]["permission_count"] == 7, "runtime daemon diagnostics must expose permission counts")
assert(!diagnostics["compatibility_permission_review_plan"]["permissions_granted"], "runtime daemon diagnostics must not grant permissions")
assert(!diagnostics["compatibility_permission_review_plan"]["settings_persisted"], "runtime daemon diagnostics must not persist permission settings")
assert(!diagnostics["compatibility_permission_review_plan"]["host_permission_changed"], "runtime daemon diagnostics must not change host permissions")
assert(diagnostics["compatibility_review_flow_plan"]["plan_type"] == "compatibility-review-flow-plan", "runtime daemon diagnostics must include compatibility review flow planning")
assert(diagnostics["compatibility_review_flow_plan"]["runtime_method"] == "GetCompatibilityReviewFlowPlan", "runtime daemon diagnostics must expose compatibility review flow Runtime methods")
assert(diagnostics["compatibility_review_flow_plan"]["review_state"] == "planned", "runtime daemon diagnostics must keep review flows planned")
assert(diagnostics["compatibility_review_flow_plan"]["step_count"] == 5, "runtime daemon diagnostics must expose review flow step counts")
assert(!diagnostics["compatibility_review_flow_plan"]["apply_enabled"], "runtime daemon diagnostics must not apply review flows")
assert(!diagnostics["compatibility_review_flow_plan"]["request_object_created"], "runtime daemon diagnostics must not create review flow request objects")
assert(!diagnostics["compatibility_review_flow_plan"]["permission_granted"], "runtime daemon diagnostics must not grant review flow permissions")
assert(!diagnostics["compatibility_review_flow_plan"]["settings_persisted"], "runtime daemon diagnostics must not persist review flow settings")
assert(!diagnostics["compatibility_review_flow_plan"]["execution_started"], "runtime daemon diagnostics must not start execution from review flows")
assert(!diagnostics["compatibility_review_flow_plan"]["host_root_modified"], "runtime daemon diagnostics must not mutate the host root from review flows")
assert(diagnostics["repair_plan"]["plan_type"] == "compatibility-repair", "runtime daemon diagnostics must include repair planning")
assert(diagnostics["repair_plan"]["issue"] == "engine-binding-pending", "runtime daemon diagnostics must identify the pending repair issue")
assert(diagnostics["repair_plan"]["snapshot_required"], "runtime daemon diagnostics repair plan must require snapshots")
assert(diagnostics["repair_plan"]["snapshot_plan"]["plan_type"] == "compatibility-snapshot", "runtime daemon diagnostics must include snapshot planning")
assert(diagnostics["repair_plan"]["snapshot_plan"]["restore_available"], "runtime daemon diagnostics snapshot plan must expose restore availability")

diagnostics_json = JSON.pretty_generate(diagnostics)
assert(!diagnostics_json.match?(/wine|prefix|\.wine|proton|virtual machine/i), "runtime diagnostics must not expose backend implementation terms")

_stdout, stderr, status = Open3.capture3(*command, "diagnostics", "org.xnix.missing")
assert(!status.success?, "runtime daemon must reject unknown applications")
assert(stderr.include?("unknown application"), "runtime daemon must explain unknown applications")

stdout, stderr, status = Open3.capture3(*command, "test-plan", "org.xnix.sample.notepad")
assert(status.success?, "runtime daemon test-plan must exit successfully: #{stderr}")
test_plan = JSON.parse(stdout)
assert(test_plan["plan_type"] == "compatibility-test", "runtime daemon test-plan command must emit a test plan")
assert(test_plan["steps"].any? { |step| step["id"] == "portal-preflight" }, "runtime daemon test-plan must include Portal preflight")

stdout, stderr, status = Open3.capture3(*command, "test-result", "org.xnix.sample.notepad")
assert(status.success?, "runtime daemon test-result must exit successfully: #{stderr}")
test_result = JSON.parse(stdout)
assert(test_result["result_type"] == "compatibility-test-result", "runtime daemon test-result command must emit a test result")
assert(test_result["overall_status"] == "pending", "runtime daemon test-result must expose pending status")

stdout, stderr, status = Open3.capture3(*command, "execution-readiness", "org.xnix.sample.notepad")
assert(status.success?, "runtime daemon execution-readiness must exit successfully: #{stderr}")
execution_readiness = JSON.parse(stdout)
assert(execution_readiness["readiness_type"] == "compatibility-execution-readiness", "runtime daemon execution-readiness command must emit execution readiness")
assert(!execution_readiness["launch_allowed"], "runtime daemon execution-readiness command must keep launch gated")

stdout, stderr, status = Open3.capture3(*command, "launch-intent", "org.xnix.sample.notepad")
assert(status.success?, "runtime daemon launch-intent must exit successfully: #{stderr}")
launch_intent = JSON.parse(stdout)
assert(launch_intent["intent_type"] == "runtime-launch-intent", "runtime daemon launch-intent command must emit launch intent")
assert(launch_intent["read_method"] == "GetLaunchIntent", "runtime daemon launch-intent command must expose the read method")
assert(!launch_intent["execution_started"], "runtime daemon launch-intent command must not start execution")

stdout, stderr, status = Open3.capture3(*command, "action-queue", "org.xnix.sample.notepad")
assert(status.success?, "runtime daemon action-queue must exit successfully: #{stderr}")
action_queue = JSON.parse(stdout)
assert(action_queue["queue_type"] == "compatibility-center-action-queue", "runtime daemon action-queue command must emit an action queue")
assert(action_queue["action_count"] == 5, "runtime daemon action-queue command must count actions")
assert(!action_queue["execution_enabled"], "runtime daemon action-queue command must not enable execution")

stdout, stderr, status = Open3.capture3(*command, "action-review", "org.xnix.sample.notepad", "review-ai-repair", "approved")
assert(status.success?, "runtime daemon action-review must exit successfully: #{stderr}")
action_review = JSON.parse(stdout)
assert(action_review["receipt_type"] == "compatibility-center-action-review-receipt", "runtime daemon action-review command must emit a receipt")
assert(action_review["decision_recorded"], "runtime daemon action-review command must record review intent")
assert(!action_review["execution_enabled"], "runtime daemon action-review command must not enable execution")

stdout, stderr, status = Open3.capture3(*command, "krunner-query-plan", "notepad")
assert(status.success?, "runtime daemon krunner-query-plan must exit successfully: #{stderr}")
krunner_query = JSON.parse(stdout)
assert(krunner_query["query_type"] == "krunner-query-plan", "runtime daemon krunner-query-plan command must emit a query plan")
assert(krunner_query["entry_point"] == "krunner", "runtime daemon krunner-query-plan must identify KRunner")
assert(krunner_query["matches"].first["application_id"] == "org.xnix.sample.notepad", "runtime daemon krunner-query-plan must resolve the sample application")
assert(krunner_query["matches"].first["action"]["argv"] == ["xnix-compat-launch", "--app", "org.xnix.sample.notepad"], "runtime daemon krunner-query-plan must use the managed launcher")
assert(!krunner_query["summary"]["query_execution_enabled"], "runtime daemon krunner-query-plan must not enable direct execution")
assert(!krunner_query["summary"]["backend_launch_enabled"], "runtime daemon krunner-query-plan must not enable backend launch")
assert(!krunner_query["backend_details_exposed"], "runtime daemon krunner-query-plan must hide backend details")

stdout, stderr, status = Open3.capture3(*command, "kde-integration-status")
assert(status.success?, "runtime daemon kde-integration-status must exit successfully: #{stderr}")
kde_status = JSON.parse(stdout)
assert(kde_status["status_type"] == "kde-integration-status", "runtime daemon kde-integration-status command must emit a status")
assert(kde_status["entry_point_count"] == 7, "runtime daemon kde-integration-status must count seven entry points")
assert(kde_status["entry_points"].all? { |entry| entry.fetch("runtime_backed") }, "runtime daemon kde-integration-status must keep entry points Runtime-backed")
assert(kde_status["entry_points"].all? { |entry| entry.fetch("c_runtime_backed") }, "runtime daemon kde-integration-status must keep entry points C Runtime-backed")
assert(kde_status["entry_points"].none? { |entry| entry.fetch("kde_policy_owner") }, "runtime daemon kde-integration-status must not make KDE the policy owner")
assert(!kde_status["backend_details_exposed"], "runtime daemon kde-integration-status must hide backend details")

stdout, stderr, status = Open3.capture3(*command, "kwin-window-rule-plan", "org.xnix.sample.notepad")
assert(status.success?, "runtime daemon kwin-window-rule-plan must exit successfully: #{stderr}")
kwin_rule = JSON.parse(stdout)
assert(kwin_rule["request_type"] == "kwin-window-rule", "runtime daemon kwin-window-rule-plan command must emit a KWin plan")
assert(kwin_rule["match"]["resource_name"] == "org.xnix.sample.notepad", "runtime daemon kwin-window-rule-plan must preserve Runtime identity")
assert(kwin_rule["set"]["desktop_file"] == "xnix-org.xnix.sample.notepad.desktop", "runtime daemon kwin-window-rule-plan must bind generated desktop files")
assert(!kwin_rule["set"]["skip_taskbar"], "runtime daemon kwin-window-rule-plan must keep taskbar visibility")
assert(kwin_rule["restore"]["prefer_existing_window"], "runtime daemon kwin-window-rule-plan must prefer restoring existing windows")
assert(!kwin_rule["safety"]["backend_details_exposed"], "runtime daemon kwin-window-rule-plan must hide backend details")

stdout, stderr, status = Open3.capture3(*command, "compatibility-center-summary", "org.xnix.sample.notepad")
assert(status.success?, "runtime daemon compatibility-center-summary must exit successfully: #{stderr}")
compatibility_center_summary = JSON.parse(stdout)
assert(compatibility_center_summary["summary_type"] == "compatibility-center-summary", "runtime daemon compatibility-center-summary command must emit a summary")
assert(compatibility_center_summary["compatibility"]["known_issue_count"] == 1, "runtime daemon compatibility-center-summary must count known issues")
assert(compatibility_center_summary["repair_records"]["state"] == "pending-review", "runtime daemon compatibility-center-summary must expose repair state")
assert(compatibility_center_summary["actions"].include?("run-preflight-test"), "runtime daemon compatibility-center-summary must expose review actions")
assert(!compatibility_center_summary["safety"]["backend_launch_enabled"], "runtime daemon compatibility-center-summary must keep backend launch disabled")
assert(!compatibility_center_summary["backend_details_exposed"], "runtime daemon compatibility-center-summary must hide backend details")

stdout, stderr, status = Open3.capture3(*command, "backend-binding", "org.xnix.sample.notepad")
assert(status.success?, "runtime daemon backend-binding must exit successfully: #{stderr}")
backend_binding = JSON.parse(stdout)
assert(backend_binding["binding_type"] == "compatibility-backend-binding", "runtime daemon backend-binding command must emit a backend binding")
assert(!backend_binding["managed_binding_ready"], "runtime daemon backend-binding must not claim readiness")

stdout, stderr, status = Open3.capture3(*command, "backend-capability-matrix")
assert(status.success?, "runtime daemon backend-capability-matrix must exit successfully: #{stderr}")
backend_capability_matrix = JSON.parse(stdout)
assert(backend_capability_matrix["matrix_type"] == "compatibility-backend-capability-matrix", "runtime daemon backend-capability-matrix command must emit a matrix")
assert(backend_capability_matrix["profile_count"] == 2, "runtime daemon backend-capability-matrix must expose profile counts")
assert(backend_capability_matrix["capability_count"] == 7, "runtime daemon backend-capability-matrix must expose capability counts")
assert(!backend_capability_matrix["selection_enabled"], "runtime daemon backend-capability-matrix must not enable selection")
assert(!backend_capability_matrix["backend_launch_enabled"], "runtime daemon backend-capability-matrix must not enable launch")
assert(!backend_capability_matrix["capability_activation_enabled"], "runtime daemon backend-capability-matrix must not enable activation")

stdout, stderr, status = Open3.capture3(*command, "backend-selection-plan", "org.xnix.sample.notepad")
assert(status.success?, "runtime daemon backend-selection-plan must exit successfully: #{stderr}")
backend_selection_plan = JSON.parse(stdout)
assert(backend_selection_plan["plan_type"] == "compatibility-backend-selection-plan", "runtime daemon backend-selection-plan command must emit a backend selection plan")
assert(backend_selection_plan["candidate_count"] == 2, "runtime daemon backend-selection-plan must expose candidate counts")
assert(!backend_selection_plan["selection_committed"], "runtime daemon backend-selection-plan must not commit selection")
assert(!backend_selection_plan["selection_change_enabled"], "runtime daemon backend-selection-plan must not enable selection changes")

stdout, stderr, status = Open3.capture3(*command, "backend-environment-plan", "org.xnix.sample.notepad")
assert(status.success?, "runtime daemon backend-environment-plan must exit successfully: #{stderr}")
backend_environment_plan = JSON.parse(stdout)
assert(backend_environment_plan["plan_type"] == "compatibility-backend-environment-plan", "runtime daemon backend-environment-plan command must emit a backend environment plan")
assert(!backend_environment_plan["environment_created"], "runtime daemon backend-environment-plan must not claim environment creation")

stdout, stderr, status = Open3.capture3(*command, "kde-application-surface-plan", "org.xnix.sample.notepad")
assert(status.success?, "runtime daemon kde-application-surface-plan must exit successfully: #{stderr}")
kde_application_surface_plan = JSON.parse(stdout)
assert(kde_application_surface_plan["plan_type"] == "kde-application-surface-plan", "runtime daemon kde-application-surface-plan command must emit a KDE surface plan")
assert(kde_application_surface_plan["normal_linux_application_surface"], "runtime daemon KDE surface plan must keep normal Linux app presentation")
assert(!kde_application_surface_plan["backend_details_exposed"], "runtime daemon KDE surface plan must hide backend details")

stdout, stderr, status = Open3.capture3(*command, "desktop-resource-bridge-plan", "org.xnix.sample.notepad")
assert(status.success?, "runtime daemon desktop-resource-bridge-plan must exit successfully: #{stderr}")
desktop_resource_bridge_plan = JSON.parse(stdout)
assert(desktop_resource_bridge_plan["plan_type"] == "desktop-resource-bridge-plan", "runtime daemon desktop-resource-bridge-plan command must emit a desktop resource bridge plan")
assert(desktop_resource_bridge_plan["portal_mediated"], "runtime daemon desktop resource bridge plan must keep Portal mediation")
assert(!desktop_resource_bridge_plan["bridges_enabled"], "runtime daemon desktop resource bridge plan must not enable bridges")

stdout, stderr, status = Open3.capture3(*command, "backend-lifecycle", "org.xnix.sample.notepad")
assert(status.success?, "runtime daemon backend-lifecycle must exit successfully: #{stderr}")
backend_lifecycle = JSON.parse(stdout)
assert(backend_lifecycle["lifecycle_type"] == "compatibility-backend-lifecycle", "runtime daemon backend-lifecycle command must emit a backend lifecycle")
assert(!backend_lifecycle["backend_process_started"], "runtime daemon backend-lifecycle must not claim backend process starts")

stdout, stderr, status = Open3.capture3(*command, "state-root", "org.xnix.sample.notepad")
assert(status.success?, "runtime daemon state-root must exit successfully: #{stderr}")
state_root = JSON.parse(stdout)
assert(state_root["root_type"] == "compatibility-application-state-root", "runtime daemon state-root command must emit a state root")
assert(state_root["allocation_state"] == "planned", "runtime daemon state-root must not claim allocation")

stdout, stderr, status = Open3.capture3(*command, "package-source", "org.xnix.sample.notepad")
assert(status.success?, "runtime daemon package-source must exit successfully: #{stderr}")
package_source = JSON.parse(stdout)
assert(package_source["source_type"] == "compatibility-package-source", "runtime daemon package-source command must emit a package source")
assert(!package_source["install_enabled"], "runtime daemon package-source must not enable installation")

stdout, stderr, status = Open3.capture3(*command, "acquisition-preflight", "org.xnix.sample.notepad")
assert(status.success?, "runtime daemon acquisition-preflight must exit successfully: #{stderr}")
acquisition_preflight = JSON.parse(stdout)
assert(acquisition_preflight["preflight_type"] == "compatibility-acquisition-preflight", "runtime daemon acquisition-preflight command must emit acquisition preflight")
assert(!acquisition_preflight["download_enabled"], "runtime daemon acquisition-preflight must not enable downloads")

stdout, stderr, status = Open3.capture3(*command, "artifact-manifest", "org.xnix.sample.notepad")
assert(status.success?, "runtime daemon artifact-manifest must exit successfully: #{stderr}")
artifact_manifest = JSON.parse(stdout)
assert(artifact_manifest["manifest_type"] == "compatibility-artifact-manifest", "runtime daemon artifact-manifest command must emit artifact manifest")
assert(!artifact_manifest["download_enabled"], "runtime daemon artifact-manifest must not enable downloads")

stdout, stderr, status = Open3.capture3(*command, "install-plan", "org.xnix.sample.notepad")
assert(status.success?, "runtime daemon install-plan must exit successfully: #{stderr}")
install_plan = JSON.parse(stdout)
assert(install_plan["plan_type"] == "compatibility-install-plan", "runtime daemon install-plan command must emit install plan")
assert(!install_plan["download_enabled"], "runtime daemon install-plan must not enable downloads")
assert(!install_plan["install_enabled"], "runtime daemon install-plan must not enable installation")

stdout, stderr, status = Open3.capture3(*command, "ai-diagnostic-input", "org.xnix.sample.notepad")
assert(status.success?, "runtime daemon ai-diagnostic-input must exit successfully: #{stderr}")
ai_input = JSON.parse(stdout)
assert(ai_input["input_type"] == "ai-diagnostic-input", "runtime daemon ai-diagnostic-input command must emit an AI diagnostic input")
assert(ai_input["safe_for_ai_diagnostics"], "runtime daemon ai-diagnostic-input must be safe for AI diagnostics")

stdout, stderr, status = Open3.capture3(*command, "ai-diagnostic-recommendation", "org.xnix.sample.notepad")
assert(status.success?, "runtime daemon ai-diagnostic-recommendation must exit successfully: #{stderr}")
ai_recommendation = JSON.parse(stdout)
assert(ai_recommendation["recommendation_type"] == "ai-diagnostic-recommendation", "runtime daemon ai-diagnostic-recommendation command must emit recommendations")
assert(ai_recommendation["recommendations"].length == 3, "runtime daemon ai-diagnostic-recommendation must expose recommendations")

stdout, stderr, status = Open3.capture3(*command, "ai-repair-approval-gate", "org.xnix.sample.notepad")
assert(status.success?, "runtime daemon ai-repair-approval-gate must exit successfully: #{stderr}")
ai_gate = JSON.parse(stdout)
assert(ai_gate["gate_type"] == "ai-repair-approval-gate", "runtime daemon ai-repair-approval-gate command must emit a gate")
assert(ai_gate["gate_decision"] == "blocked-until-approval", "runtime daemon ai-repair-approval-gate must block until approval")

stdout, stderr, status = Open3.capture3(*command, "service-binding")
assert(status.success?, "runtime daemon service-binding must exit successfully: #{stderr}")
service_binding = JSON.parse(stdout)
assert(service_binding["binding_type"] == "runtime-service-binding", "runtime daemon service-binding command must emit service binding")
assert(service_binding["activation_binding_ready"], "runtime daemon service-binding must report activation readiness")

stdout, stderr, status = Open3.capture3(*command, "live-owner-gate")
assert(status.success?, "runtime daemon live-owner-gate must exit successfully: #{stderr}")
live_owner_gate = JSON.parse(stdout)
assert(live_owner_gate["gate_type"] == "runtime-live-owner-gate", "runtime daemon live-owner-gate command must emit a live owner gate")
assert(!live_owner_gate["production_owner_enabled"], "runtime daemon live-owner-gate must not enable production ownership")
assert(!live_owner_gate["owner_transition_ready"], "runtime daemon live-owner-gate must not enable owner transition")
assert(!live_owner_gate["smoke_adapter_is_production_owner"], "runtime daemon live-owner-gate must not treat the smoke adapter as production owner")

stdout, stderr, status = Open3.capture3(*command, "owner-smoke-plan")
assert(status.success?, "runtime daemon owner-smoke-plan must exit successfully: #{stderr}")
owner_smoke_plan = JSON.parse(stdout)
assert(owner_smoke_plan["plan_type"] == "runtime-owner-smoke-plan", "runtime daemon owner-smoke-plan command must emit a smoke plan")
assert(owner_smoke_plan["smoke_state"] == "planned", "runtime daemon owner-smoke-plan must stay planned")
assert(!owner_smoke_plan["system_service_started"], "runtime daemon owner-smoke-plan must not start a system service")
assert(!owner_smoke_plan["production_bus_claimed"], "runtime daemon owner-smoke-plan must not claim production bus ownership")

stdout, stderr, status = Open3.capture3(*command, "method-parity")
assert(status.success?, "runtime daemon method-parity must exit successfully: #{stderr}")
method_parity = JSON.parse(stdout)
assert(method_parity["manifest_type"] == "runtime-method-parity-manifest", "runtime daemon method-parity command must emit a manifest")
assert(method_parity["read_only_method_parity_ready"], "runtime daemon method-parity must report read-only parity readiness")
assert(!method_parity["write_methods_supported"], "runtime daemon method-parity must not claim write method support")

stdout, stderr, status = Open3.capture3(*command, "write-gate", "Launch")
assert(status.success?, "runtime daemon write-gate must exit successfully: #{stderr}")
write_gate = JSON.parse(stdout)
assert(write_gate["gate_type"] == "runtime-write-gate", "runtime daemon write-gate command must emit a write gate")
assert(write_gate["method_name"] == "Launch", "runtime daemon write-gate command must preserve the method name")
assert(write_gate["gate_decision"] == "blocked-until-production-backend", "runtime daemon write-gate must block production writes")
assert(!write_gate["write_method_enabled"], "runtime daemon write-gate must not enable write methods")

stdout, stderr, status = Open3.capture3(*command, "settings", "org.xnix.sample.notepad")
assert(status.success?, "runtime daemon settings must exit successfully: #{stderr}")
settings = JSON.parse(stdout)
assert(settings["request_type"] == "settings-model", "runtime daemon settings command must emit settings model")
assert(settings["runtime_owned"], "runtime daemon settings command must expose Runtime ownership")

stdout, stderr, status = Open3.capture3(*command, "settings-change", "org.xnix.sample.notepad", "resource-access", "documents", "ask")
assert(status.success?, "runtime daemon settings-change must exit successfully: #{stderr}")
settings_change = JSON.parse(stdout)
assert(settings_change["plan_type"] == "settings-change-plan", "runtime daemon settings-change command must emit a settings change plan")
assert(settings_change["change_state"] == "planned", "runtime daemon settings-change command must expose planned changes")
assert(!settings_change["apply_enabled"], "runtime daemon settings-change command must not enable application yet")
assert(!settings_change["settings_persisted"], "runtime daemon settings-change command must not persist settings yet")

stdout, stderr, status = Open3.capture3(*command, "mode-switch-plan", "org.xnix.sample.notepad", "prefer-performance")
assert(status.success?, "runtime daemon mode-switch-plan must exit successfully: #{stderr}")
mode_switch = JSON.parse(stdout)
assert(mode_switch["plan_type"] == "compatibility-mode-switch-plan", "runtime daemon mode-switch-plan command must emit a compatibility mode switch plan")
assert(mode_switch["requested_mode"] == "prefer-performance", "runtime daemon mode-switch-plan command must preserve requested mode")
assert(!mode_switch["settings_persistence_enabled"], "runtime daemon mode-switch-plan command must not persist settings")
assert(!mode_switch["backend_process_started"], "runtime daemon mode-switch-plan command must not start backend processes")

stdout, stderr, status = Open3.capture3(*command, "permission-review-plan", "org.xnix.sample.notepad")
assert(status.success?, "runtime daemon permission-review-plan must exit successfully: #{stderr}")
permission_review = JSON.parse(stdout)
assert(permission_review["plan_type"] == "compatibility-permission-review-plan", "runtime daemon permission-review-plan command must emit a compatibility permission review plan")
assert(permission_review["permission_count"] == 7, "runtime daemon permission-review-plan command must preserve permission count")
assert(!permission_review["permissions_granted"], "runtime daemon permission-review-plan command must not grant permissions")

stdout, stderr, status = Open3.capture3(*command, "review-flow-plan", "org.xnix.sample.notepad")
assert(status.success?, "runtime daemon review-flow-plan must exit successfully: #{stderr}")
review_flow = JSON.parse(stdout)
assert(review_flow["plan_type"] == "compatibility-review-flow-plan", "runtime daemon review-flow-plan command must emit a compatibility review flow plan")
assert(review_flow["step_count"] == 5, "runtime daemon review-flow-plan command must preserve step count")
assert(!review_flow["apply_enabled"], "runtime daemon review-flow-plan command must not apply changes")
assert(!review_flow["permission_granted"], "runtime daemon review-flow-plan command must not grant permissions")
assert(!review_flow["settings_persisted"], "runtime daemon review-flow-plan command must not persist settings")
assert(!review_flow["execution_started"], "runtime daemon review-flow-plan command must not start execution")

puts "PASS: compatibility runtime daemon unit tests"
