#!/usr/bin/env ruby
# frozen_string_literal: true

require "json"
require "open3"
require "pathname"
require "tmpdir"

def assert(condition, message)
  return if condition

  warn "FAIL: #{message}"
  exit 1
end

project_root = Pathname.new(__dir__).join("..").realpath
core_source = project_root.join("runtime/core/xnix_runtime_core.c")
core_header = project_root.join("runtime/core/xnix_runtime_core.h")
core_cli = project_root.join("runtime/core/xnix_runtime_core_cli.c")

assert(core_header.read.include?("#define XNIX_RUNTIME_VERSION \"0.2.63\""), "C Runtime core must expose the current version")
assert(core_header.read.include?("XNIX_RUNTIME_WRITE_ERROR"), "C Runtime core must define the write-method D-Bus error")
assert(core_header.read.include?("XnixRuntimeApplication"), "C Runtime core must define application catalog records")
assert(core_header.read.include?("XnixRuntimeEngine"), "C Runtime core must define compatibility engine records")
assert(core_header.read.include?("XnixRuntimePortalPolicy"), "C Runtime core must define Portal access policy records")
assert(core_header.read.include?("XnixRuntimeSnapshotPolicy"), "C Runtime core must define snapshot policy records")
assert(core_header.read.include?("XnixRuntimeStateRootPolicy"), "C Runtime core must define state root policy records")
assert(core_header.read.include?("XnixRuntimeInstallReadinessPolicy"), "C Runtime core must define install readiness policy records")
assert(core_header.read.include?("XnixRuntimeArtifactManifestPolicy"), "C Runtime core must define artifact manifest policy records")
assert(core_source.read.include?("xnix_runtime_write_gate"), "C Runtime core must implement write gate logic")
assert(core_source.read.include?("blocked-until-production-backend"), "C Runtime core must keep write gates blocked")
assert(core_source.read.include?("xnix_runtime_find_application"), "C Runtime core must query application catalog records")
assert(core_source.read.include?("xnix_runtime_select_engine_for_mode"), "C Runtime core must select engine records by recipe mode")
assert(core_source.read.include?("xnix_runtime_find_portal_policy"), "C Runtime core must query Portal access policies")
assert(core_source.read.include?("xnix_runtime_find_snapshot_policy"), "C Runtime core must query snapshot policies")
assert(core_source.read.include?("xnix_runtime_find_state_root_policy"), "C Runtime core must query state root policies")
assert(core_source.read.include?("xnix_runtime_find_install_readiness_policy"), "C Runtime core must query install readiness policies")
assert(core_source.read.include?("xnix_runtime_find_artifact_manifest_policy"), "C Runtime core must query artifact manifest policies")
assert(core_cli.read.include?("business_logic_runtime"), "C Runtime core CLI must identify the business runtime language")
assert(core_cli.read.include?("list-applications"), "C Runtime core CLI must expose application catalog listing")
assert(core_cli.read.include?("list-engines"), "C Runtime core CLI must expose engine catalog listing")
assert(core_cli.read.include?("list-portal-policies"), "C Runtime core CLI must expose Portal policy listing")
assert(core_cli.read.include?("list-snapshot-policies"), "C Runtime core CLI must expose snapshot policy listing")
assert(core_cli.read.include?("list-state-root-policies"), "C Runtime core CLI must expose state root policy listing")
assert(core_cli.read.include?("list-install-readiness-policies"), "C Runtime core CLI must expose install readiness policy listing")
assert(core_cli.read.include?("list-artifact-manifest-policies"), "C Runtime core CLI must expose artifact manifest policy listing")

Dir.mktmpdir("xnix-runtime-core") do |dir|
  binary = Pathname.new(dir).join("xnix-runtime-core")
  _stdout, stderr, status = Open3.capture3(
    "cc",
    "-std=c11",
    "-Wall",
    "-Wextra",
    "-Werror",
    core_source.to_s,
    core_cli.to_s,
    "-o",
    binary.to_s
  )
  assert(status.success?, "C Runtime core must compile cleanly: #{stderr}")

  stdout, stderr, status = Open3.capture3(binary.to_s, "probe")
  assert(status.success?, "C Runtime core probe must exit successfully: #{stderr}")
  probe = JSON.parse(stdout)
  assert(probe["version"] == "0.2.63", "C Runtime core probe must expose the current version")
  assert(probe["core_language"] == "c", "C Runtime core must report C as its implementation language")
  assert(probe["business_logic_runtime"] == "c", "important Runtime business logic must be C-owned")
  assert(probe["ruby_role"] == "tests-and-development-tools", "Ruby must be limited to tests and development tooling")
  assert(probe["bus_name"] == "org.xnix.Compatibility1", "C Runtime core must keep the stable bus name")
  assert(probe["runtime_owned"], "C Runtime core must expose Runtime ownership")
  assert(!probe["kde_policy_owner"], "KDE must not own Runtime policy")
  assert(probe["application_catalog_owner"] == "c", "C Runtime core must own the first application catalog layer")
  assert(probe["application_count"] == 1, "C Runtime core must count registered applications")
  assert(probe["engine_catalog_owner"] == "c", "C Runtime core must own the first engine catalog layer")
  assert(probe["engine_count"] == 3, "C Runtime core must count registered engines")
  assert(probe["portal_policy_owner"] == "c", "C Runtime core must own the first Portal policy layer")
  assert(probe["portal_policy_count"] == 7, "C Runtime core must count registered Portal policies")
  assert(probe["snapshot_policy_owner"] == "c", "C Runtime core must own the first snapshot policy layer")
  assert(probe["snapshot_policy_count"] == 3, "C Runtime core must count registered snapshot policies")
  assert(probe["state_root_policy_owner"] == "c", "C Runtime core must own the first state root policy layer")
  assert(probe["state_root_policy_count"] == 1, "C Runtime core must count registered state root policies")
  assert(probe["install_readiness_policy_owner"] == "c", "C Runtime core must own the first install readiness layer")
  assert(probe["install_readiness_policy_count"] == 1, "C Runtime core must count registered install readiness policies")
  assert(probe["artifact_manifest_policy_owner"] == "c", "C Runtime core must own the first artifact manifest layer")
  assert(probe["artifact_manifest_policy_count"] == 1, "C Runtime core must count registered artifact manifest policies")
  assert(probe["write_methods"] == %w[InstallRecipe Launch CreateSnapshot RestoreSnapshot], "C Runtime core must list reserved write methods")
  assert(probe["write_method_count"] == 4, "C Runtime core must count write methods")
  assert(!probe["write_methods_supported"], "C Runtime core must not claim write method support")
  assert(!probe["write_method_dispatch_enabled"], "C Runtime core must not enable write dispatch")

  stdout, stderr, status = Open3.capture3(binary.to_s, "list-applications")
  assert(status.success?, "C Runtime core application list must exit successfully: #{stderr}")
  applications = JSON.parse(stdout)
  assert(applications.length == 1, "C Runtime core must list the sample application")
  application = applications.first
  assert(application["id"] == "org.xnix.sample.notepad", "C Runtime core must preserve the recipe id")
  assert(application["name"] == "Sample Notepad", "C Runtime core must preserve the recipe name")
  assert(application["icon"] == "accessories-text-editor", "C Runtime core must preserve the desktop icon")
  assert(application["runtime_mode"] == "automatic", "C Runtime core must preserve the runtime mode")
  assert(application["desktop_category"] == "Utility", "C Runtime core must expose a safe desktop category")
  assert(application["launcher_command"] == "xnix-compat-launch --app org.xnix.sample.notepad %U", "C Runtime core must expose the managed launcher")
  assert(application["primary_extension"] == ".txt", "C Runtime core must expose the primary file extension")
  assert(application["primary_mime_type"] == "application/x-xnix-txt", "C Runtime core must expose the primary MIME type")
  assert(application["runtime_owned"], "C Runtime core application catalog must be Runtime-owned")
  assert(!application["kde_policy_owner"], "C Runtime core application catalog must not make KDE the policy owner")
  assert(!application["backend_details_exposed"], "C Runtime core application catalog must hide backend details")
  assert(!stdout.match?(/wine|prefix|proton|virtual machine/i), "C Runtime core application catalog must not expose backend details")

  stdout, stderr, status = Open3.capture3(binary.to_s, "get-application", "org.xnix.sample.notepad")
  assert(status.success?, "C Runtime core application lookup must exit successfully: #{stderr}")
  found_application = JSON.parse(stdout)
  assert(found_application == application, "C Runtime core lookup must return the catalog record")

  _stdout, stderr, status = Open3.capture3(binary.to_s, "get-application", "org.xnix.unknown")
  assert(!status.success?, "C Runtime core must reject unknown application ids")
  assert(stderr.include?("not registered"), "C Runtime core must explain unknown application validation")

  stdout, stderr, status = Open3.capture3(binary.to_s, "list-engines")
  assert(status.success?, "C Runtime core engine catalog must exit successfully: #{stderr}")
  engine_catalog = JSON.parse(stdout)
  assert(engine_catalog["version"] == "0.2.63", "C Runtime core engine catalog must expose the current version")
  assert(engine_catalog["catalog_type"] == "compatibility-engine", "C Runtime core engine catalog must identify the catalog type")
  assert(engine_catalog["runtime_policy_owner"], "C Runtime core must own engine policy")
  assert(!engine_catalog["desktop_shell_policy_owner"], "C Runtime core must not make the desktop shell the engine policy owner")
  assert(engine_catalog["catalog_owner"] == "c", "C Runtime core engine catalog must be C-owned")
  assert(!engine_catalog["backend_details_exposed"], "C Runtime core engine catalog must hide backend details")
  assert(engine_catalog["engine_count"] == 3, "C Runtime core engine catalog must count engines")
  engines = engine_catalog.fetch("engines")
  assert(engines.map { |engine| engine.fetch("id") } == %w[automatic-managed local-compatibility-engine isolated-compatibility-engine], "C Runtime core must keep engine order stable")
  assert(engines.all? { |engine| !engine.fetch("ready") }, "C Runtime core must not claim engine readiness")
  assert(engines.all? { |engine| !engine.fetch("launch_enabled") }, "C Runtime core must not claim launch enablement")
  assert(engines.all? { |engine| engine.fetch("user_visible") }, "C Runtime core must expose engines as user-visible Runtime strategies")
  assert(engines.all? { |engine| !engine.fetch("backend_details_exposed") }, "C Runtime core engines must hide backend details")
  assert(!stdout.match?(/prefix|\.wine|proton|virtual machine/i), "C Runtime core engine catalog must not expose backend implementation terms")

  stdout, stderr, status = Open3.capture3(binary.to_s, "select-engine", "automatic")
  assert(status.success?, "C Runtime core automatic engine selection must exit successfully: #{stderr}")
  automatic = JSON.parse(stdout)
  assert(automatic["engine_id"] == "automatic-managed", "automatic mode must select the automatic-managed engine")
  assert(!automatic["launch_enabled"], "automatic mode must not enable launch yet")

  stdout, stderr, status = Open3.capture3(binary.to_s, "select-engine", "wine")
  assert(status.success?, "C Runtime core local engine selection must exit successfully: #{stderr}")
  local = JSON.parse(stdout)
  assert(local["engine_id"] == "local-compatibility-engine", "local recipe mode must select the local compatibility engine")
  assert(!local["backend_details_exposed"], "local engine selection must hide backend details")

  stdout, stderr, status = Open3.capture3(binary.to_s, "select-engine", "vm")
  assert(status.success?, "C Runtime core isolated engine selection must exit successfully: #{stderr}")
  isolated = JSON.parse(stdout)
  assert(isolated["engine_id"] == "isolated-compatibility-engine", "isolated recipe mode must select the isolated compatibility engine")

  _stdout, stderr, status = Open3.capture3(binary.to_s, "select-engine", "unknown")
  assert(!status.success?, "C Runtime core must reject unknown recipe modes")
  assert(stderr.include?("mode must be one of"), "C Runtime core must explain recipe mode validation")

  stdout, stderr, status = Open3.capture3(binary.to_s, "list-portal-policies")
  assert(status.success?, "C Runtime core Portal policy catalog must exit successfully: #{stderr}")
  portal_catalog = JSON.parse(stdout)
  assert(portal_catalog["version"] == "0.2.63", "C Runtime core Portal policy catalog must expose the current version")
  assert(portal_catalog["catalog_type"] == "portal-access-policy", "C Runtime core Portal policy catalog must identify the catalog type")
  assert(portal_catalog["runtime_policy_owner"], "C Runtime core must own Portal policy")
  assert(!portal_catalog["desktop_shell_policy_owner"], "C Runtime core must not make the desktop shell the Portal policy owner")
  assert(portal_catalog["catalog_owner"] == "c", "C Runtime core Portal policy catalog must be C-owned")
  assert(!portal_catalog["backend_details_exposed"], "C Runtime core Portal policy catalog must hide backend details")
  assert(portal_catalog["policy_count"] == 7, "C Runtime core Portal policy catalog must count policies")
  policies = portal_catalog.fetch("policies")
  assert(policies.map { |policy| policy.fetch("operation") } == %w[file-open uri-open print screenshot clipboard camera remote-desktop], "C Runtime core must keep Portal policy order stable")
  assert(policies.all? { |policy| policy.fetch("portal_required") }, "C Runtime core policies must require portals")
  assert(policies.all? { |policy| policy.fetch("user_mediation_required") }, "C Runtime core policies must require user mediation")
  assert(policies.all? { |policy| !policy.fetch("direct_access_allowed") }, "C Runtime core policies must deny direct desktop access")
  assert(policies.all? { |policy| policy.fetch("runtime_policy_owner") }, "C Runtime core policies must be Runtime-owned")
  assert(policies.all? { |policy| !policy.fetch("desktop_shell_policy_owner") }, "C Runtime core policies must not be KDE-owned")
  assert(policies.all? { |policy| !policy.fetch("backend_details_exposed") }, "C Runtime core policies must hide backend details")
  assert(!stdout.match?(/wine|prefix|\.wine|proton|virtual machine/i), "C Runtime core Portal policy catalog must not expose backend implementation terms")

  stdout, stderr, status = Open3.capture3(binary.to_s, "portal-policy", "org.xnix.sample.notepad", "file-open")
  assert(status.success?, "C Runtime core file Portal policy must exit successfully: #{stderr}")
  file_policy = JSON.parse(stdout)
  assert(file_policy["policy_type"] == "portal-access", "C Runtime core Portal policy must identify the policy type")
  assert(file_policy["desktop"] == "KDE Plasma", "C Runtime core Portal policy must target KDE Plasma")
  assert(file_policy["application_id"] == "org.xnix.sample.notepad", "C Runtime core Portal policy must preserve the application id")
  assert(file_policy["operation"] == "file-open", "C Runtime core Portal policy must preserve the operation")
  assert(file_policy["decision"] == "ask", "C Runtime core must ask for file access")
  assert(file_policy["portal_interface"] == "org.freedesktop.portal.FileChooser", "C Runtime core must select the file chooser Portal")
  assert(file_policy["resources"].include?("selected-files"), "C Runtime core must scope selected files")
  assert(file_policy["request_flow"]["dbus_api"] == "XDG Desktop Portal", "C Runtime core Portal policy must use XDG Desktop Portal")
  assert(file_policy["request_flow"]["runtime_policy_owner"], "C Runtime core Portal request flow must be Runtime-owned")
  assert(!file_policy["request_flow"]["desktop_shell_policy_owner"], "C Runtime core Portal request flow must not be KDE-owned")
  assert(!file_policy["direct_access_allowed"], "C Runtime core Portal policy must deny direct access")
  assert(!file_policy["backend_details_exposed"], "C Runtime core Portal policy must hide backend details")

  stdout, stderr, status = Open3.capture3(binary.to_s, "portal-policy", "org.xnix.sample.notepad", "camera")
  assert(status.success?, "C Runtime core camera Portal policy must exit successfully: #{stderr}")
  camera_policy = JSON.parse(stdout)
  assert(camera_policy["decision"] == "deny", "C Runtime core must deny camera access by default")

  _stdout, stderr, status = Open3.capture3(binary.to_s, "portal-policy", "org.xnix.unknown", "file-open")
  assert(!status.success?, "C Runtime core must reject Portal policy for unknown applications")
  assert(stderr.include?("application is not registered"), "C Runtime core must explain unknown Portal application validation")

  _stdout, stderr, status = Open3.capture3(binary.to_s, "portal-policy", "org.xnix.sample.notepad", "unknown")
  assert(!status.success?, "C Runtime core must reject unknown Portal operations")
  assert(stderr.include?("registered sensitive desktop operation"), "C Runtime core must explain unknown Portal operation validation")

  stdout, stderr, status = Open3.capture3(binary.to_s, "list-snapshot-policies")
  assert(status.success?, "C Runtime core snapshot policy catalog must exit successfully: #{stderr}")
  snapshot_catalog = JSON.parse(stdout)
  assert(snapshot_catalog["version"] == "0.2.63", "C Runtime core snapshot policy catalog must expose the current version")
  assert(snapshot_catalog["catalog_type"] == "snapshot-policy", "C Runtime core snapshot policy catalog must identify the catalog type")
  assert(snapshot_catalog["runtime_policy_owner"], "C Runtime core must own snapshot policy")
  assert(!snapshot_catalog["desktop_shell_policy_owner"], "C Runtime core must not make the desktop shell the snapshot policy owner")
  assert(snapshot_catalog["catalog_owner"] == "c", "C Runtime core snapshot policy catalog must be C-owned")
  assert(!snapshot_catalog["backend_details_exposed"], "C Runtime core snapshot policy catalog must hide backend details")
  assert(!snapshot_catalog["host_root_modified"], "C Runtime core snapshot policy catalog must not mutate the host root")
  assert(snapshot_catalog["policy_count"] == 3, "C Runtime core snapshot policy catalog must count policies")
  snapshot_policies = snapshot_catalog.fetch("policies")
  assert(snapshot_policies.map { |policy| policy.fetch("reason") } == %w[before-repair before-engine-change manual], "C Runtime core must keep snapshot policy order stable")
  assert(snapshot_policies.all? { |policy| policy.fetch("enabled_by_default") }, "C Runtime core snapshot policies must default to enabled")
  assert(snapshot_policies.all? { |policy| policy.fetch("snapshot_scope").fetch("application_state") }, "C Runtime core snapshot policies must include application state")
  assert(snapshot_policies.all? { |policy| policy.fetch("snapshot_scope").fetch("runtime_metadata") }, "C Runtime core snapshot policies must include Runtime metadata")
  assert(snapshot_policies.all? { |policy| policy.fetch("snapshot_scope").fetch("desktop_activation_receipts") }, "C Runtime core snapshot policies must include desktop activation receipts")
  assert(snapshot_policies.all? { |policy| !policy.fetch("snapshot_scope").fetch("user_documents") }, "C Runtime core snapshot policies must exclude user documents")
  assert(snapshot_policies.all? { |policy| !policy.fetch("snapshot_scope").fetch("host_system") }, "C Runtime core snapshot policies must exclude the host system")
  assert(snapshot_policies.all? { |policy| policy.fetch("restore").fetch("requires_user_confirmation") }, "C Runtime core snapshot restore must require confirmation")
  assert(snapshot_policies.all? { |policy| policy.fetch("restore").fetch("preserve_user_documents") }, "C Runtime core snapshot restore must preserve user documents")
  assert(snapshot_policies.all? { |policy| policy.fetch("retention").fetch("policy") == "bounded" }, "C Runtime core snapshot policies must use bounded retention")
  assert(snapshot_policies.all? { |policy| policy.fetch("retention").fetch("keep_latest") == 5 }, "C Runtime core snapshot policies must keep a bounded latest set")
  assert(snapshot_policies.all? { |policy| policy.fetch("safety").fetch("runtime_policy_owner") }, "C Runtime core snapshot policies must be Runtime-owned")
  assert(snapshot_policies.all? { |policy| !policy.fetch("safety").fetch("desktop_shell_policy_owner") }, "C Runtime core snapshot policies must not be KDE-owned")
  assert(snapshot_policies.all? { |policy| !policy.fetch("safety").fetch("backend_details_exposed") }, "C Runtime core snapshot policies must hide backend details")
  assert(snapshot_policies.all? { |policy| !policy.fetch("safety").fetch("host_root_modified") }, "C Runtime core snapshot policies must not mutate the host root")
  assert(!stdout.match?(/wine|prefix|\.wine|proton|virtual machine/i), "C Runtime core snapshot policy catalog must not expose backend implementation terms")

  stdout, stderr, status = Open3.capture3(binary.to_s, "snapshot-policy", "org.xnix.sample.notepad", "before-repair")
  assert(status.success?, "C Runtime core snapshot policy must exit successfully: #{stderr}")
  snapshot_policy = JSON.parse(stdout)
  assert(snapshot_policy["plan_type"] == "compatibility-snapshot", "C Runtime core snapshot policy must identify the plan type")
  assert(snapshot_policy["application_id"] == "org.xnix.sample.notepad", "C Runtime core snapshot policy must preserve the application id")
  assert(snapshot_policy["reason"] == "before-repair", "C Runtime core snapshot policy must preserve the reason")
  assert(snapshot_policy["restore"]["method"] == "Runtime.RestoreSnapshot", "C Runtime core snapshot policy must expose the restore method")
  assert(snapshot_policy["retention"]["keep_latest"] == 5, "C Runtime core snapshot policy must expose retention")

  _stdout, stderr, status = Open3.capture3(binary.to_s, "snapshot-policy", "org.xnix.unknown", "manual")
  assert(!status.success?, "C Runtime core must reject snapshot policy for unknown applications")
  assert(stderr.include?("application is not registered"), "C Runtime core must explain unknown snapshot application validation")

  _stdout, stderr, status = Open3.capture3(binary.to_s, "snapshot-policy", "org.xnix.sample.notepad", "unknown")
  assert(!status.success?, "C Runtime core must reject unknown snapshot reasons")
  assert(stderr.include?("registered snapshot reason"), "C Runtime core must explain unknown snapshot reason validation")

  stdout, stderr, status = Open3.capture3(binary.to_s, "list-state-root-policies")
  assert(status.success?, "C Runtime core state root policy catalog must exit successfully: #{stderr}")
  state_root_catalog = JSON.parse(stdout)
  assert(state_root_catalog["version"] == "0.2.63", "C Runtime core state root policy catalog must expose the current version")
  assert(state_root_catalog["catalog_type"] == "application-state-root-policy", "C Runtime core state root policy catalog must identify the catalog type")
  assert(state_root_catalog["runtime_policy_owner"], "C Runtime core must own state root policy")
  assert(!state_root_catalog["desktop_shell_policy_owner"], "C Runtime core must not make the desktop shell the state root policy owner")
  assert(state_root_catalog["catalog_owner"] == "c", "C Runtime core state root policy catalog must be C-owned")
  assert(!state_root_catalog["backend_details_exposed"], "C Runtime core state root policy catalog must hide backend details")
  assert(!state_root_catalog["host_root_modified"], "C Runtime core state root policy catalog must not mutate the host root")
  assert(state_root_catalog["policy_count"] == 1, "C Runtime core state root policy catalog must count policies")
  state_root_records = state_root_catalog.fetch("policies")
  state_root_record = state_root_records.fetch(0)
  assert(state_root_record["application_id"] == "org.xnix.sample.notepad", "C Runtime core state root policy must preserve the application id")
  assert(state_root_record["state_namespace"] == "org.xnix.sample.notepad", "C Runtime core state root policy must expose a stable namespace")
  assert(state_root_record["storage_scope"] == "per-application", "C Runtime core state root policy must remain per-application")
  assert(state_root_record["allocation_state"] == "planned", "C Runtime core state root policy must not claim allocation")
  assert(state_root_record["runtime_owned"], "C Runtime core state root policy must be Runtime-owned")
  assert(!state_root_record["kde_policy_owner"], "C Runtime core state root policy must not be KDE-owned")
  assert(!state_root_record["directories_created"], "C Runtime core state root policy must not create directories")
  assert(!state_root_record["host_root_modified"], "C Runtime core state root policy must not mutate the host root")
  assert(!state_root_record["user_documents_included"], "C Runtime core state root policy must exclude user documents")
  assert(state_root_record["portal_required_for_user_files"], "C Runtime core state root policy must require Portal access for user files")
  assert(state_root_record["snapshot_eligible"], "C Runtime core state root policy must be snapshot eligible")
  assert(state_root_record["restore_requires_confirmation"], "C Runtime core state root policy restore must require confirmation")
  assert(state_root_record["managed_scopes"] == %w[application-data runtime-metadata diagnostic-cache desktop-activation-receipts], "C Runtime core state root policy must keep managed scope order stable")
  assert(!state_root_record["backend_details_exposed"], "C Runtime core state root policy must hide backend details")
  assert(!stdout.match?(/wine|prefix|\.wine|proton|virtual machine/i), "C Runtime core state root policy catalog must not expose backend implementation terms")
  assert(!stdout.match?(%r{/Users|/home|/var|/opt|/tmp}), "C Runtime core state root policy catalog must not expose host storage paths")

  stdout, stderr, status = Open3.capture3(binary.to_s, "state-root-policy", "org.xnix.sample.notepad")
  assert(status.success?, "C Runtime core state root policy must exit successfully: #{stderr}")
  state_root_policy = JSON.parse(stdout)
  assert(state_root_policy["root_type"] == "compatibility-application-state-root", "C Runtime core state root policy must identify the root type")
  assert(state_root_policy["application"]["id"] == "org.xnix.sample.notepad", "C Runtime core state root policy must preserve the application id")
  assert(state_root_policy["application"]["requested_mode"] == "automatic", "C Runtime core state root policy must preserve the requested mode")
  assert(state_root_policy["retention_policy"]["automatic_restore_points"] == 5, "C Runtime core state root policy must expose automatic retention")
  assert(state_root_policy["retention_policy"]["manual_restore_points"] == 10, "C Runtime core state root policy must expose manual retention")
  assert(state_root_policy["retention_policy"]["user_documents_excluded"], "C Runtime core state root retention must exclude user documents")
  assert(state_root_policy["managed_scopes"].map { |scope| scope.fetch("id") } == %w[application-data runtime-metadata diagnostic-cache desktop-activation-receipts], "C Runtime core state root policy must expose managed scope objects")
  assert(!state_root_policy["managed_scopes"].find { |scope| scope.fetch("id") == "diagnostic-cache" }.fetch("snapshot_included"), "C Runtime core state root policy must exclude diagnostic cache from snapshots")
  assert(state_root_policy["blocked_actions"].include?("expose host storage paths to KDE"), "C Runtime core state root policy must block host path exposure")
  assert(!state_root_policy["backend_details_exposed"], "C Runtime core state root policy must hide backend details")

  _stdout, stderr, status = Open3.capture3(binary.to_s, "state-root-policy", "org.xnix.unknown")
  assert(!status.success?, "C Runtime core must reject state root policy for unknown applications")
  assert(stderr.include?("state root policy catalog"), "C Runtime core must explain unknown state root application validation")

  stdout, stderr, status = Open3.capture3(binary.to_s, "list-install-readiness-policies")
  assert(status.success?, "C Runtime core install readiness catalog must exit successfully: #{stderr}")
  install_catalog = JSON.parse(stdout)
  assert(install_catalog["version"] == "0.2.63", "C Runtime core install readiness catalog must expose the current version")
  assert(install_catalog["catalog_type"] == "install-readiness-policy", "C Runtime core install readiness catalog must identify the catalog type")
  assert(install_catalog["runtime_policy_owner"], "C Runtime core must own install readiness policy")
  assert(!install_catalog["desktop_shell_policy_owner"], "C Runtime core must not make the desktop shell the install readiness owner")
  assert(install_catalog["catalog_owner"] == "c", "C Runtime core install readiness catalog must be C-owned")
  assert(!install_catalog["backend_details_exposed"], "C Runtime core install readiness catalog must hide backend details")
  assert(!install_catalog["host_root_modified"], "C Runtime core install readiness catalog must not mutate the host root")
  assert(install_catalog["policy_count"] == 1, "C Runtime core install readiness catalog must count policies")
  install_record = install_catalog.fetch("policies").fetch(0)
  assert(install_record["application_id"] == "org.xnix.sample.notepad", "C Runtime core install readiness must preserve the application id")
  assert(install_record["install_state"] == "planned", "C Runtime core install readiness must stay planned")
  assert(!install_record["install_ready"], "C Runtime core install readiness must not claim install readiness")
  assert(!install_record["desktop_activation_ready"], "C Runtime core install readiness must not claim desktop activation readiness")
  assert(!install_record["download_enabled"], "C Runtime core install readiness must not enable downloads")
  assert(!install_record["install_enabled"], "C Runtime core install readiness must not enable installation")
  assert(!install_record["host_root_modified"], "C Runtime core install readiness must not mutate the host root")
  assert(install_record["selected_strategy"] == "automatic-managed", "C Runtime core install readiness must preserve the selected strategy")
  assert(!install_record["backend_details_exposed"], "C Runtime core install readiness must hide backend details")
  assert(!stdout.match?(/wine|prefix|\.wine|proton|virtual machine/i), "C Runtime core install readiness catalog must not expose backend implementation terms")
  assert(!stdout.match?(%r{/Users|/home|/var|/opt|/tmp}), "C Runtime core install readiness catalog must not expose host storage paths")

  stdout, stderr, status = Open3.capture3(binary.to_s, "install-readiness-policy", "org.xnix.sample.notepad", "development")
  assert(status.success?, "C Runtime core development install readiness must exit successfully: #{stderr}")
  install_policy = JSON.parse(stdout)
  install_phase_ids = install_policy.fetch("phases").map { |phase| phase.fetch("id") }
  assert(install_policy["plan_type"] == "compatibility-install-readiness", "C Runtime core install readiness must identify the plan type")
  assert(install_policy["application"]["id"] == "org.xnix.sample.notepad", "C Runtime core install readiness must preserve the application id")
  assert(install_policy["environment"] == "development", "C Runtime core install readiness must preserve the environment")
  assert(install_policy["runtime_owned"], "C Runtime core install readiness must be Runtime-owned")
  assert(!install_policy["kde_policy_owner"], "C Runtime core install readiness must not be KDE-owned")
  assert(!install_policy["readiness"]["artifact_manifest_ready"], "C Runtime core install readiness must wait for artifact manifests")
  assert(!install_policy["readiness"]["artifact_signature_verified"], "C Runtime core install readiness must wait for artifact signatures")
  assert(!install_policy["readiness"]["acquisition_ready"], "C Runtime core install readiness must wait for acquisition readiness")
  assert(!install_policy["readiness"]["package_source_ready"], "C Runtime core install readiness must wait for package sources")
  assert(!install_policy["readiness"]["state_root_allocated"], "C Runtime core install readiness must wait for state allocation")
  assert(install_policy["readiness"]["recipe_install_allowed"], "C Runtime core development install readiness must allow digest-verified staging")
  assert(install_policy["readiness"]["recipe_install_decision"] == "allow", "C Runtime core development install readiness must expose the allow decision")
  assert(install_phase_ids == %w[resolve-artifact-manifest verify-artifact-digests prepare-package-source allocate-application-state stage-desktop-integration enable-launch-binding], "C Runtime core install readiness must keep phase order stable")
  assert(install_policy["blocked_actions"].include?("mutate the host root during install planning"), "C Runtime core install readiness must block host root mutation")
  assert(!install_policy["download_enabled"], "C Runtime core install readiness must not enable downloads")
  assert(!install_policy["install_enabled"], "C Runtime core install readiness must not enable installation")
  assert(!install_policy["network_request_created"], "C Runtime core install readiness must not create network requests")
  assert(!install_policy["artifacts_downloaded"], "C Runtime core install readiness must not download artifacts")
  assert(!install_policy["privileged_container_required"], "C Runtime core install readiness must not require privileged containers")
  assert(!install_policy["desktop_shell_command_exposed"], "C Runtime core install readiness must not expose desktop shell commands")
  assert(!install_policy["backend_details_exposed"], "C Runtime core install readiness must hide backend details")

  stdout, stderr, status = Open3.capture3(binary.to_s, "install-readiness-policy", "org.xnix.sample.notepad", "production")
  assert(status.success?, "C Runtime core production install readiness must exit successfully: #{stderr}")
  production_install_policy = JSON.parse(stdout)
  assert(!production_install_policy["readiness"]["recipe_install_allowed"], "C Runtime core production install readiness must block development-only registries")
  assert(production_install_policy["readiness"]["recipe_install_decision"] == "block", "C Runtime core production install readiness must expose the blocked decision")

  _stdout, stderr, status = Open3.capture3(binary.to_s, "install-readiness-policy", "org.xnix.sample.notepad", "unknown")
  assert(!status.success?, "C Runtime core must reject unknown install readiness environments")
  assert(stderr.include?("environment must be development or production"), "C Runtime core must explain install readiness environment validation")

  _stdout, stderr, status = Open3.capture3(binary.to_s, "install-readiness-policy", "org.xnix.unknown", "development")
  assert(!status.success?, "C Runtime core must reject install readiness for unknown applications")
  assert(stderr.include?("install readiness policy catalog"), "C Runtime core must explain unknown install readiness application validation")

  stdout, stderr, status = Open3.capture3(binary.to_s, "list-artifact-manifest-policies")
  assert(status.success?, "C Runtime core artifact manifest catalog must exit successfully: #{stderr}")
  artifact_catalog = JSON.parse(stdout)
  assert(artifact_catalog["version"] == "0.2.63", "C Runtime core artifact manifest catalog must expose the current version")
  assert(artifact_catalog["catalog_type"] == "artifact-manifest-policy", "C Runtime core artifact manifest catalog must identify the catalog type")
  assert(artifact_catalog["runtime_policy_owner"], "C Runtime core must own artifact manifest policy")
  assert(!artifact_catalog["desktop_shell_policy_owner"], "C Runtime core must not make the desktop shell the artifact manifest owner")
  assert(artifact_catalog["catalog_owner"] == "c", "C Runtime core artifact manifest catalog must be C-owned")
  assert(!artifact_catalog["backend_details_exposed"], "C Runtime core artifact manifest catalog must hide backend details")
  assert(!artifact_catalog["host_root_modified"], "C Runtime core artifact manifest catalog must not mutate the host root")
  assert(artifact_catalog["policy_count"] == 1, "C Runtime core artifact manifest catalog must count policies")
  artifact_record = artifact_catalog.fetch("policies").fetch(0)
  assert(artifact_record["application_id"] == "org.xnix.sample.notepad", "C Runtime core artifact manifest must preserve the application id")
  assert(artifact_record["manifest_state"] == "planned", "C Runtime core artifact manifest must stay planned")
  assert(!artifact_record["manifest_ready"], "C Runtime core artifact manifest must not claim readiness")
  assert(!artifact_record["signature_verified"], "C Runtime core artifact manifest must not claim signature verification")
  assert(!artifact_record["download_enabled"], "C Runtime core artifact manifest must not enable downloads")
  assert(!artifact_record["artifacts_downloaded"], "C Runtime core artifact manifest must not download artifacts")
  assert(!artifact_record["host_root_modified"], "C Runtime core artifact manifest must not mutate the host root")
  assert(artifact_record["selected_strategy"] == "automatic-managed", "C Runtime core artifact manifest must preserve the selected strategy")
  assert(!artifact_record["backend_details_exposed"], "C Runtime core artifact manifest must hide backend details")
  assert(!stdout.match?(/wine|prefix|\.wine|proton|virtual machine/i), "C Runtime core artifact manifest catalog must not expose backend implementation terms")
  assert(!stdout.match?(%r{/Users|/home|/var|/opt|/tmp}), "C Runtime core artifact manifest catalog must not expose host storage paths")

  stdout, stderr, status = Open3.capture3(binary.to_s, "artifact-manifest-policy", "org.xnix.sample.notepad")
  assert(status.success?, "C Runtime core artifact manifest must exit successfully: #{stderr}")
  artifact_manifest = JSON.parse(stdout)
  artifact_group_ids = artifact_manifest.fetch("artifact_groups").map { |group| group.fetch("id") }
  artifact_preflight_ids = artifact_manifest.fetch("required_preflight").map { |preflight| preflight.fetch("id") }
  assert(artifact_manifest["manifest_type"] == "compatibility-artifact-manifest", "C Runtime core artifact manifest must identify the manifest type")
  assert(artifact_manifest["application"]["id"] == "org.xnix.sample.notepad", "C Runtime core artifact manifest must preserve the application id")
  assert(artifact_manifest["runtime_owned"], "C Runtime core artifact manifest must be Runtime-owned")
  assert(!artifact_manifest["kde_policy_owner"], "C Runtime core artifact manifest must not be KDE-owned")
  assert(artifact_manifest["selected_strategy"] == "automatic-managed", "C Runtime core artifact manifest must align with the selected strategy")
  assert(artifact_manifest["manifest_state"] == "planned", "C Runtime core artifact manifest must not claim resolution")
  assert(!artifact_manifest["manifest_ready"], "C Runtime core artifact manifest must not claim readiness")
  assert(!artifact_manifest["signature_verified"], "C Runtime core artifact manifest must not claim signature verification")
  assert(!artifact_manifest["acquisition_preflight_ready"], "C Runtime core artifact manifest must inherit pending acquisition preflight")
  assert(!artifact_manifest["download_enabled"], "C Runtime core artifact manifest must not enable downloads")
  assert(!artifact_manifest["install_enabled"], "C Runtime core artifact manifest must not enable installation")
  assert(!artifact_manifest["network_request_created"], "C Runtime core artifact manifest must not create network requests")
  assert(!artifact_manifest["artifacts_downloaded"], "C Runtime core artifact manifest must not download artifacts")
  assert(!artifact_manifest["host_root_modified"], "C Runtime core artifact manifest must not mutate the host root")
  assert(!artifact_manifest["privileged_container_required"], "C Runtime core artifact manifest must not require privileged containers")
  assert(!artifact_manifest["desktop_shell_command_exposed"], "C Runtime core artifact manifest must not expose desktop shell commands")
  assert(artifact_group_ids == %w[runtime-launch-metadata local-execution-artifacts isolated-environment-artifacts], "C Runtime core artifact manifest must expose expected artifact groups")
  assert(artifact_preflight_ids == %w[acquisition-preflight-ready manifest-signature-verification artifact-digest-verification cache-namespace-allocation rollback-reference], "C Runtime core artifact manifest must expose expected preflight")
  assert(artifact_manifest["artifact_groups"].none? { |group| group.fetch("resolved") }, "C Runtime core artifact manifest must not claim artifact resolution")
  assert(artifact_manifest["artifact_groups"].none? { |group| group.fetch("downloaded") }, "C Runtime core artifact manifest must not claim artifact downloads")
  assert(artifact_manifest["blocked_actions"].include?("expose artifact cache paths to KDE"), "C Runtime core artifact manifest must block cache path exposure")
  assert(!artifact_manifest["backend_details_exposed"], "C Runtime core artifact manifest must hide backend details")

  _stdout, stderr, status = Open3.capture3(binary.to_s, "artifact-manifest-policy", "org.xnix.unknown")
  assert(!status.success?, "C Runtime core must reject artifact manifests for unknown applications")
  assert(stderr.include?("artifact manifest policy catalog"), "C Runtime core must explain unknown artifact manifest application validation")

  stdout, stderr, status = Open3.capture3(binary.to_s, "write-gate", "Launch")
  assert(status.success?, "C Runtime core write-gate must exit successfully: #{stderr}")
  gate = JSON.parse(stdout)
  assert(gate["gate_type"] == "runtime-write-gate", "C Runtime core must emit write gate models")
  assert(gate["method_name"] == "Launch", "C Runtime core write gate must preserve the method")
  assert(gate["gate_decision"] == "blocked-until-production-backend", "C Runtime core must block writes until production backend")
  assert(!gate["write_method_enabled"], "C Runtime core must not enable writes")
  assert(!gate["dispatch_enabled"], "C Runtime core must not enable write dispatch")
  assert(!gate["request_object_created"], "C Runtime core must not create request objects")
  assert(!gate["execution_started"], "C Runtime core must not start execution")
  assert(gate["denial_error_name"] == "org.xnix.Compatibility1.Error.WriteMethodDisabled", "C Runtime core must expose the write denial error")

  _stdout, stderr, status = Open3.capture3(binary.to_s, "write-gate", "Unknown")
  assert(!status.success?, "C Runtime core must reject unknown write gate methods")
  assert(stderr.include?("reserved Runtime write method"), "C Runtime core must explain write gate validation")
end

puts "PASS: C Runtime core unit tests"
