#!/usr/bin/env ruby
# frozen_string_literal: true

require "json"
require "open3"
require "pathname"

def assert(condition, message)
  return if condition

  warn "FAIL: #{message}"
  exit 1
end

project_root = Pathname.new(__dir__).join("..").realpath
script = project_root.join("scripts/q4_notepadpp_portable_winapp_smoke.rb")
source = script.read

assert(source.include?("xnix.scripts.q4_notepadpp_portable_winapp_smoke.v1"), "q4 Notepad++ smoke must expose a stable schema")
assert(source.include?("q4-notepadpp-portable-winapp-smoke"), "q4 Notepad++ smoke must expose a stable request type")
assert(source.include?("https://github.com/notepad-plus-plus/notepad-plus-plus/releases/download/v8.9.7/npp.8.9.7.portable.zip"), "q4 Notepad++ smoke must target the official portable zip")
assert(source.include?("ce0690fac91c1fc5d61dcdf5b09733ff0d143a61d0a27c6cb9f4003ea92765bb"), "q4 Notepad++ smoke must pin the official portable zip checksum")
assert(source.include?("scripts/remote_go_build.rb"), "q4 Notepad++ smoke must build the Go Runtime on q4")
assert(source.include?("windows-known-app-bundle-import-record"), "q4 Notepad++ smoke must use the Go Runtime known bundle import command")
assert(source.include?("windows-known-app-bundle-stage-and-launch"), "q4 Notepad++ smoke must use the Go Runtime known bundle staged launch command")
assert(source.include?("real-winapp-gui-evidence-packet-preview"), "q4 Notepad++ smoke must project the Go staged launch into a Runtime GUI evidence packet")
assert(source.include?("kde-center-page-preview"), "q4 Notepad++ smoke must render the known bundle GUI evidence through KDE page preview")
assert(source.include?("external-winapp-compatibility-evidence-bundle-preview"), "q4 Notepad++ smoke must produce a Runtime compatibility bundle from the known bundle staged launch")
assert(source.include?("external-winapp-application-detail-preview"), "q4 Notepad++ smoke must produce a Runtime application detail from the known bundle compatibility bundle")
assert(source.include?("q4-known-portable-bundle-winapp-acceptance-preview"), "q4 Notepad++ smoke must produce a Go-owned known portable bundle acceptance")
assert(source.include?("--managed-launcher-bin"), "q4 Notepad++ smoke must pass the Go managed launcher to the Runtime staged launch")
assert(source.include?("--allow-download"), "q4 Notepad++ smoke must explicitly authorize q4 download through the Runtime")
assert(source.include?("--include-fetch"), "q4 Notepad++ smoke must preserve fetch evidence from the Runtime")
assert(source.include?("known_portable_bundle_import_recorded"), "q4 Notepad++ smoke must record known bundle import evidence")
assert(source.include?("known_portable_bundle_stage_launch_status"), "q4 Notepad++ smoke must record Go-owned staged launch evidence")
assert(source.include?("known_portable_bundle_gui_evidence_packet_status"), "q4 Notepad++ smoke must record Go-owned GUI evidence packet status")
assert(source.include?("known_portable_bundle_gui_evidence_packet_artifact_fetched"), "q4 Notepad++ smoke must fetch the Go-owned GUI evidence packet artifact")
assert(source.include?("known_portable_bundle_compatibility_bundle_stage_launch_consumed"), "q4 Notepad++ smoke must record known bundle compatibility bundle consumption")
assert(source.include?("known_portable_bundle_compatibility_bundle_artifact_fetched"), "q4 Notepad++ smoke must fetch the known bundle compatibility evidence bundle")
assert(source.include?("known_portable_bundle_application_detail_stage_launch_consumed"), "q4 Notepad++ smoke must record known bundle application detail consumption")
assert(source.include?("known_portable_bundle_kde_page_from_detail_stage_launch_consumed"), "q4 Notepad++ smoke must expose known bundle provenance in the KDE page from detail")
assert(source.include?("known_portable_bundle_acceptance_ready"), "q4 Notepad++ smoke must record Go-owned known bundle acceptance readiness")
assert(source.include?("known_portable_bundle_acceptance_artifact_fetched"), "q4 Notepad++ smoke must fetch the known bundle acceptance artifact")
assert(source.include?("known_portable_bundle_archive_verified"), "q4 Notepad++ smoke must expose Runtime archive verification")
assert(source.include?("existing_import_record_consumed"), "q4 Notepad++ smoke must require existing import record consumption")
assert(source.include?("record_first_launch_path"), "q4 Notepad++ smoke must expose record-first launch evidence")
assert(source.include?("scripts/q4_staged_desktop_external_winapp_smoke.rb"), "q4 Notepad++ smoke must delegate to the staged external Runtime/KDE path")
assert(source.include?("--remote-import-record"), "q4 Notepad++ smoke must delegate the q4 Runtime import record")
assert(source.include?("notepadpp_executable_relative_path"), "q4 Notepad++ smoke must keep the selected portable executable in the Runtime import evidence")
assert(source.include?("notepad++.exe"), "q4 Notepad++ smoke must select the portable Notepad++ executable")
assert(source.include?("portable_directory_external_app"), "q4 Notepad++ smoke must record portable-directory evidence")
assert(source.include?("portable_directory_bundle_import_required"), "q4 Notepad++ smoke must require the bundle import path")
assert(source.include?("real_third_party_windows_app"), "q4 Notepad++ smoke must distinguish real third-party app evidence")
assert(source.include?("host_download_avoided"), "q4 Notepad++ smoke must avoid host-side download")
assert(source.include?("host_compilation_avoided"), "q4 Notepad++ smoke must avoid host-side compilation")

stdout, stderr, status = Open3.capture3(
  "ruby",
  script.to_s,
  "--output", "/tmp/xnix-q4-notepadpp-plan.json",
  "--markdown-output", "/tmp/xnix-q4-notepadpp-plan.md"
)
assert(status.success?, "q4 Notepad++ plan must exit successfully: #{stderr}")
payload = JSON.parse(stdout)
assert(payload.fetch("schema_version") == "xnix.scripts.q4_notepadpp_portable_winapp_smoke.v1", "plan must expose schema")
assert(payload.fetch("request_type") == "q4-notepadpp-portable-winapp-smoke", "plan must expose request type")
assert(payload.fetch("status") == "planned", "plan must not execute by default")
assert(payload.fetch("execute") == false, "plan must keep execute disabled by default")
assert(payload.fetch("remote_host") == "root@q4", "plan must default to q4")
assert(payload.fetch("remote_runtime_binary").end_with?("/xnix-runtime-go"), "plan must expose the q4 Runtime binary")
assert(payload.fetch("remote_launcher_binary").end_with?("/xnix-compat-launch"), "plan must expose the q4 managed launcher binary")
assert(payload.fetch("source_kind") == "official-notepad-plus-plus-github-release", "plan must identify official source")
assert(payload.fetch("notepadpp_version") == "8.9.7", "plan must pin the Notepad++ version")
assert(payload.fetch("notepadpp_zip") == "npp.8.9.7.portable.zip", "plan must pin the portable zip")
assert(payload.fetch("notepadpp_sha256") == "ce0690fac91c1fc5d61dcdf5b09733ff0d143a61d0a27c6cb9f4003ea92765bb", "plan must pin the portable zip checksum")
assert(payload.fetch("notepadpp_download_planned") == true, "plan must download the portable zip")
assert(payload.fetch("notepadpp_downloaded") == false, "plan must not claim download before execute")
assert(payload.fetch("notepadpp_sha256_verified") == false, "plan must not claim checksum before execute")
assert(payload.fetch("notepadpp_extracted") == false, "plan must not claim extraction before execute")
assert(payload.fetch("notepadpp_executable_configured") == true, "plan must configure the executable")
assert(payload.fetch("notepadpp_executable_relative_path") == "notepad++.exe", "plan must select the portable executable")
assert(payload.fetch("known_portable_bundle_import_planned") == true, "plan must use the known portable bundle import path")
assert(payload.fetch("known_portable_bundle_import_command").include?("windows-known-app-bundle-import-record"), "plan must call the Runtime known bundle importer")
assert(payload.fetch("known_portable_bundle_import_command").include?("--allow-download"), "plan must explicitly authorize q4 Runtime download")
assert(payload.fetch("known_portable_bundle_import_recorded") == false, "plan must not claim import before execute")
assert(payload.fetch("known_portable_bundle_import_status") == "planned", "plan must mark import as planned")
assert(payload.fetch("go_known_portable_bundle_import_backed") == true, "plan must keep known bundle import in Go")
assert(payload.fetch("known_portable_bundle_stage_launch_planned") == true, "plan must use the known portable bundle staged launch path")
assert(payload.fetch("known_portable_bundle_stage_launch_command").include?("windows-known-app-bundle-stage-and-launch"), "plan must call the Runtime known bundle staged launcher")
assert(payload.fetch("known_portable_bundle_stage_launch_command").include?("--managed-launcher-bin"), "plan must pass the managed launcher to the Runtime command")
assert(payload.fetch("known_portable_bundle_stage_launch_command").include?("file://#{payload.fetch("remote_app_root")}/sample-document.txt"), "plan must pass a q4 file-open document to the Runtime command")
assert(payload.fetch("known_portable_bundle_stage_launch_status") == "planned", "plan must mark staged launch as planned")
assert(payload.fetch("go_known_portable_bundle_stage_launch_backed") == true, "plan must keep staged launch in Go")
assert(payload.fetch("known_portable_bundle_gui_evidence_packet_planned") == true, "plan must produce a Runtime GUI evidence packet from the Go staged launch")
assert(payload.fetch("known_portable_bundle_gui_evidence_packet_command").include?("real-winapp-gui-evidence-packet-preview"), "plan must call the Runtime GUI evidence packet command")
assert(payload.fetch("known_portable_bundle_gui_evidence_packet_command").include?(payload.fetch("known_portable_bundle_stage_launch_report")), "plan must consume the Go staged launch report")
assert(payload.fetch("known_portable_bundle_gui_evidence_packet_status") == "planned", "plan must mark GUI evidence packet as planned")
assert(payload.fetch("known_portable_bundle_kde_page_planned") == true, "plan must render a KDE page from the known bundle GUI evidence packet")
assert(payload.fetch("known_portable_bundle_kde_page_command").include?("kde-center-page-preview"), "plan must call KDE page preview for known bundle evidence")
assert(payload.fetch("known_portable_bundle_kde_page_command").include?(payload.fetch("known_portable_bundle_gui_evidence_packet_report")), "plan must render KDE from the known bundle GUI evidence packet")
assert(payload.fetch("known_portable_bundle_kde_page_status") == "planned", "plan must mark known bundle KDE page as planned")
assert(payload.fetch("known_portable_bundle_compatibility_bundle_planned") == true, "plan must produce a compatibility bundle from known bundle artifacts")
assert(payload.fetch("known_portable_bundle_compatibility_bundle_command").include?("external-winapp-compatibility-evidence-bundle-preview"), "plan must call the Runtime compatibility evidence bundle command")
assert(payload.fetch("known_portable_bundle_compatibility_bundle_command").include?(payload.fetch("known_portable_bundle_stage_launch_report")), "plan must feed the known staged launch report into the compatibility bundle")
assert(payload.fetch("known_portable_bundle_compatibility_bundle_command").include?(payload.fetch("known_portable_bundle_gui_evidence_packet_report")), "plan must feed the known GUI packet into the compatibility bundle")
assert(payload.fetch("known_portable_bundle_compatibility_bundle_status") == "planned", "plan must mark known bundle compatibility bundle as planned")
assert(payload.fetch("known_portable_bundle_application_detail_planned") == true, "plan must produce a Runtime application detail from the known bundle bundle")
assert(payload.fetch("known_portable_bundle_application_detail_command").include?("external-winapp-application-detail-preview"), "plan must call the Runtime application detail command")
assert(payload.fetch("known_portable_bundle_application_detail_command").include?(payload.fetch("known_portable_bundle_compatibility_bundle_report")), "plan must feed the known compatibility bundle into the application detail")
assert(payload.fetch("known_portable_bundle_application_detail_status") == "planned", "plan must mark known bundle application detail as planned")
assert(payload.fetch("known_portable_bundle_kde_page_from_detail_planned") == true, "plan must render a KDE page from the known bundle application detail")
assert(payload.fetch("known_portable_bundle_kde_page_from_detail_command").include?("kde-center-page-preview"), "plan must call KDE page preview from known bundle detail")
assert(payload.fetch("known_portable_bundle_kde_page_from_detail_command").include?(payload.fetch("known_portable_bundle_application_detail_report")), "plan must feed the known application detail into KDE")
assert(payload.fetch("known_portable_bundle_kde_page_from_detail_status") == "planned", "plan must mark known bundle KDE page from detail as planned")
assert(payload.fetch("known_portable_bundle_acceptance_planned") == true, "plan must produce a Go-owned known bundle acceptance")
assert(payload.fetch("known_portable_bundle_acceptance_command").include?("q4-known-portable-bundle-winapp-acceptance-preview"), "plan must call the Go-owned known bundle acceptance command")
assert(payload.fetch("known_portable_bundle_acceptance_command").include?(payload.fetch("known_portable_bundle_acceptance_report")), "plan must write the known bundle acceptance artifact")
assert(payload.fetch("known_portable_bundle_acceptance_status") == "planned", "plan must mark known bundle acceptance as planned")
assert(payload.fetch("artifact_output_root").end_with?("/artifacts"), "plan must expose the local artifact output root")
assert(payload.fetch("record_first_launch_path") == true, "plan must use the Runtime import record as the staged launch source")
assert(payload.fetch("portable_directory_external_app") == true, "plan must mark the app as portable-directory")
assert(payload.fetch("portable_directory_bundle_import_required") == true, "plan must require bundle import")
assert(payload.fetch("real_third_party_windows_app") == true, "plan must mark the app as a real third-party app")
assert(payload.fetch("single_file_windows_app") == false, "plan must not claim the app is single-file")
assert(payload.fetch("delegated_command").include?("scripts/q4_staged_desktop_external_winapp_smoke.rb"), "plan must delegate to staged external smoke")
assert(payload.fetch("delegated_command").include?("--remote-import-record"), "plan must pass the q4 Runtime import record")
assert(payload.fetch("delegated_command").any? { |value| value.end_with?("/external-apps/org.xnix.external.notepadplusplus/import-record.json") }, "plan must show the Runtime-owned import record path")
assert(payload.fetch("notepadpp_executable_relative_path") == "notepad++.exe", "plan must preserve the selected executable in the Runtime import evidence")
assert(payload.fetch("delegated_command").include?("org.xnix.external.notepadplusplus"), "plan must pass app identity")
assert(payload.fetch("delegated_command").include?("Notepad++ Portable"), "plan must pass display name")
assert(payload.fetch("runtime_owned") == true, "plan must keep Runtime ownership")
assert(payload.fetch("go_runtime_backed") == true, "plan must keep Go Runtime backing")
assert(payload.fetch("kde_policy_owner") == false, "plan must not make KDE the policy owner")
assert(payload.fetch("q4_download_required") == true, "plan must require q4 download")
assert(payload.fetch("q4_extract_required") == true, "plan must require q4 extraction")
assert(payload.fetch("q4_compile_required") == true, "plan must require q4 Runtime compilation")
assert(payload.fetch("host_compilation_avoided") == true, "plan must avoid host compilation")
assert(payload.fetch("host_download_avoided") == true, "plan must avoid host download")
assert(payload.fetch("full_smoke_required") == false, "plan must remain targeted")
assert(payload.fetch("host_root_modified") == false, "plan must not mutate host root")
assert(payload.fetch("privileged_container_required") == false, "plan must not require privileged containers")
assert(payload.fetch("host_networking_required") == false, "plan must not require host networking")
assert(payload.fetch("docker_socket_mounted") == false, "plan must not mount Docker socket")
assert(payload.fetch("broad_host_mount_required") == false, "plan must not require broad host mounts")

stdout, stderr, status = Open3.capture3(
  "ruby",
  script.to_s,
  "--remote-materials-root", "/Users/rocky/not-q4"
)
assert(!status.success?, "q4 Notepad++ plan must reject unsafe remote materials roots")
assert(stderr.include?("remote materials root must stay under /home/xnix-* or /tmp/xnix-* on q4"), "q4 Notepad++ plan must explain unsafe roots")

puts "PASS: q4 Notepad++ Portable Windows app smoke is official-download and q4-bundle-runtime backed"
