#!/usr/bin/env ruby
# frozen_string_literal: true

require "open3"
require "pathname"

def assert(condition, message)
  return if condition

  warn "FAIL: #{message}"
  exit 1
end

project_root = Pathname.new(__dir__).join("..").realpath
script = project_root.join("scripts/staged_launcher_dispatch_smoke.rb")
container_script = project_root.join("scripts/container.rb")
container_model = project_root.join("lib/xnix/container.rb")
contents = script.read

assert(script.executable?, "Staged launcher dispatch smoke script must be executable")
assert(contents.include?("windows-known-app-dispatch-preview"), "Staged launcher dispatch smoke must preflight the managed artifact")
assert(contents.include?("desktop-activation-stage"), "Staged launcher dispatch smoke must stage desktop activation files")
assert(contents.include?("--managed-launcher-bin"), "Staged launcher dispatch smoke must copy the Go launcher binary")
assert(contents.include?("usr/local/bin/xnix-compat-launch"), "Staged launcher dispatch smoke must execute the staged launcher")
assert(contents.include?("--guest-boundary"), "Staged launcher dispatch smoke must supply the controlled guest boundary")
assert(contents.include?("--state-root"), "Staged launcher dispatch smoke must supply the Runtime state root to the launcher")
assert(contents.include?("--receipt-id"), "Staged launcher dispatch smoke must supply the opaque receipt id to the launcher")
assert(contents.include?("--review-receipt-id"), "Staged launcher dispatch smoke must supply the opaque review receipt id to the launcher")
assert(contents.include?("--session-id"), "Staged launcher dispatch smoke must supply the opaque controlled execution session id to the launcher")
assert(contents.include?("managed-known-app-guest-smoke"), "Staged launcher dispatch smoke must use the known app guest smoke boundary")
assert(contents.include?("windows-known-app-dispatch-smoke"), "Staged launcher dispatch smoke must enter the dispatch smoke path")
assert(contents.include?("compatibility-center-preview"), "Staged launcher dispatch smoke must feed Compatibility Center preview evidence")
assert(contents.include?("kde-center-page-preview"), "Staged launcher dispatch smoke must feed KDE Center page preview evidence")
assert(contents.include?("known-app-launch-authorization-receipt-preview"), "Staged launcher dispatch smoke must record a Runtime launch authorization receipt")
assert(contents.include?("known-app-launch-gate-preview"), "Staged launcher dispatch smoke must consume the Runtime launch gate")
assert(contents.include?("known-app-controlled-dispatch-request-preview"), "Staged launcher dispatch smoke must materialize a controlled dispatch request")
assert(contents.include?("known-app-controlled-execution-session-preview"), "Staged launcher dispatch smoke must materialize a controlled execution session handoff")
assert(contents.include?("known-app-controlled-execution-session-record"), "Staged launcher dispatch smoke must persist a controlled execution session record")
assert(contents.include?("known-app-controlled-execution-session-consume-preview"), "Staged launcher dispatch smoke must consume the controlled execution session record")
assert(contents.include?("known-app-session-gated-launch-review-preview"), "Staged launcher dispatch smoke must verify the session-gated Runtime launch review route")
assert(contents.include?("known-app-session-gated-launch-review-receipt-record"), "Staged launcher dispatch smoke must record the session-gated Runtime launch review receipt")
assert(contents.include?("known-app-session-gated-launch-review-gate-preview"), "Staged launcher dispatch smoke must consume the session-gated Runtime launch review gate")
assert(contents.include?("known-app-session-gated-controlled-dispatch-request-preview"), "Staged launcher dispatch smoke must create post-review controlled dispatch state")
assert(contents.include?("known-app-kde-runtime-status-launch-execution"), "Staged launcher dispatch smoke must execute through the Runtime-owned KDE status launch entrypoint")
assert(contents.include?("state_root_injected_by_runtime"), "Staged launcher dispatch smoke must verify Runtime state-root injection")
assert(contents.include?("managed_launcher_invoked"), "Staged launcher dispatch smoke must verify Runtime wrapper invoked the managed launcher")
assert(contents.include?("existing_managed_launcher_invoked"), "Staged launcher dispatch smoke must verify the existing staged launcher was invoked")
assert(contents.include?("launcher_output_json_observed"), "Staged launcher dispatch smoke must verify delegated launcher JSON was observed")
assert(contents.include?("delegated_request_type"), "Staged launcher dispatch smoke must consume delegated launcher request type from the Runtime wrapper")
assert(contents.include?("delegated_runtime_owned_dispatch"), "Staged launcher dispatch smoke must preserve delegated Runtime-owned dispatch evidence")
assert(contents.include?("compatibility_center_known_app_evidence"), "Staged launcher dispatch smoke must consume the Go-owned Center evidence projection")
assert(contents.include?("known-app-kde-runtime-status-launch-delegated-evidence"), "Staged launcher dispatch smoke must verify delegated evidence projection type")
assert(contents.include?("compatibility_center_projection_ready"), "Staged launcher dispatch smoke must verify Compatibility Center projection readiness")
assert(contents.include?("kde_center_projection_ready"), "Staged launcher dispatch smoke must verify KDE Center projection readiness")
assert(contents.include?("known_app_staged_launcher_passed_count"), "Staged launcher dispatch smoke must verify Compatibility Center staged launcher evidence")
assert(contents.include?("known_app_launch_authorization_required_count"), "Staged launcher dispatch smoke must verify launch authorization requirement count")
assert(contents.include?("known_app_launch_authorization_recorded_count"), "Staged launcher dispatch smoke must verify launch authorization receipt count")
assert(contents.include?("known_app_launch_gate_consumed_count"), "Staged launcher dispatch smoke must verify launch gate consumption count")
assert(contents.include?("known_app_controlled_dispatch_ready_count"), "Staged launcher dispatch smoke must verify controlled dispatch readiness count")
assert(contents.include?("known_app_launcher_session_gate_consumed_count"), "Staged launcher dispatch smoke must verify launcher session gate consumption count")
assert(contents.include?("known_app_post_review_dispatch_consumed_count"), "Staged launcher dispatch smoke must verify post-review dispatch consumption count")
assert(contents.include?("known_app_session_gate_evidence_count"), "Staged launcher dispatch smoke must verify KDE Center page session gate evidence count")
assert(contents.include?("known_app_session_gate_cards"), "Staged launcher dispatch smoke must verify KDE Center page session gate cards")
assert(contents.include?("read_before_write_required"), "Staged launcher dispatch smoke must verify read-before-write Runtime review routing")
assert(contents.include?("read_before_write_consumed"), "Staged launcher dispatch smoke must verify read-before-write Runtime review receipt consumption")
assert(contents.include?("runtime_receipt_required"), "Staged launcher dispatch smoke must keep a later Runtime receipt required")
assert(contents.include?("review_route_consumed"), "Staged launcher dispatch smoke must verify Runtime review route consumption")
assert(contents.include?("review_receipt_recorded"), "Staged launcher dispatch smoke must verify Runtime review receipt recording")
assert(contents.include?("review_receipt_consumed"), "Staged launcher dispatch smoke must verify Runtime review receipt consumption")
assert(contents.include?("review_receipt_accepted"), "Staged launcher dispatch smoke must verify Runtime review receipt acceptance")
assert(contents.include?("review_gate_ready"), "Staged launcher dispatch smoke must verify Runtime review gate readiness")
assert(contents.include?("review_receipt_id"), "Staged launcher dispatch smoke must preserve the opaque Runtime review receipt id")
assert(contents.include?("review_receipt_relative_path"), "Staged launcher dispatch smoke must expose only relative review receipt evidence")
assert(contents.include?("review_receipt_sha256"), "Staged launcher dispatch smoke must expose review receipt digest evidence")
assert(contents.include?("controlled_dispatch_gate_ready"), "Staged launcher dispatch smoke must verify controlled dispatch gate readiness")
assert(contents.include?("dispatch_state_advance_ready"), "Staged launcher dispatch smoke must verify dispatch state advancement readiness")
assert(contents.include?("dispatch_state_advanced"), "Staged launcher dispatch smoke must verify dispatch state remains unadvanced in the gate preview")
assert(contents.include?("receipt_relative_path"), "Staged launcher dispatch smoke must expose only relative Runtime review receipt evidence")
assert(contents.include?("receipt_sha256"), "Staged launcher dispatch smoke must expose Runtime review receipt digest evidence")
assert(contents.include?("receipt_path_exposed"), "Staged launcher dispatch smoke must keep Runtime review receipt paths hidden")
assert(contents.include?("validated-post-review-dispatch"), "Staged launcher dispatch smoke must verify the post-review dispatch card state")
assert(contents.include?("review-launch-authorization"), "Staged launcher dispatch smoke must verify the launch authorization review action")
assert(contents.include?("show-runtime-controlled-launch"), "Staged launcher dispatch smoke must verify the Runtime-controlled launch status action")
assert(contents.include?("runtime-status"), "Staged launcher dispatch smoke must verify the Runtime status action kind")
assert(contents.include?("known-app-kde-runtime-status-launch-request-preview"), "Staged launcher dispatch smoke must verify the KDE Runtime-status launch request preview")
assert(contents.include?("runtime_status_launch_request_type"), "Staged launcher dispatch smoke must verify the Runtime-status launch request type")
assert(contents.include?("runtime_status_launch_managed_launcher_argv"), "Staged launcher dispatch smoke must verify the KDE-collected managed launcher argv")
assert(contents.include?("runtime_status_launch_state_root_owned_by_runtime"), "Staged launcher dispatch smoke must keep the Runtime-status launch state root Runtime-owned")
assert(contents.include?("direct_launch_enabled"), "Staged launcher dispatch smoke must keep direct launch disabled")
assert(contents.include?("launch_authorization_receipt_state"), "Staged launcher dispatch smoke must expose the launch authorization receipt state")
assert(contents.include?("launch_authorization_receipt_id"), "Staged launcher dispatch smoke must expose the opaque launch authorization receipt id")
assert(contents.include?("launch_gate_state"), "Staged launcher dispatch smoke must expose the launch gate state")
assert(contents.include?("launch_gate_consumed"), "Staged launcher dispatch smoke must expose launch gate consumption")
assert(contents.include?("launch_gate_receipt_accepted"), "Staged launcher dispatch smoke must expose launch gate receipt acceptance")
assert(contents.include?("launch_gate_guest_boundary_accepted"), "Staged launcher dispatch smoke must expose launch gate boundary acceptance")
assert(contents.include?("controlled_dispatch_ready"), "Staged launcher dispatch smoke must expose controlled dispatch readiness")
assert(contents.include?("controlled_dispatch_request_created"), "Staged launcher dispatch smoke must verify controlled dispatch request creation")
assert(contents.include?("controlled_dispatch_request_state"), "Staged launcher dispatch smoke must verify controlled dispatch request state")
assert(contents.include?("created-after-session-gated-review"), "Staged launcher dispatch smoke must verify post-review controlled dispatch state")
assert(contents.include?("runtime_owned_dispatch_request"), "Staged launcher dispatch smoke must verify Runtime ownership of controlled dispatch requests")
assert(contents.include?("runtime_owned_execution_session"), "Staged launcher dispatch smoke must verify Runtime ownership of controlled execution sessions")
assert(contents.include?("execution_session_handoff_created"), "Staged launcher dispatch smoke must verify controlled execution session handoff creation")
assert(contents.include?("session_handoff_ready"), "Staged launcher dispatch smoke must verify controlled execution session handoff readiness")
assert(contents.include?("ledger_record_written"), "Staged launcher dispatch smoke must verify controlled execution ledger persistence")
assert(contents.include?("session_record_written"), "Staged launcher dispatch smoke must verify controlled execution session persistence")
assert(contents.include?("session_record_consumed"), "Staged launcher dispatch smoke must verify controlled execution session consumption")
assert(contents.include?("session_digest_verified"), "Staged launcher dispatch smoke must verify controlled execution session digest consumption")
assert(contents.include?("runtime_owner_consumable"), "Staged launcher dispatch smoke must verify Runtime-owner consumption readiness")
assert(contents.include?("kde_read_model_consumable"), "Staged launcher dispatch smoke must verify KDE read-model consumption readiness")
assert(contents.include?("controlled_execution_session_consumed"), "Staged launcher dispatch smoke must verify launcher-side session consumption")
assert(contents.include?("session_gated_controlled_dispatch_consumed"), "Staged launcher dispatch smoke must verify launcher-side post-review dispatch state consumption")
assert(contents.include?("session_gated_controlled_dispatch_state"), "Staged launcher dispatch smoke must verify launcher-side post-review dispatch state")
assert(contents.include?("session_gated_review_receipt_id"), "Staged launcher dispatch smoke must verify launcher-side review receipt id preservation")
assert(contents.include?("post_review_dispatch_consumed"), "Staged launcher dispatch smoke must feed post-review dispatch consumption into Compatibility Center")
assert(contents.include?("post_review_dispatch_state"), "Staged launcher dispatch smoke must feed post-review dispatch state into Compatibility Center")
assert(contents.include?("--known-app-post-review-dispatch-consumed"), "Staged launcher dispatch smoke must pass post-review dispatch consumption to Runtime previews")
assert(contents.include?("--known-app-post-review-dispatch-state"), "Staged launcher dispatch smoke must pass post-review dispatch state to Runtime previews")
assert(contents.include?("--known-app-session-gated-review-receipt-id"), "Staged launcher dispatch smoke must pass the opaque session-gated review receipt id to Runtime previews")
assert(contents.include?("controlled_session_digest_verified"), "Staged launcher dispatch smoke must verify launcher-side session digest consumption")
assert(contents.include?("runtime_owner_consumable_session"), "Staged launcher dispatch smoke must verify launcher-side Runtime-owner session readiness")
assert(contents.include?("kde_read_model_consumable_session"), "Staged launcher dispatch smoke must verify launcher-side KDE session readiness")
assert(contents.include?("launcher_session_gate_consumed"), "Staged launcher dispatch smoke must feed launcher session gate evidence into Compatibility Center")
assert(contents.include?("launcher_session_digest_verified"), "Staged launcher dispatch smoke must feed launcher session digest evidence into Compatibility Center")
assert(contents.include?("launch_authorization_receipt_id"), "Staged launcher dispatch smoke must feed launch authorization receipt id into the KDE Runtime-status request")
assert(contents.include?("managed_launcher_argv_ready"), "Staged launcher dispatch smoke must verify Runtime-status managed launcher argv readiness")
assert(contents.include?("state_root_supplied_by_runtime"), "Staged launcher dispatch smoke must verify Runtime-owned state-root supply")
assert(contents.include?("kde_state_root_access"), "Staged launcher dispatch smoke must verify KDE has no state-root access")
assert(contents.include?("session_sha256"), "Staged launcher dispatch smoke must verify controlled execution session digest evidence")
assert(contents.include?("dispatch_smoke_request_type"), "Staged launcher dispatch smoke must verify the controlled dispatch smoke request type")
assert(contents.include?("staged_launcher_verified"), "Staged launcher dispatch smoke must verify staged launcher evidence visibility")
assert(contents.include?("runtime_dispatch_verified"), "Staged launcher dispatch smoke must verify Runtime dispatch evidence visibility")
assert(contents.include?("request_objects_created"), "Staged launcher dispatch smoke must verify controlled request object creation")
assert(contents.include?("launch_authorization_required"), "Staged launcher dispatch smoke must keep launch authorization visible")
assert(contents.include?("desktop_launch_enabled"), "Staged launcher dispatch smoke must keep desktop launch disabled in Center evidence")
assert(contents.include?("SKIP:"), "Staged launcher dispatch smoke must skip when external smoke prerequisites are missing")
assert(contents.include?("PASS:"), "Staged launcher dispatch smoke must print a pass marker")
assert(container_script.read.include?("staged-launcher-dispatch-smoke"), "Container CLI must expose staged-launcher-dispatch-smoke")
assert(container_model.read.include?("staged_launcher_dispatch_smoke_command"), "Container model must expose staged launcher dispatch smoke command")

stdout, stderr, status = Open3.capture3("ruby", script.to_s)
assert(status.success?, "Staged launcher dispatch smoke script must pass or skip cleanly: #{stderr}")
assert(stdout.include?("PASS: staged managed launcher dispatch smoke") || stdout.include?("SKIP: staged managed launcher dispatch smoke"),
       "Staged launcher dispatch smoke script must print a pass or skip marker")

puts "PASS: staged launcher dispatch smoke script unit tests"
