# frozen_string_literal: true

require "json"
require "optparse"
require "pathname"

module Xnix
  module Image
    # KdeImage is the single source of truth for the Xnix KDE Plasma
    # atomic image (Delivery Sequence step 1). It loads the checked-in
    # manifest, validates that every artifact/overlay it references
    # actually exists in the repository, and renders a bootc Containerfile
    # from the manifest so the definition and the build recipe can never
    # drift apart.
    #
    # The heavy compose (a multi-GB Fedora Kinoite image) runs on a
    # privileged podman/bootc build host. Everything in this class is pure
    # data + rendering and runs anywhere Ruby runs, including the
    # constrained CI container.
    class KdeImage
      CLI_COMMAND = "xnix-kde-image"

      REQUIRED_MANIFEST_KEYS = %w[
        schema image_name base_image architecture build_mode desktop
        package_groups layered_artifacts config_overlays enabled_units
        first_boot kde_entry_points boot_smoke provenance
      ].freeze

      REQUIRED_PACKAGE_GROUPS = %w[plasma_desktop xdg_portals xnix_runtime].freeze

      EXPECTED_KDE_ENTRY_POINTS = %w[
        compatibility-center krunner kwin dolphin
        system-tray notifications system-settings
      ].freeze

      class ManifestError < StandardError; end

      def self.default_manifest_path(project_root)
        Pathname.new(project_root).join("image/kinoite/manifest.json")
      end

      def initialize(project_root:, manifest_path: nil)
        @project_root = Pathname.new(project_root)
        @manifest_path = Pathname.new(manifest_path || self.class.default_manifest_path(@project_root))
        @manifest = load_manifest
      end

      attr_reader :manifest

      def version
        @version ||= @project_root.join("VERSION").read.strip
      end

      # Structural + on-disk validation. Returns an array of human-readable
      # problem strings; empty means the definition is internally consistent
      # and every referenced file is present.
      def problems
        issues = []
        issues.concat(missing_manifest_keys)
        issues.concat(package_group_problems)
        issues.concat(missing_source_files)
        issues.concat(entry_point_problems)
        issues.concat(enabled_unit_problems)
        issues.concat(boot_marker_problems)
        issues
      end

      def valid?
        problems.empty?
      end

      # Every repository file the image build must copy in, deduplicated,
      # as project-relative paths.
      def referenced_sources
        (artifact_sources + overlay_sources).uniq
      end

      # Render a bootc Containerfile from the manifest. This is the exact
      # recipe a build host runs; the checked-in Containerfile is a snapshot
      # of this output and a test guards against drift.
      def render_containerfile
        lines = []
        lines << "# GENERATED by #{CLI_COMMAND} -- edit image/kinoite/manifest.json, not this file."
        lines << "# Xnix KDE Plasma atomic image (Fedora Kinoite-compatible, bootc image mode)."
        lines << "FROM #{manifest.fetch('base_image')}"
        lines << ""
        lines << "LABEL org.xnix.image=\"#{manifest.fetch('image_name')}\""
        lines << "LABEL org.xnix.flagship=\"#{manifest.dig('desktop', 'environment')}\""
        lines << ""
        lines << "# --- Desktop, portal, and runtime packages -------------------------"
        lines << rpm_ostree_install_block
        lines << ""
        lines << "# --- Layered Xnix runtime + KDE entry-point artifacts --------------"
        artifact_copy_lines.each { |line| lines << line }
        lines << ""
        lines << "# --- Image configuration overlays ----------------------------------"
        overlay_copy_lines.each { |line| lines << line }
        lines << ""
        lines << "# --- Presets: enable the graphical login + runtime daemon ----------"
        lines << "RUN systemctl preset-all"
        lines << ""
        lines << "# bootc build validation keeps the ostree commit consistent."
        lines << "RUN bootc container lint || true"
        lines.join("\n") + "\n"
      end

      def to_h
        {
          "version" => version,
          "artifact_type" => "kde-plasma-atomic-image",
          "image_name" => manifest.fetch("image_name"),
          "base_image" => manifest.fetch("base_image"),
          "architecture" => manifest.fetch("architecture"),
          "build_mode" => manifest.fetch("build_mode"),
          "desktop" => manifest.fetch("desktop"),
          "package_count" => package_names.length,
          "referenced_sources" => referenced_sources,
          "enabled_units" => manifest.fetch("enabled_units"),
          "kde_entry_points" => manifest.fetch("kde_entry_points"),
          "runtime_owned" => manifest.dig("provenance", "runtime_owned"),
          "kde_policy_owner" => manifest.dig("provenance", "kde_policy_owner"),
          "privileged_build_required" => manifest.dig("provenance", "privileged_build_required"),
          "valid" => valid?,
          "problems" => problems
        }
      end

      def to_json(*args)
        JSON.pretty_generate(to_h, *args)
      end

      private

      attr_reader :project_root, :manifest_path

      def load_manifest
        raise ManifestError, "manifest not found: #{manifest_path}" unless manifest_path.file?

        JSON.parse(manifest_path.read)
      rescue JSON::ParserError => e
        raise ManifestError, "manifest is not valid JSON (#{manifest_path}): #{e.message}"
      end

      def package_names
        REQUIRED_PACKAGE_GROUPS.flat_map { |group| Array(manifest.dig("package_groups", group)) }
      end

      def artifact_sources
        Array(manifest["layered_artifacts"]).map { |item| item.fetch("source") }
      end

      def overlay_sources
        Array(manifest["config_overlays"]).map { |item| item.fetch("source") }
      end

      def missing_manifest_keys
        REQUIRED_MANIFEST_KEYS.reject { |key| manifest.key?(key) }
                              .map { |key| "manifest is missing required key: #{key}" }
      end

      def package_group_problems
        REQUIRED_PACKAGE_GROUPS.flat_map do |group|
          packages = manifest.dig("package_groups", group)
          if packages.nil? || packages.empty?
            ["package group '#{group}' must list at least one package"]
          else
            []
          end
        end
      end

      def missing_source_files
        referenced_sources.reject { |rel| project_root.join(rel).exist? }
                          .map { |rel| "referenced source does not exist: #{rel}" }
      end

      def entry_point_problems
        missing = EXPECTED_KDE_ENTRY_POINTS - Array(manifest["kde_entry_points"])
        missing.map { |point| "manifest must cover KDE entry point: #{point}" }
      end

      def enabled_unit_problems
        return ["manifest must enable sddm.service to reach a graphical login"] unless
          Array(manifest["enabled_units"]).include?("sddm.service")

        []
      end

      def boot_marker_problems
        markers = manifest.dig("boot_smoke", "expect_serial_markers")
        return ["boot_smoke must list at least one expected serial marker"] if markers.nil? || markers.empty?

        []
      end

      def rpm_ostree_install_block
        packages = package_names
        indented = packages.each_with_index.map do |pkg, index|
          suffix = index == packages.length - 1 ? "" : " \\"
          "        #{pkg}#{suffix}"
        end
        (["RUN rpm-ostree install --idempotent \\"] + indented).join("\n")
      end

      def artifact_copy_lines
        Array(manifest["layered_artifacts"]).map do |item|
          "COPY #{item.fetch('source')} #{item.fetch('dest')}"
        end
      end

      def overlay_copy_lines
        Array(manifest["config_overlays"]).map do |item|
          "COPY #{item.fetch('source')} #{item.fetch('dest')}"
        end
      end
    end
  end
end

if $PROGRAM_NAME == __FILE__
  options = { project_root: Pathname.new(__dir__).join("../../..").realpath.to_s }
  subcommand = ARGV.shift || "validate"

  OptionParser.new do |parser|
    parser.banner = "Usage: #{Xnix::Image::KdeImage::CLI_COMMAND} {validate|report|containerfile} [options]"
    parser.on("--project-root PATH", "Project root (defaults to repository root)") do |value|
      options[:project_root] = value
    end
    parser.on("--manifest PATH", "Manifest path override") do |value|
      options[:manifest_path] = value
    end
  end.parse!(ARGV)

  image = Xnix::Image::KdeImage.new(
    project_root: options[:project_root],
    manifest_path: options[:manifest_path]
  )

  case subcommand
  when "validate"
    problems = image.problems
    if problems.empty?
      puts "PASS: #{image.manifest.fetch('image_name')} image definition is consistent"
    else
      problems.each { |problem| warn "FAIL: #{problem}" }
      exit 1
    end
  when "report"
    puts image.to_json
  when "containerfile"
    print image.render_containerfile
  else
    warn "Unknown subcommand: #{subcommand}"
    exit 2
  end
end
