#!/usr/bin/env ruby
# frozen_string_literal: true

registry_path = File.expand_path("../../runtime/recipes/registry.json", __dir__)
common_args = [
  "--registry",
  registry_path,
  "--app",
  "org.xnix.sample.notepad"
]

case ARGV
when ["desktop-entry-preview", *common_args]
  puts [
    "[Desktop Entry]",
    "Type=Application",
    "Version=1.0",
    "Name=Sample Notepad",
    "Comment=Run with Xnix Compatibility Runtime",
    "Exec=xnix-compat-launch --app org.xnix.sample.notepad %U",
    "Icon=accessories-text-editor",
    "Categories=Utility;",
    "StartupNotify=true",
    "StartupWMClass=xnix-org.xnix.sample.notepad",
    "X-Xnix-ApplicationId=org.xnix.sample.notepad",
    "X-Xnix-RuntimeOwned=true",
    "X-Xnix-Renderer=fake-runtime-go",
    "MimeType=application/x-xnix-log;application/x-xnix-txt;"
  ].join("\n")
when ["mimeapps-preview", *common_args]
  puts [
    "[Default Applications]",
    "application/x-xnix-log=xnix-org.xnix.sample.notepad.desktop",
    "application/x-xnix-txt=xnix-org.xnix.sample.notepad.desktop",
    "",
    "[Added Associations]",
    "application/x-xnix-log=xnix-org.xnix.sample.notepad.desktop;",
    "application/x-xnix-txt=xnix-org.xnix.sample.notepad.desktop;"
  ].join("\n")
else
  abort "usage"
end
